Repository scp-fs2open/fs2open.github.com, pull requests merged in 2018-03, with the labels that each got.

#1627 Add a mechanism for batching line draw calls
  code/graphics/2d.h
  code/graphics/line_draw_list.cpp
  code/graphics/line_draw_list.h
  code/graphics/opengl/gropengltnl.cpp
  code/graphics/paths/NanoVGRenderer.cpp
  code/hud/hudbrackets.cpp
  code/hud/hudbrackets.h
  code/hud/hudtargetbox.cpp
  code/missionui/missionshipchoice.cpp
  code/missionui/missionweaponchoice.cpp
  code/scripting/api/objs/graphics.cpp
  code/source_groups.cmake
  code/tracing/categories.cpp
  code/tracing/categories.h
Labels: bugfix

#1624 Remove gr_set_fog
  code/graphics/2d.h
  code/graphics/grstub.cpp
  code/graphics/material.cpp
  code/graphics/material.h
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropengltnl.cpp
  code/graphics/uniforms.cpp
  code/nebula/neb.cpp
  code/object/objectsort.cpp
  code/starfield/starfield.cpp
Labels: cleanup

#1626 Use vertex interface blocks for vertex shader attributes
  code/def_files/data/effects/main-f.sdr
  code/def_files/data/effects/main-g.sdr
  code/def_files/data/effects/main-v.sdr
Labels: cleanup

#1635 Handle emissive light properly in nebulas
  code/def_files/data/effects/main-f.sdr
Labels: bugfix

#1639 Move gamma correction into common header
  code/def_files/data/effects/batched-f.sdr
  code/def_files/data/effects/decal-f.sdr
  code/def_files/data/effects/default-material-f.sdr
  code/def_files/data/effects/effect-particle-f.sdr
  code/def_files/data/effects/gamma.sdr
  code/def_files/data/effects/main-f.sdr
  code/def_files/data/effects/passthrough-f.sdr
  code/def_files/data/effects/shield-impact-f.sdr
  code/def_files/data/effects/tonemapping-f.sdr
  code/source_groups.cmake
Labels: cleanup

#1641 Load unloaded sounds when trying to determine sound length
  code/gamesnd/gamesnd.cpp
Labels: bugfix

#1643 Fix stencil rendering in hardpoint rendering
  code/graphics/material.cpp
  code/graphics/material.h
  code/graphics/opengl/gropengl.cpp
  code/hud/hudtarget.cpp
  code/model/model.h
  code/model/modelrender.cpp
Labels: bugfix

#1644 Improve handling of nebula fog for deferred lighting
  code/def_files/data/effects/fog-f.sdr
  code/graphics/2d.h
  code/graphics/opengl/gropengldeferred.cpp
  code/graphics/opengl/gropenglshader.cpp
  code/model/modelrender.cpp
  code/nebula/neb.cpp
  code/source_groups.cmake
Labels: bugfix

#1646 Avoid reusing model material instance when setting fog
  code/model/modelrender.cpp
Labels: bugfix

#1649 Fix rendering position of hardpoint models
  code/hud/hudtarget.cpp
Labels: bugfix

#1632 Add normal map rendering to decals
  code/decals/decals.cpp
  code/def_files/data/effects/decal-f.sdr
  code/def_files/data/effects/decal-v.sdr
  code/def_files/data/effects/deferred-f.sdr
  code/def_files/data/effects/normals.sdr
  code/graphics/2d.h
  code/graphics/decal_draw_list.cpp
  code/graphics/decal_draw_list.h
  code/graphics/material.cpp
  code/graphics/material.h
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropengldraw.cpp
  code/graphics/opengl/gropenglstate.cpp
  code/graphics/opengl/gropenglstate.h
  code/graphics/opengl/gropengltnl.cpp
  code/graphics/util/uniform_structs.h
  code/source_groups.cmake
  lib/opengl/gl/extensions.txt
  lib/opengl/gl/glad/include/glad/glad.h
  lib/opengl/gl/glad/src/glad.c
  lib/opengl/gl/glad_wgl/include/glad/glad_wgl.h
  lib/opengl/gl/glad_wgl/src/glad_wgl.c
Labels: enhancement

#1610 Allow mods to specify the window icon
  code/bmpman/bmpman.cpp
  code/bmpman/bmpman.h
  code/def_files/data/maps/app_icon.png
  code/def_files/data/maps/app_icon_d.png
  code/def_files/data/maps/app_icon_sse.png
  code/def_files/data/maps/app_icon_sse_d.png
  code/graphics/2d.cpp
  code/io/cursor.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/source_groups.cmake
  freespace2/resources.cmake
Labels: enhancement

#1656 Disable building targets with runtime DLLs as default
  ci/appveyor/build.ps1
  qtfred/CMakeLists.txt
Labels: bugfix

#1661 Fix wrong return value when getting boolean value from Lua
  code/scripting/lua/LuaConvert.cpp
Labels: bugfix

#1660 Make the OGL_Anisotropy setting more usable
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
  code/graphics/opengl/gropengltexture.cpp
Labels: enhancement

#1657 Add SEXP tree context menu building
  qtfred/source_groups.cmake
  qtfred/src/main.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/ui/util/menu.cpp
  qtfred/src/ui/util/menu.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: qtfred

#1671 Assign minimum and maximum value properly in RandomRange
  code/utils/RandomRange.h
Labels: bugfix
