Repository scp-fs2open/fs2open.github.com, pull requests merged in 2018-07, with the labels that each got.

#1779 Stop accessing Ships[] array with an objnum.
  code/scripting/api/objs/ship.cpp
Labels: bugfix

#1771 Add scripting API for manipulating mission backgrounds
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/background_element.cpp
  code/scripting/api/objs/background_element.h
  code/scripting/lua.cpp
  code/source_groups.cmake
Labels: enhancement

#1778 Add more generic scripting callback system
  .clang-format
  code/object/object.cpp
  code/object/object.h
  code/scripting/ade.cpp
  code/scripting/api/LuaEventCallback.cpp
  code/scripting/api/LuaEventCallback.h
  code/scripting/api/objs/object.cpp
  code/source_groups.cmake
  code/utils/event.h
Labels: enhancement

#1781 Fix inconsistency in Lua background API documenation
  code/scripting/api/libs/mission.cpp
Labels: bugfix

#1782 Remove hack for On Frame scripting hook and quit mission popup
  code/graphics/2d.cpp
  code/io/keycontrol.cpp
  code/io/keycontrol.h
Labels: bugfix, cleanup

#1780 Retry prebuilt library download if it fails
  lib/prebuilt.cmake
Labels: bugfix

#1783 Lua's createShip() function now checks for a valid ship class.
  code/scripting/api/libs/mission.cpp
  code/ship/ship.cpp
Labels: bugfix

#1777 Use strongly-typed handles for sound entries
  code/gamesnd/gamesnd.cpp
  code/menuui/optionsmenu.cpp
  code/mission/missionmessage.cpp
  code/mission/missionmessage.h
  code/mission/missiontraining.cpp
  code/network/multi_voice.cpp
  code/scripting/api/libs/audio.cpp
  code/scripting/api/objs/message.cpp
  code/scripting/api/objs/sound.cpp
  code/scripting/api/objs/sound.h
  code/ship/shipfx.cpp
  code/sound/channel.h
  code/sound/ds.h
  code/sound/sound.cpp
  code/sound/sound.h
Labels: bugfix, cleanup

#1787 Don't make invalid data in campaign file fatal
  code/pilotfile/csg.cpp
Labels: bugfix

#1786 Fix bounds check and string->int conversion in lua ship classes API
  code/scripting/api/libs/tables.cpp
Labels: bugfix

#1784 Make parse_weapon_targeting_priorities() work when weapon missing.
  code/ship/ship.cpp
Labels: bugfix, cleanup

#1631 Feature/eternal variables
  code/mission/missioncampaign.cpp
  code/mission/missioncampaign.h
  code/mission/missionparse.cpp
  code/missionui/missiondebrief.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/pilotfile/csg.cpp
  code/scripting/api/objs/sexpvar.cpp
  fred2/addvariabledlg.cpp
  fred2/addvariabledlg.h
  fred2/fred.rc
  fred2/missionsave.cpp
  fred2/modifyvariabledlg.cpp
  fred2/modifyvariabledlg.h
  fred2/resource.h
  fred2/sexp_tree.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/missionsave.cpp
Labels: bugfix, enhancement

#1793 Add support for movies with RGB(A) pixel format
  code/cfile/cfile.cpp
  code/cutscene/Decoder.cpp
  code/cutscene/Decoder.h
  code/cutscene/VideoPresenter.cpp
  code/cutscene/VideoPresenter.h
  code/cutscene/ffmpeg/FFMPEGDecoder.cpp
  code/cutscene/ffmpeg/VideoDecoder.cpp
  code/cutscene/ffmpeg/VideoDecoder.h
Labels: enhancement

#1794 Add scripting API for displaying movie files
  code/cutscene/ffmpeg/FFMPEGDecoder.cpp
  code/cutscene/movie.cpp
  code/cutscene/player.cpp
  code/cutscene/player.h
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/libs/graphics.h
  code/scripting/api/libs/time_lib.cpp
  code/scripting/api/libs/time_lib.h
  code/scripting/api/objs/movie_player.cpp
  code/scripting/api/objs/movie_player.h
  code/scripting/api/objs/time_obj.cpp
  code/scripting/api/objs/time_obj.h
  code/scripting/lua.cpp
  code/source_groups.cmake
Labels: enhancement

#1789 Fix assert in ship_cleanup
  code/ship/ship.cpp
Labels: bugfix

#1772 CMake: Unify how source files are added to CMake
  cmake/util.cmake
  code/CMakeLists.txt
  code/default_files.cmake
  code/source_groups.cmake
  qtfred/source_groups.cmake
  test/src/source_groups.cmake
Labels: cleanup, enhancement

#1796 Use byte offset into immediate buffer for movie rendering
  code/cutscene/VideoPresenter.cpp
  code/graphics/2d.h
  code/graphics/grstub.cpp
  code/graphics/opengl/gropengldraw.cpp
  code/graphics/opengl/gropengldraw.h
Labels: bugfix

#1797 Use type-safe handles for particle effects
  code/asteroid/asteroid.cpp
  code/particle/ParticleManager.cpp
  code/particle/ParticleManager.h
  code/particle/effects/CompositeEffect.cpp
  code/particle/effects/GenericShapeEffect.h
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/beam.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: bugfix, cleanup

#1798 Convert debris object count Assert to Error
  code/model/modelread.cpp
Labels: cleanup

#1137 Add a lua loader that uses the CFile system
  .clang-tidy
  ci/travis/script.sh
  ci/travis/valgrind.supp
  code/def_files/data/scripts/cfile_require.lua
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/scripting/ade.cpp
  code/scripting/ade.h
  code/scripting/lua.cpp
  code/source_groups.cmake
  test/gtest/include/gtest/internal/gtest-internal.h
  test/gtest/include/gtest/internal/gtest-port.h
  test/src/scripting/require.cpp
  test/src/source_groups.cmake
  test/src/util/FSTestFixture.cpp
  test/test_data/scripting/require/defaultRequire/data/scripts/lib.lua
  test/test_data/scripting/require/defaultRequire/data/scripts/test.lua
  test/test_data/scripting/require/overrideRequire/data/scripts/cfile_require.lua
  test/test_data/scripting/require/overrideRequire/data/scripts/test.lua
  test/test_data/scripting/require/overrideRequire/data/tables/scripting-mod.tbm
Labels: enhancement

#1807 Fix crash on game shutdown if Lua object callbacks are used
  code/object/object.cpp
  code/object/object.h
  freespace2/freespace.cpp
Labels: bugfix

#1746 Add ship display name feature
  code/hud/hudescort.cpp
  code/hud/hudmessage.cpp
  code/hud/hudobserver.cpp
  code/hud/hudsquadmsg.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/io/keycontrol.cpp
  code/mission/missionhotkey.cpp
  code/mission/missionlog.cpp
  code/mission/missionlog.h
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/network/multi_pmsg.cpp
  code/network/multimsgs.cpp
  code/network/multimsgs.h
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  fred2/missionsave.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/missionsave.cpp
Labels: enhancement

#1801 Add CFile API for specifying the file location
  code/bmpman/bmpman.cpp
  code/cfile/cfile.cpp
  code/cfile/cfile.h
  code/cfile/cfilesystem.cpp
  code/cfile/cfilesystem.h
  code/graphics/generic.cpp
  code/graphics/opengl/gropenglshader.cpp
  code/hud/hudconfig.cpp
  code/lab/lab.cpp
  code/menuui/barracks.cpp
  code/menuui/playermenu.cpp
  code/mission/missioncampaign.cpp
  code/pilotfile/csg.cpp
  code/pilotfile/csg_convert.cpp
  code/pilotfile/pilotfile_convert.cpp
  code/pilotfile/plr.cpp
  code/pilotfile/plr_convert.cpp
  code/playerman/managepilot.cpp
  code/sound/ffmpeg/WaveFile.cpp
  fred2/campaigneditordlg.cpp
  fred2/mainfrm.cpp
  qtfred/src/mission/Editor.cpp
  test/src/cfile/cfile.cpp
Labels: cleanup, enhancement

#1810 Fix MSVC linking issue in new Discord Code
  lib/discord/src/CMakeLists.txt
Labels: bugfix

#1811 Properly handle invalid UTF-8 sequences in NanoVG
  code/graphics/paths/NanoVGRenderer.cpp
  code/graphics/paths/nanovg/fontstash.h
  code/graphics/paths/nanovg/nanovg.c
Labels: bugfix

#1785 Use strongly typed handles for sound handles
  code/cutscene/player.cpp
  code/gamesnd/gamesnd.cpp
  code/hud/hud.cpp
  code/hud/hudlock.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/hud/hudtargetbox.h
  code/menuui/mainhallmenu.cpp
  code/menuui/optionsmenu.cpp
  code/menuui/optionsmenumulti.cpp
  code/mission/missionbriefcommon.cpp
  code/mission/missionmessage.cpp
  code/mission/missionmessage.h
  code/mission/missiontraining.cpp
  code/network/multi_pause.cpp
  code/network/multi_voice.cpp
  code/object/collideshipship.cpp
  code/object/objectsnd.cpp
  code/object/objectsnd.h
  code/playerman/managepilot.cpp
  code/playerman/player.h
  code/playerman/playercontrol.cpp
  code/radar/radar.cpp
  code/radar/radar.h
  code/radar/radardradis.cpp
  code/radar/radardradis.h
  code/radar/radarorb.cpp
  code/radar/radarorb.h
  code/radar/radarsetup.cpp
  code/radar/radarsetup.h
  code/scripting/api/libs/audio.cpp
  code/scripting/api/objs/sound.cpp
  code/scripting/api/objs/sound.h
  code/ship/afterburner.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipfx.cpp
  code/ship/shipfx.h
  code/sound/channel.h
  code/sound/ds.cpp
  code/sound/ds.h
  code/sound/openal.h
  code/sound/rtvoice.cpp
  code/sound/rtvoice.h
  code/sound/sound.cpp
  code/sound/sound.h
  code/weapon/beam.cpp
  code/weapon/beam.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
  freespace2/freespace.cpp
Labels: cleanup, enhancement

#1813 Fix crash when launching FSO without a mod option
  code/graphics/opengl/gropenglshader.cpp
Labels: bugfix

#1816 Don't reset mission file name on mission end
  code/libs/discord/discord.cpp
  freespace2/freespace.cpp
Labels: bugfix
