Repository scp-fs2open/fs2open.github.com, pull requests merged in 2018-10, with the labels that each got.

#1890 Fix missing Warpin sounds from Hyperspace Warpin Effect
  code/ship/shipfx.cpp
  code/ship/shipfx.h
Labels: bugfix

#1891 Switch communication messages to use SCP_string
  code/hud/hudsquadmsg.cpp
  code/hud/hudsquadmsg.h
  fred2/ignoreordersdlg.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: cleanup, enhancement

#1880 add ai-play-dead-persistent
  code/ai/aigoals.cpp
  code/ai/aigoals.h
  code/def_files/data/tables/objecttypes.tbl
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/enums.h
  code/scripting/api/objs/order.cpp
  code/scripting/api/objs/ship.cpp
  fred2/fredview.cpp
  fred2/management.cpp
  fred2/missionsave.cpp
  fred2/shipgoalsdlg.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/missionsave.cpp
Labels: discussion, enhancement

#1911 Add option for disabling spark spawning for subsystem
  code/model/model_flags.h
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shiphit.cpp
Labels: enhancement
