Repository scp-fs2open/fs2open.github.com, pull requests merged in 2018-09, with the labels that each got.

#1845 Disable movie looping for MVE cutscenes
  code/cutscene/ffmpeg/FFMPEGDecoder.cpp
Labels: bugfix

#1846 Fix nebula background rendering
  code/def_files/data/effects/fog-f.sdr
Labels: bugfix

#1849 Apply clipping offsets when using the line draw list
  code/graphics/line_draw_list.cpp
Labels: bugfix

#1850 Handle DIRECTIVE_WING_ZERO in is-destroyed SEXPs correctly
  code/parse/sexp.cpp
Labels: bugfix

#1853 Write SDL version to debug log
  code/osapi/osapi.cpp
Labels: enhancement

#1854 Fix share_fire_direction logic
  code/ship/ship.cpp
Labels: bugfix

#1856 add reset-post-effects sexp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/scripting/api/libs/graphics.cpp
Labels: enhancement

#1859 Add support for looping particles
  code/particle/particle.cpp
  code/particle/particle.h
  code/scripting/api/objs/particle.cpp
Labels: enhancement

#1871 Remove release build uploading to transfer.sh
  ci/travis/release.sh
Labels: bugfix

#1872 Disable libRocket unless unicode mode is active
  code/scpui/rocket_ui.cpp
Labels: bugfix

#1879 always choose a dock leader in FRED
  code/mission/missionparse.cpp
Labels: bugfix

#1875 Remove duplicate shadow FBO creation
  code/graphics/opengl/gropenglpostprocessing.cpp
  code/graphics/opengl/gropengltnl.cpp
Labels: bugfix, cleanup

#1862 Add scripting features for barracks libRocket UI
  code/menuui/barracks.cpp
  code/osapi/dialogs.cpp
  code/playerman/managepilot.cpp
  code/scpui/RocketFileInterface.cpp
  code/scpui/RocketFileInterface.h
  code/scpui/RocketSystemInterface.cpp
  code/scpui/RocketSystemInterface.h
  code/scripting/api/libs/base.cpp
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/player.cpp
  code/scripting/api/objs/player.h
  code/scripting/api/objs/shipclass.cpp
  freespace2/freespace.cpp
Labels: enhancement

#1882 Disable Linux qtFRED building again
  ci/travis/release.sh
Labels: bugfix, cleanup

#1883 Fix linux release building
  ci/travis/before_script.sh
  ci/travis/release.sh
Labels: bugfix
