Repository scp-fs2open/fs2open.github.com, pull requests merged in 2018-11, with the labels that each got.

#1917 Add arrow key scrolling to the lab
  code/lab/lab.cpp
  code/lab/wmcgui.cpp
  code/lab/wmcgui.h
Labels: enhancement

#1920 Make the lab camera better
  code/lab/lab.cpp
Labels: bugfix, cleanup

#1923 Cleanup the speech API code a bit
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
  code/sound/fsspeech.cpp
  code/sound/fsspeech.h
  code/sound/speech.h
  freespace2/freespace.cpp
Labels: cleanup

#1912 Remove -old_collision command line option
  code/autopilot/autopilot.cpp
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
  code/debris/debris.cpp
  code/mission/missionparse.cpp
  code/model/modelcollide.cpp
  code/model/modelread.cpp
  code/object/objcollide.cpp
  code/object/objcollide.h
  code/object/object.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/starfield/supernova.cpp
  code/weapon/beam.cpp
  freespace2/freespace.cpp
Labels: cleanup

#1930 Fix Appveyor Qt directory
  appveyor.yml
Labels: bugfix

#1881 Add proper class support to Lua API
  code/scripting/ade.cpp
  code/scripting/ade.h
  code/scripting/ade_api.h
  code/scripting/ade_args.cpp
  code/scripting/ade_args.h
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/libs/testing.cpp
  code/scripting/api/objs/beam.cpp
  code/scripting/api/objs/cockpit_display.cpp
  code/scripting/api/objs/mc_info.cpp
  code/scripting/api/objs/mc_info.h
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/movie_player.cpp
  code/scripting/api/objs/movie_player.h
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/particle.cpp
  code/scripting/api/objs/particle.h
  code/scripting/api/objs/player.cpp
  code/scripting/api/objs/player.h
  code/scripting/api/objs/ship.cpp
  code/scripting/api/objs/streaminganim.cpp
  code/scripting/api/objs/streaminganim.h
  code/scripting/api/objs/texture.cpp
  code/scripting/api/objs/texture.h
  code/scripting/api/objs/texturemap.cpp
  code/scripting/api/objs/waypoint.cpp
  code/scripting/api/objs/weapon.cpp
  code/scripting/lua/LuaConvert.cpp
  code/scripting/lua/LuaConvert.h
  code/scripting/lua/LuaValue.h
  code/scripting/scripting.h
Labels: cleanup, enhancement

#1931 Also fix Appveyor Qt path for nightly builds
  ci/appveyor/build.ps1
Labels: bugfix

#1927 Add additional validity check for decals
  code/decals/decals.cpp
Labels: bugfix

#1933 multi capability for destroy-instantly and destroy-subsys-instantly
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: multi

#1938 Check optional scripting parameters before using them
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/particle.cpp
  code/scripting/api/objs/ship.cpp
  code/scripting/api/objs/texturemap.cpp
Labels: cleanup
