Repository scp-fs2open/fs2open.github.com, pull requests merged in 2018-06, with the labels that each got.

#1721 Fix scrambling unicode messages
  code/globalincs/pstypes.h
  code/globalincs/toolchain/clang.h
  code/globalincs/toolchain/gcc.h
  code/globalincs/toolchain/mingw.h
  code/globalincs/toolchain/msvc.h
  code/mission/missionmessage.cpp
  code/parse/parselo.cpp
  code/utils/unicode.cpp
Labels: bugfix

#1736 Implement various translation features requested by Novachen
  code/hud/hudbrackets.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/io/keycontrol.cpp
  code/lab/lab.cpp
  code/menuui/techmenu.cpp
  code/mission/missionbriefcommon.cpp
  code/missionui/missiondebrief.cpp
  code/missionui/missionshipchoice.cpp
  code/missionui/missionweaponchoice.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/network/multi_ingame.cpp
  code/playerman/playercontrol.cpp
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/weaponclass.cpp
  code/ship/ship.cpp
  code/stats/medals.cpp
  code/stats/medals.h
  code/weapon/emp.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
  freespace2/freespace.cpp
Labels: bugfix, cleanup, enhancement

#1750 Add initial clang-format config file
  .clang-format
Labels: cleanup, enhancement

#1742 Enable log output for qtFRED
  qtfred/src/main.cpp
Labels: bugfix, qtfred

#1749 Add support for external subtitle files
  .clang-format
  code/cfile/cfile.cpp
  code/cutscene/Decoder.h
  code/cutscene/ffmpeg/FFMPEGDecoder.cpp
  code/cutscene/ffmpeg/FFMPEGDecoder.h
  code/cutscene/ffmpeg/SubtitleDecoder.cpp
  code/cutscene/ffmpeg/internal.h
Labels: enhancement

#1743 Respect trailing white space in tstrings.tbl strings
  code/localization/localize.cpp
Labels: bugfix

#1744 Fix OpenAL errors when sound is disabled
  code/sound/ds3d.cpp
Labels: bugfix

#1748 Add macro for marking unreachable code
  code/ai/aicode.cpp
  code/bmpman/bmpman.cpp
  code/cfile/cfile.cpp
  code/gamehelp/contexthelp.cpp
  code/globalincs/alphacolors.cpp
  code/globalincs/toolchain/clang.h
  code/globalincs/toolchain/doxygen.h
  code/globalincs/toolchain/gcc.h
  code/globalincs/toolchain/mingw.h
  code/globalincs/toolchain/msvc.h
  code/graphics/opengl/ShaderProgram.cpp
  code/graphics/opengl/gropenglquery.cpp
  code/graphics/opengl/gropengltnl.cpp
  code/graphics/util/GPUMemoryHeap.cpp
  code/graphics/util/UniformBufferManager.cpp
  code/hud/hudartillery.cpp
  code/io/keycontrol.cpp
  code/missionui/redalert.cpp
  code/object/deadobjectdock.cpp
  code/object/objectdock.cpp
  code/parse/parselo.cpp
  code/parse/sexp/LuaSEXP.cpp
  code/particle/effects/CompositeEffect.cpp
  code/pilotfile/JSONFileHandler.cpp
  code/pilotfile/pilotfile.cpp
  code/ship/ship.cpp
  code/sound/ffmpeg/WaveFile.cpp
  code/tracing/TraceEventWriter.cpp
  code/tracing/tracing.cpp
  code/weapon/beam.cpp
  freespace2/SDLGraphicsOperations.cpp
  qtfred/src/ui/FredView.cpp
Labels: cleanup, enhancement

#1735 Remove unnecessary function pointer dereferences in gr API
  code/graphics/2d.h
Labels: cleanup

#1723 Enable legacy config mode if legacy config is newer
  code/cfile/cfile.cpp
  code/cfile/cfile.h
  code/cfile/cfilesystem.cpp
  code/osapi/osapi.cpp
  code/osapi/osapi.h
  code/osapi/osregistry.cpp
  code/osapi/osregistry.h
  freespace2/freespace.cpp
Labels: bugfix, enhancement

#1725 Render hardpoint model outlines using geometry shaders
  code/def_files/data/effects/main-f.sdr
  code/def_files/data/effects/main-g.sdr
  code/def_files/data/effects/main-v.sdr
  code/graphics/2d.h
  code/graphics/material.cpp
  code/graphics/material.h
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropenglshader.cpp
  code/graphics/uniforms.cpp
  code/graphics/util/uniform_structs.h
  code/hud/hudtarget.cpp
  code/libs/renderdoc/renderdoc.cpp
  code/libs/renderdoc/renderdoc.h
  code/libs/renderdoc/renderdoc_app.h
  code/model/modelrender.cpp
  code/model/modelrender.h
  code/source_groups.cmake
Labels: bugfix, enhancement

#1713 Port goal editor dialog code to qtFRED
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/MissionGoalsDialogModel.cpp
  qtfred/src/mission/dialogs/MissionGoalsDialogModel.h
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
  qtfred/src/ui/dialogs/MissionGoalsDialog.cpp
  qtfred/src/ui/dialogs/MissionGoalsDialog.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
  qtfred/ui/EventEditorDialog.ui
  qtfred/ui/FredView.ui
  qtfred/ui/MissionGoalsDialog.ui
Labels: qtfred

#1659 Delete all objects on mission end (Fix for #1653)
  code/lab/lab.cpp
  code/object/object.cpp
  code/object/object.h
  freespace2/freespace.cpp
Labels: bugfix

#1755 Write full log path and add legacy mode reason to log file
  code/osapi/osapi.cpp
  code/osapi/outwnd.cpp
Labels: enhancement

#1756 Discard submodels by generating clipped vertices
  code/def_files/data/effects/main-f.sdr
  code/def_files/data/effects/main-g.sdr
  code/def_files/data/effects/main-v.sdr
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropengl.h
  code/graphics/opengl/gropenglshader.cpp
  code/graphics/opengl/gropengltnl.cpp
Labels: bugfix

#1761 Fix loading of TGA files with unexpected bit depths
  code/bmpman/bmpman.cpp
Labels: bugfix

#1757 Improve handling of the shader cache
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropengl.h
  code/graphics/opengl/gropenglshader.cpp
Labels: bugfix, enhancement

#1764 Make sure that sound pitch range is initialized properly
  code/gamesnd/gamesnd.cpp
Labels: bugfix

#1762 Purge old shader cache files from file system
  code/graphics/opengl/gropenglshader.cpp
Labels: cleanup, enhancement

#1766 Apply spec_* values to lights in deferred pass
  code/graphics/opengl/gropengldeferred.cpp
Labels: bugfix

#1765 Nolink ballistic primaries no longer disallow linking when depleted.
  code/ship/ship.cpp
Labels: bugfix

#1767 Add AI profile flag to allow primary weapons to consider range.
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aicode.cpp
Labels: enhancement

#1768 Enable cache bitmaps by default and remove option
  code/bmpman/bmpman.cpp
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
Labels: cleanup, enhancement

#1760 Fix GCC8 and FFmpeg warnings
  .travis.yml
  cmake/toolchain-gcc.cmake
  code/bmpman/bmpman.cpp
  code/cfile/cfile.cpp
  code/cfile/cfilesystem.cpp
  code/cutscene/ffmpeg/FFMPEGDecoder.cpp
  code/cutscene/ffmpeg/VideoDecoder.cpp
  code/libs/ffmpeg/FFmpeg.cpp
  code/mission/missioncampaign.cpp
  code/mission/missionmessage.cpp
  code/network/chat_api.cpp
  code/network/multi_pxo.cpp
  code/parse/sexp.cpp
  code/pilotfile/plr.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/stats/medals.cpp
  code/tracing/FrameProfiler.cpp
  code/utils/strings.h
  lib/opengl/gl/CMakeLists.txt
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/missionsave.cpp
Labels: bugfix, cleanup

#1774 Remove "not enough points in path" warning
  code/ai/aicode.cpp
Labels: cleanup

#1773 Validate variable name when adding new variable
  fred2/addvariabledlg.cpp
Labels: bugfix
