Repository scp-fs2open/fs2open.github.com, pull requests merged in 2018-04, with the labels that each got.

#1675 Fix texture detail errors
  code/graphics/opengl/gropengltexture.cpp
Labels: bugfix

#1679 Copy original FRED initialization code
  qtfred/src/main.cpp
  qtfred/src/mission/management.cpp
  qtfred/src/mission/management.h
Labels: bugfix, cleanup, qtfred

#1676 Write EFX support information to JSON output
  code/cmdline/cmdline.cpp
  code/sound/openal.cpp
  code/sound/openal.h
Labels: bugfix

#1669 Add fiction viewer dialog to qtFRED
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/FictionViewerDialogModel.cpp
  qtfred/src/mission/dialogs/FictionViewerDialogModel.h
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
  qtfred/src/ui/dialogs/FictionViewerDialog.cpp
  qtfred/src/ui/dialogs/FictionViewerDialog.h
  qtfred/ui/FictionViewerDialog.ui
  qtfred/ui/FredView.ui
Labels: qtfred, unfinished

#1684 Set team_glow_enabled uniform to proper value
  code/graphics/uniforms.cpp
Labels: bugfix

#1705 Update qtFRED readme and add some documentation
  qtfred/README.md
  qtfred/src/mission/dialogs/AbstractDialogModel.h
Labels: qtfred

#1711 Fix crash on FRED startup in debug mode
  code/osapi/outwnd.cpp
Labels: bugfix

#1673 Reenable FRED building for Appveyor
  CMakeLists.txt
  ci/appveyor/build.ps1
  fred2/fred.cpp
Labels: bugfix

#1700 Fix Windows deployment issue
  qtfred/CMakeLists.txt
  qtfred/src/main.cpp
Labels: bugfix, qtfred

#1665 Validate number of parsed briefing stages and icons
  code/mission/missionparse.cpp
Labels: bugfix

#1662 Fix Assert in Lua API when passing invalid name to mn.WaypointList
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/waypoint.cpp
Labels: bugfix

#1668 Fix various issues detected by MinGW
  cmake/platformChecks.cmake
  cmake/platformChecks.h.in
  cmake/toolchain-gcc.cmake
  code/cfile/cfile.cpp
  code/default_files.cmake
  code/fs2netd/tcp_socket.cpp
  code/globalincs/toolchain/mingw.h
  code/globalincs/toolchain/msvc.h
  code/headtracking/freetrack.cpp
  code/inetfile/cftp.cpp
  code/network/multi_sexp.h
  code/network/multilag.cpp
  code/network/psnet2.cpp
  code/network/stand_gui.cpp
  code/osapi/osregistry.cpp
  code/osapi/outwnd.cpp
  code/source_groups.cmake
  code/utils/strings.h
  code/utils/unicode.h
  code/windows_stub/config.h
  freespace2/freespace.cpp
Labels: bugfix

#1703 Port mission save code to qtFRED
  code/parse/parselo.cpp
  code/parse/parselo.h
  qtfred/source_groups.cmake
  qtfred/src/mission/missionsave.cpp
  qtfred/src/mission/missionsave.h
  qtfred/src/mission/util.cpp
  qtfred/src/mission/util.h
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
Labels: qtfred

#1680 Port event editor dialog code to qtFRED
  code/libs/ffmpeg/FFmpegContext.cpp
  qtfred/source_groups.cmake
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/dialogs/EventEditorDialogModel.cpp
  qtfred/src/mission/dialogs/EventEditorDialogModel.h
  qtfred/src/ui/dialogs/EventEditorDialog.cpp
  qtfred/src/ui/dialogs/EventEditorDialog.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
  qtfred/ui/EventEditorDialog.ui
Labels: qtfred

#1707 Improve handling of non-persistent particles
  code/particle/effects/BeamPiercingEffect.cpp
  code/particle/effects/GenericShapeEffect.h
  code/particle/effects/SingleParticleEffect.cpp
  code/particle/particle.cpp
  code/particle/particle.h
  code/particle/util/ParticleProperties.cpp
  code/particle/util/ParticleProperties.h
  code/scripting/api/libs/testing.cpp
  code/weapon/beam.cpp
  code/weapon/muzzleflash.cpp
  code/weapon/weapons.cpp
Labels: enhancement

#1718 Fix fog rendering in forward renderer
  code/def_files/data/effects/main-f.sdr
  code/model/modelrender.cpp
Labels: bugfix
