Repository scp-fs2open/fs2open.github.com, pull requests merged in 2018-02, with the labels that each got.

#1597 Fix off-by-one error in stuff_int_list
  code/parse/parselo.cpp
Labels: bugfix

#1603 Fix assertion failure in ship_get_sound
  code/ship/ship.cpp
Labels: bugfix

#1607 Don't include the default ai_profiles system in CFile
  code/cfile/cfilesystem.cpp
  code/def_files/ai_profiles.tbl
  code/source_groups.cmake
Labels: bugfix

#1614 Add lua functions for accessing the current engine language
  code/scripting/api/libs/base.cpp
Labels: enhancement

#1618 Make AI profile tables actually stop parsing if #End is missing.
  code/ai/ai_profiles.cpp
Labels: bugfix

#1613 Add support for includes in shader files
  code/def_files/data/effects/deferred-f.sdr
  code/def_files/data/effects/lighting.sdr
  code/def_files/data/effects/main-f.sdr
  code/def_files/data/effects/shadows.sdr
  code/graphics/opengl/gropenglshader.cpp
  code/source_groups.cmake
Labels: enhancement

#1622 Use deferred shader for applying directional lights
  code/def_files/data/effects/deferred-clear-f.sdr
  code/def_files/data/effects/deferred-f.sdr
  code/def_files/data/effects/deferred-v.sdr
  code/def_files/data/effects/lighting.sdr
  code/def_files/data/effects/main-f.sdr
  code/def_files/data/effects/main-v.sdr
  code/def_files/data/effects/shadows.sdr
  code/graphics/2d.h
  code/graphics/material.cpp
  code/graphics/material.h
  code/graphics/opengl/gropengldeferred.cpp
  code/graphics/opengl/gropengldraw.cpp
  code/graphics/opengl/gropengldraw.h
  code/graphics/opengl/gropenglpostprocessing.cpp
  code/graphics/opengl/gropenglshader.cpp
  code/graphics/opengl/gropengltnl.cpp
  code/graphics/opengl/gropengltnl.h
  code/graphics/util/UniformBufferManager.cpp
  code/graphics/util/uniform_structs.h
  code/model/modelrender.cpp
Labels: cleanup
