Repository scp-fs2open/fs2open.github.com, pull requests merged in 2018-08, with the labels that each got.

#1822 Terminate FRED/qtFRED when command line demands it
  fred2/management.cpp
  qtfred/src/mission/management.cpp
Labels: bugfix

#1819 Add C++ operators for vector math operations
  code/globalincs/pstypes.h
  code/math/vecmat.h
Labels: enhancement

#1818 Add support for looping movies
  code/cutscene/Decoder.h
  code/cutscene/ffmpeg/AudioDecoder.cpp
  code/cutscene/ffmpeg/AudioDecoder.h
  code/cutscene/ffmpeg/FFMPEGDecoder.cpp
  code/cutscene/ffmpeg/FFMPEGDecoder.h
  code/cutscene/ffmpeg/SubtitleDecoder.cpp
  code/cutscene/ffmpeg/SubtitleDecoder.h
  code/cutscene/ffmpeg/VideoDecoder.cpp
  code/cutscene/ffmpeg/VideoDecoder.h
  code/cutscene/ffmpeg/internal.h
  code/cutscene/player.cpp
  code/cutscene/player.h
  code/scripting/api/libs/graphics.cpp
Labels: enhancement

#1714 Enable qtFRED for all deployments
  CMakeLists.txt
  ci/appveyor/build.ps1
  ci/travis/before_script.sh
  ci/travis/install.sh
  ci/travis/release.sh
  cmake/AppImage.desktop.in
  cmake/appimage.cmake
  freespace2/CMakeLists.txt
  qtfred/CMakeLists.txt
  qtfred/cmake/AppImage.desktop.in
  qtfred/cmake/AppRun.in
  qtfred/resources/fred_icon.png
Labels: qtfred

#1825 qtfred asteroid editor
  code/globalincs/pstypes.h
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/AsteroidEditorDialogModel.cpp
  qtfred/src/mission/dialogs/AsteroidEditorDialogModel.h
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
  qtfred/src/ui/dialogs/AsteroidEditorDialog.cpp
  qtfred/src/ui/dialogs/AsteroidEditorDialog.h
  qtfred/ui/AsteroidEditorDialog.ui
  qtfred/ui/FredView.ui
Labels: qtfred

#1833 fix bug introduced in pr #1736
  code/missionui/missionweaponchoice.cpp
Labels: bugfix

#1837 add feature: change reticle when autoaim is active
  code/hud/hudparse.cpp
  code/hud/hudreticle.cpp
  code/hud/hudreticle.h
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement

#1841 add per-ship-class scanning range feature
  code/hud/hudtarget.h
  code/playerman/playercontrol.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement
