Repository scp-fs2open/fs2open.github.com, pull requests merged in 2019-02, with the labels that each got.

#1983 some tweaks and minor improvements to ship initialization
  code/ai/aicode.cpp
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  code/scripting/api/libs/mission.cpp
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/ship/shipfx.h
Labels: bugfix, cleanup

#1988 make is-docked work with a single argument
  code/parse/sexp.cpp
Labels: bug

#1994 Add CircleCI config file
  .circleci/config.yml
  code/cutscene/cutscenes.h
  code/gamesnd/gamesnd.h
  code/pilotfile/csg_convert.cpp
  code/pilotfile/pilotfile_convert.cpp
  code/pilotfile/pilotfile_convert.h
Labels: enhancement

#1908 Add scripting file handle auto-closing and error message
  code/cfile/cfile.h
  code/scripting/api/libs/cfile.cpp
  code/scripting/api/objs/file.cpp
  code/scripting/api/objs/file.h
Labels: bugfix, cleanup
