Repository scp-fs2open/fs2open.github.com, pull requests merged in 2019-12, with the labels that each got.

#2051 Make Lua documentation generation more generic
  .clang-tidy
  .travis.yml
  ci/travis/before_install.sh
  ci/travis/before_script.sh
  ci/travis/clang-tidy-diff.py
  ci/travis/clang_tidy.sh
  ci/travis/install.sh
  ci/travis/script.sh
  cmake/platform-unix.cmake
  cmake/toolchain-clang.cmake
  code/cmdline/cmdline.cpp
  code/scripting/ade.cpp
  code/scripting/ade.h
  code/scripting/ade_api.h
  code/scripting/api/libs/audio.cpp
  code/scripting/api/libs/base.cpp
  code/scripting/api/libs/cfile.cpp
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/libs/hud.cpp
  code/scripting/api/libs/options.cpp
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/beam.cpp
  code/scripting/api/objs/cockpit_display.cpp
  code/scripting/api/objs/control_info.cpp
  code/scripting/api/objs/file.cpp
  code/scripting/api/objs/mc_info.cpp
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/movie_player.cpp
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/option.cpp
  code/scripting/api/objs/sound.cpp
  code/scripting/api/objs/streaminganim.cpp
  code/scripting/api/objs/subsystem.cpp
  code/scripting/api/objs/team.cpp
  code/scripting/api/objs/texture.cpp
  code/scripting/api/objs/vecmath.cpp
  code/scripting/api/objs/weapon.cpp
  code/scripting/lua.cpp
  code/scripting/scripting.cpp
  code/scripting/scripting.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: enhancement

#2177 Make 2D sounds play from front speakers instead of rear.
  code/sound/ds.cpp
Labels: bugfix

#2179 Fix some CI issues
  .travis.yml
  ci/travis/clang_tidy.sh
Labels: bugfix

#2185 Standardize nonstandard "+nocreate" behavior in objecttypes.tbl
  code/ship/ship.cpp
Labels: cleanup

#2052 Add scripting API support for model paths
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/objs/beam.cpp
  code/scripting/api/objs/camera.cpp
  code/scripting/api/objs/model_path.cpp
  code/scripting/api/objs/model_path.h
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/order.cpp
  code/scripting/api/objs/ship.cpp
  code/scripting/api/objs/subsystem.cpp
  code/scripting/api/objs/subsystem.h
  code/scripting/api/objs/weapon.cpp
  code/scripting/lua.cpp
  code/scripting/scripting.cpp
  code/scripting/scripting.h
  code/source_groups.cmake
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
Labels: enhancement

#2147 Add Lua access to not yet arrived ships
  .clang-tidy
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/parse_object.cpp
  code/scripting/api/objs/parse_object.h
  code/source_groups.cmake
Labels: enhancement

#2201 Make Dinky Shockwaves not dinky by default.
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/weapon/weapons.cpp
Labels: bugfix, regression
