Repository scp-fs2open/fs2open.github.com, pull requests merged in 2019-10, with the labels that each got.

#1540 Extends the existing parse pausing system (used by bmpman) to use a
  code/parse/parselo.cpp
  code/parse/parselo.h
Labels: enhancement

#2103 this error message should report the variable name
  code/mission/missionparse.cpp
Labels: bugfix

#2108 Only update arrival/departure location if ship is not part of a wing
  fred2/missionsave.cpp
  fred2/shipeditordlg.cpp
  qtfred/src/mission/missionsave.cpp
Labels: bugfix

#2106 implement Mantis 3204
  code/mission/mission_flags.h
  code/parse/sexp.cpp
  fred2/fred.rc
  fred2/missionnotesdlg.cpp
  fred2/missionnotesdlg.h
  fred2/resource.h
  fred2/voiceactingmanager.cpp
Labels: enhancement

#2104 fix issue #1221
  code/cmdline/cmdline.cpp
Labels: bugfix

#2102 fix default loop increment in for-counter
  code/parse/sexp.cpp
Labels: bugfix

#2100 Handle pausing and unpausing music in certain screens
  code/io/keycontrol.cpp
  code/menuui/optionsmenu.cpp
Labels: bugfix

#2105 miscellaneous XSTR cleanup
  code/parse/sexp.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: cleanup

#2111 Move filename sort in cf_get_file_list() to before packfile search.
  code/cfile/cfilesystem.cpp
Labels: bugfix, regression

#2112 Make .csg loading code check rp_dist, just like .plr loading does.
  code/pilotfile/csg.cpp
Labels: bugfix

#2113 Give PNG warnings their own category, so they're hidden by default.
  code/pngutils/pngutils.cpp
Labels: cleanup

#2116 Fix #2086: Detect unsupported characters in root paths
  .clang-tidy
  code/cfile/cfilesystem.cpp
  code/osapi/osapi.cpp
Labels: bugfix

#2119 Clear object events when Lua state is shut down
  code/object/object.cpp
Labels: bugfix

#2128 fix an oversight with dont-clamp-max-velocity
  code/physics/physics.cpp
Labels: bugfix
