Repository scp-fs2open/fs2open.github.com, pull requests merged in 2019-11, with the labels that each got.

#2129 Update Travis to GCC 9 and fix warnings
  .github/workflows/pr-workflow.yaml
  .travis.yml
  code/mission/missionparse.cpp
  code/scripting/lua/LuaFunction.cpp
  code/scripting/lua/LuaFunction.h
  code/scripting/lua/LuaValue.cpp
  code/scripting/lua/LuaValue.h
  code/stats/scoring.h
  code/weapon/weapons.cpp
  qtfred/src/mission/dialogs/MissionGoalsDialogModel.cpp
  qtfred/src/ui/dialogs/EventEditorDialog.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: build

#2127 replace FS2NetD with PXO
  code/ai/ai_profiles.cpp
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
  code/fs2netd/fs2netd_client.cpp
  code/fs2netd/fs2netd_client.h
  code/fs2netd/protocol.h
  code/fs2netd/tcp_client.cpp
  code/fs2netd/tcp_client.h
  code/fs2netd/tcp_socket.cpp
  code/fs2netd/tcp_socket.h
  code/iff_defs/iff_defs.cpp
  code/menuui/mainhallmenu.cpp
  code/menuui/optionsmenumulti.cpp
  code/network/chat_api.h
  code/network/gtrack.cpp
  code/network/gtrack.h
  code/network/multi.cpp
  code/network/multi.h
  code/network/multi_dogfight.cpp
  code/network/multi_endgame.cpp
  code/network/multi_fstracker.cpp
  code/network/multi_fstracker.h
  code/network/multi_options.cpp
  code/network/multi_options.h
  code/network/multi_pxo.cpp
  code/network/multi_sw.cpp
  code/network/multi_sw.h
  code/network/multimsgs.cpp
  code/network/multiui.cpp
  code/network/multiutil.cpp
  code/network/psnet2.h
  code/network/ptrack.cpp
  code/network/ptrack.h
  code/network/stand_gui-unix.cpp
  code/network/stand_gui.cpp
  code/network/valid.cpp
  code/network/valid.h
  code/pilotfile/plr.cpp
  code/scripting/api/libs/base.cpp
  code/scripting/api/libs/testing.cpp
  code/scripting/scripting.cpp
  code/ship/ship.cpp
  code/source_groups.cmake
  code/species_defs/species_defs.cpp
  code/weapon/weapons.cpp
  freespace2/freespace.cpp
Labels: enhancement, multi

#2135 Two subsystem-related fixes
  code/ai/aigoals.cpp
  code/parse/sexp.cpp
Labels: bugfix, cleanup

#1740 Add tool for extracting XSTR calls
  .clang-tidy
  tools/CMakeLists.txt
  tools/strings_tool/CMakeLists.txt
  tools/strings_tool/strings_tool.cpp
Labels: enhancement

#2145 Handle invalid Lua reference correctly
  code/scripting/lua/LuaFunction.cpp
  code/scripting/lua/LuaValue.cpp
  code/scripting/lua/LuaValue.h
Labels: bugfix

#1211 [Feature] Ngon Radar
  code/hud/hudparse.cpp
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/radar/radar.cpp
  code/radar/radar.h
  code/radar/radarngon.cpp
  code/radar/radarngon.h
  code/source_groups.cmake
Labels: cleanup, enhancement, unfinished

#2153 Fix#1992
  code/ship/shipfx.cpp
Labels: bugfix

#2146 Makes slight adjustments to the lighting defaults.
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
  code/graphics/uniforms.cpp
  code/lab/lab.cpp
Labels: cleanup, discussion
