Repository scp-fs2open/fs2open.github.com, pull requests merged in 2019-01, with the labels that each got.

#1967 Avoid using Asserts for data security in modelread properties-reading code.
  code/model/modelread.cpp
Labels: bugfix, cleanup

#1970 fix some bugs with the per_ship_warp_type feature
  code/mission/missionparse.cpp
  code/ship/ship.cpp
Labels: bugfix

#1962 Update internal NanoVG bitmap data buffer when updating texture
  code/graphics/paths/NanoVGRenderer.cpp
Labels: bugfix

#1975 Add support for "Effects per second" feature
  code/particle/ParticleEffect.h
  code/particle/ParticleSource.cpp
  code/particle/ParticleSource.h
  code/particle/ParticleSourceWrapper.h
  code/particle/effects/BeamPiercingEffect.cpp
  code/particle/effects/BeamPiercingEffect.h
  code/particle/effects/CompositeEffect.cpp
  code/particle/effects/CompositeEffect.h
  code/particle/effects/GenericShapeEffect.h
  code/particle/effects/ParticleEmitterEffect.cpp
  code/particle/effects/ParticleEmitterEffect.h
  code/particle/effects/SingleParticleEffect.cpp
  code/particle/effects/SingleParticleEffect.h
  code/particle/util/EffectTiming.cpp
  code/particle/util/EffectTiming.h
  code/utils/RandomRange.h
Labels: enhancement

#1976 Avoid ship name lookup when sending "special" messages.
  code/mission/missionmessage.cpp
Labels: bugfix, mantis

#1977 Swap back return values for lua setButtonControlMode() function.
  code/scripting/api/libs/base.cpp
Labels: bugfix

#1978 Use modulo instead of division in Lua useButtonControl() function.
  code/scripting/api/objs/control_info.cpp
Labels: bugfix

#1979 Add checks for Player being nullptr to l_Control_Info.
  code/scripting/api/objs/control_info.cpp
Labels: bugfix
