Repository scp-fs2open/fs2open.github.com, pull requests merged in 2019-03, with the labels that each got.

#2000 Add natvis file for Lua
  lib/lua/CMakeLists.txt
  lib/lua/lua.natvis
Labels: enhancement

#1991 Fix issues with docked ships warping
  code/object/collideshipship.cpp
  code/object/objectdock.cpp
  code/object/objectdock.h
  code/radar/radarsetup.cpp
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/ship_flags.h
  code/ship/shipfx.cpp
Labels: bugfix

#1999 Unify Cfile blocks and CFILE handles
  code/cfile/cfile.cpp
  code/cfile/cfile.h
  code/cfile/cfilearchive.cpp
  code/cfile/cfilearchive.h
  code/prefix_header.h
Labels: cleanup

#2007 Add new HUD gauge type for scripted gauges
  code/hud/hud.cpp
  code/hud/hud.h
  code/hud/hudparse.cpp
  code/hud/hudparse.h
  code/hud/hudscripting.cpp
  code/hud/hudscripting.h
  code/scripting/ade_args.cpp
  code/scripting/ade_args.h
  code/scripting/api/objs/hudgauge.cpp
  code/scripting/api/objs/hudgauge.h
  code/source_groups.cmake
Labels: enhancement
