Repository scp-fs2open/fs2open.github.com, pull requests merged in 2020-05, with the labels that each got.

#2348 bring save format up to date (Mantis 2867)
  fred2/fred.cpp
  fred2/fredview.cpp
  fred2/fredview.h
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: cleanup, mantis

#2336 add +Hotkey Team: to override IFF designation in hotkey list
  code/iff_defs/iff_defs.cpp
  code/iff_defs/iff_defs.h
  code/mission/missionhotkey.cpp
  code/scripting/api/objs/team.cpp
Labels: cleanup, enhancement, mantis

#2353 clean up the support ship code a bit
  code/ship/ship.cpp
Labels: bugfix, cleanup

#2345 Fix mantis 2791
  code/ai/aicode.cpp
  code/mission/missionparse.cpp
  code/model/model.h
  code/model/modelread.cpp
Labels: bugfix, cleanup, mantis

#2343 implement XSTR check as described in Mantis 2942
  code/localization/localize.cpp
  code/localization/localize.h
  code/menuui/readyroom.cpp
  code/mission/missionparse.cpp
  code/network/multiui.cpp
  test/src/menuui/test_intel_parse.cpp
Labels: mantis

#2342 implement Mantis 1947, treat ship comm systems the same as player comm systems
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aicode.cpp
  code/hud/hudsquadmsg.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtarget.h
  code/mission/missionmessage.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/sound/voicerec.cpp
Labels: bugfix, enhancement, mantis

#2332 add an ai-profiles flag to govern the Mantis 3147 fix
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aicode.cpp
  code/globalincs/version.h
Labels: cleanup, mantis

#2298 Add capability to have a pure lua script
  .clang-tidy
  code/cfile/cfile.cpp
  code/osapi/dialogs.cpp
  code/parse/parselo.cpp
  code/scripting/api/libs/engine.cpp
  code/scripting/api/libs/engine.h
  code/scripting/lua.cpp
  code/scripting/lua/LuaFunction.cpp
  code/scripting/lua/LuaFunction.h
  code/scripting/scripting.cpp
  code/scripting/scripting.h
  code/source_groups.cmake
  fred2/management.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/management.cpp
Labels: enhancement

#2390 clean up handling of translated vs. untranslated English
  code/cutscene/ffmpeg/FFMPEGDecoder.cpp
  code/localization/localize.cpp
  code/localization/localize.h
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/scripting/api/libs/base.cpp
  fred2/management.cpp
  qtfred/src/mission/management.cpp
Labels: cleanup

#2389 make Goal_target_names dynamic
  code/ai/ai.cpp
  code/ai/ai.h
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/mission/missionparse.cpp
Labels: cleanup

#2414 fix corrupted retail save format
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: bugfix

#2413 fix incorrect consolidation
  code/mission/missionparse.cpp
Labels: bugfix

#2399 Fix 'Guard Attack This' Behavior with AI Flag
  code/ai/aicode.cpp
Labels: bugfix

#2404 Fixes gr.drawOffscreenIndicator
  code/scripting/api/libs/graphics.cpp
Labels: bugfix

#2397 Add Lua API for promises and async coroutines
  .clang-format
  code/scripting/ade_args.cpp
  code/scripting/api/LuaCoroutineRunner.cpp
  code/scripting/api/LuaCoroutineRunner.h
  code/scripting/api/LuaPromise.cpp
  code/scripting/api/LuaPromise.h
  code/scripting/api/libs/async.cpp
  code/scripting/api/libs/async.h
  code/scripting/api/objs/promise.cpp
  code/scripting/api/objs/promise.h
  code/scripting/lua.cpp
  code/scripting/lua/LuaFunction.cpp
  code/scripting/lua/LuaFunction.h
  code/scripting/lua/LuaReference.cpp
  code/scripting/lua/LuaReference.h
  code/scripting/lua/LuaTable.cpp
  code/scripting/lua/LuaTable.h
  code/scripting/lua/LuaThread.cpp
  code/scripting/lua/LuaThread.h
  code/scripting/lua/LuaTypes.h
  code/scripting/lua/LuaUtil.cpp
  code/scripting/lua/LuaUtil.h
  code/scripting/lua/LuaValue.cpp
  code/scripting/lua/LuaValue.h
  code/scripting/scripting.h
  code/source_groups.cmake
  test/src/scripting/ade_args.cpp
  test/src/scripting/api/async.cpp
  test/src/scripting/lua/Function.cpp
  test/src/scripting/lua/Reference.cpp
  test/src/scripting/lua/Table.cpp
  test/src/scripting/lua/TestUtil.h
  test/src/scripting/lua/Thread.cpp
  test/src/source_groups.cmake
  test/test_data/scripting/async/promise/callBothResolveReject/data/scripts/test.lua
  test/test_data/scripting/async/promise/callRejectTwice/data/scripts/test.lua
  test/test_data/scripting/async/promise/callResolveTwice/data/scripts/test.lua
  test/test_data/scripting/async/promise/callWithNonFunction/data/scripts/test.lua
  test/test_data/scripting/async/promise/catchErrors/data/scripts/test.lua
  test/test_data/scripting/async/promise/resolveWithValues/data/scripts/test.lua
  test/test_data/scripting/async/promise/thenCatchChains/data/scripts/test.lua
  test/test_data/scripting/async/run/runWithErroredAwait/data/scripts/test.lua
  test/test_data/scripting/async/run/runWithResolvedAwait/data/scripts/test.lua
  test/test_data/scripting/async/run/runWithoutAwait/data/scripts/test.lua
  test/test_data/scripting/data/scripts/assert.lua
Labels: enhancement

#2420 use get_operator_* optimizations
  code/ai/aigoals.cpp
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/fredview.cpp
  fred2/messageeditordlg.cpp
  fred2/voiceactingmanager.cpp
Labels: cleanup

#2424 Fix a crash in the Lab when viewing bombs
  code/globalincs/systemvars.h
  code/lab/lab.cpp
  code/radar/radarsetup.cpp
Labels: bugfix
