Repository scp-fs2open/fs2open.github.com, pull requests merged in 2020-08, with the labels that each got.

#2614 Allow actually editing orientations in the orientation editor
  fred2/fred.rc
  fred2/orienteditor.cpp
  fred2/orienteditor.h
  fred2/resource.h
Labels: cleanup, enhancement

#2617 Fix for #2616
  code/hud/hudlock.cpp
  code/ship/ship.cpp
Labels: bugfix

#2615 add new versions of the collision group sexps
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement

#2619 Fix Missing Check for Primary Linking
  code/ai/aicode.cpp
Labels: bugfix

#2620 increased weapon type limit from 300 to 500, matching ship class limit
  code/globalincs/globals.h
Labels: enhancement

#2621 add the ability to use multiple sexp parameter variants
  code/parse/sexp/LuaSEXP.cpp
  code/parse/sexp/LuaSEXP.h
Labels: enhancement

#2599 Fix Non-Standalone Servers Failing to Switch Between PXO and Non-PXO
  code/network/multi_fstracker.cpp
Labels: bugfix, multi

#2594 Keeps players From Accessing Multi Screens When No Connection Available.
  code/menuui/mainhallmenu.cpp
Labels: bugfix, cleanup, multi

#2604 Supply world coordinates in whack function calls
  code/ai/aicode.cpp
  code/network/multimsgs.cpp
  code/object/collideshipweapon.cpp
  code/object/objectdock.cpp
  code/parse/sexp.cpp
  code/physics/physics.cpp
  code/physics/physics.h
  code/scripting/api/objs/physics_info.cpp
  code/ship/ship.cpp
  code/ship/shiphit.cpp
  code/weapon/beam.cpp
  code/weapon/weapons.cpp
Labels: bugfix, cleanup

#2642 Several small sound-related enhancements
  code/debris/debris.cpp
  code/debris/debris.h
  code/gamesnd/gamesnd.cpp
  code/gamesnd/gamesnd.h
  code/hud/hud.cpp
  code/object/collideshipship.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement

#2637 Enable dllexport for Lua API
  lib/lua/luaconf.h
Labels: cleanup

#2643 Capture Ade skip arguments locally
  code/scripting/ade_args.h
  code/scripting/api/LuaCoroutineRunner.cpp
  code/scripting/scripting.h
Labels: bugfix

#2647 clean up fireball filename init
  code/fireball/fireballs.cpp
Labels: cleanup

#2639 fix crash from multilock merge
  code/ship/ship.cpp
Labels: bugfix

#2644 Add scripting API for custom execution context
  code/executor/CombinedExecutionContext.cpp
  code/executor/CombinedExecutionContext.h
  code/scripting/api/LuaExecutionContext.cpp
  code/scripting/api/LuaExecutionContext.h
  code/scripting/api/libs/async.cpp
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/enums.h
  code/scripting/api/objs/execution_context.cpp
  code/scripting/api/objs/execution_context.h
  code/source_groups.cmake
Labels: enhancement

#2645 Add more scripting APIs for the command briefing
  code/missionui/missionbrief.cpp
  code/missionui/missionbrief.h
  code/missionui/missionscreencommon.cpp
  code/missionui/missionscreencommon.h
  code/scripting/api/libs/async.cpp
  code/scripting/api/libs/base.cpp
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/audio_stream.cpp
  code/scripting/api/objs/player.cpp
  code/scripting/api/objs/player.h
Labels: enhancement

#2649 Debris enhancements
  code/debris/debris.cpp
  code/debris/debris.h
  code/mission/missionparse.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/debris.cpp
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/ship/shiphit.cpp
Labels: enhancement

#2651 add for-ship-class and for-ship-type sexps
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement

#2634 Allow multilock missiles to restrict lock based on class or species
  code/hud/hudlock.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement

#2653 use SCP_string instead of fixed buffer
  code/mission/missionparse.cpp
Labels: bugfix

#2654 add LuaSEXP support for soundentry (OPF_GAME_SND)
  code/parse/sexp/LuaSEXP.cpp
Labels: enhancement

#2655 Fix memory leak in scripting documentation
  code/scripting/doc_json.cpp
Labels: bugfix

#2657 ship-create protecc
  code/parse/sexp.cpp
Labels: bugfix

#2652 Update DDS Utilities to DX10 Standard
  code/bmpman/bm_internal.h
  code/bmpman/bmpman.cpp
  code/bmpman/bmpman.h
  code/ddsutils/ddsutils.cpp
  code/ddsutils/ddsutils.h
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropengltexture.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  lib/opengl/gl/extensions.txt
  lib/opengl/gl/glad/include/glad/glad.h
  lib/opengl/gl/glad/src/glad.c
  lib/opengl/gl/glad_wgl/include/glad/glad_wgl.h
  lib/opengl/gl/glad_wgl/src/glad_wgl.c
Labels: enhancement

#2662 add warning for duplicate dockpoints
  code/model/modelread.cpp
Labels: cleanup

#2666 synchronize localization
  code/localization/localize.cpp
  test/src/menuui/test_intel_parse.cpp
Labels: bugfix

#2612 Patch a Crash Point
  code/network/multi_campaign.cpp
Labels: bugfix, multi

#2663 make Intel stuff dynamic
  code/lab/lab.cpp
  code/menuui/techmenu.cpp
  code/menuui/techmenu.h
  code/parse/sexp.cpp
  code/pilotfile/csg.cpp
  code/pilotfile/csg_convert.cpp
  code/scripting/api/libs/tables.cpp
  code/scripting/api/objs/intelentry.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
  test/src/menuui/test_intel_parse.cpp
Labels: enhancement

#2665 Don't trigger ship_start/stop_secondary_fire assert on empty bank
  code/ship/ship.cpp
Labels: bugfix

#2670 Improve error reporting related to SSM strikes.
  code/hud/hudartillery.cpp
  code/weapon/weapons.cpp
Labels: bugfix, cleanup

#2669 Improve Linux linking performance
  cmake/toolchain-clang.cmake
  cmake/toolchain-gcc.cmake
Labels: build

#2677 temporary hack to increase flexibility of hook variables
  code/scripting/ade.cpp
Labels: cleanup

#2680 Fix usage of float instead of int epsilon
  code/math/vecmat.h
Labels: bugfix

#2684 Some fred enhancements
  fred2/fred.cpp
  fred2/fred.rc
  fred2/fredview.cpp
  fred2/fredview.h
  fred2/initialstatus.cpp
  fred2/resource.h
  qtfred/src/mission/EditorViewport.cpp
  qtfred/src/mission/EditorViewport.h
Labels: enhancement

#2679 miscellaneous scripting and ship-destruction enhancements
  code/debris/debris.cpp
  code/network/multimsgs.cpp
  code/parse/sexp.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/ship.cpp
  code/scripting/api/objs/vecmath.cpp
  code/ship/ship.cpp
  code/ship/shiphit.cpp
  code/ship/shiphit.h
Labels: enhancement

#2682 fix alignments in the hud gauge parsing
  code/hud/hud.cpp
  code/hud/hud.h
  code/hud/hudparse.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtarget.h
Labels: cleanup

#2681 add for-ship-team and for-ship-species sexps
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: enhancement

#2675 add the ability to override main halls with modular tables
  code/menuui/mainhallmenu.cpp
  code/menuui/mainhallmenu.h
Labels: enhancement

#2693 make sound lookup case-insensitive
  code/gamesnd/gamesnd.cpp
Labels: bugfix

#2694 add more debris sounds
  code/debris/debris.cpp
  code/object/collideshipship.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement

#2695 handle Hull_debris_list for dynamic debris
  code/debris/debris.cpp
  code/debris/debris.h
Labels: bugfix

#2585 Add pstypes.h to precompiled header
  cmake/util.cmake
  code/CMakeLists.txt
  code/prefix_header.h
  code/sound/speech.cpp
  code/sound/voicerec.cpp
Labels: build

#2683 Add ShipEditor to QtFred
  qtfred/source_groups.cmake
  qtfred/src/mission/Editor.h
  qtfred/src/mission/EditorWing.cpp
  qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
  qtfred/src/mission/dialogs/ShipEditorDialogModel.h
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
  qtfred/src/ui/dialogs/ShipEditorDialog.cpp
  qtfred/src/ui/dialogs/ShipEditorDialog.h
  qtfred/ui/ShipEditorDialog.ui
Labels: enhancement

#2687 various collision group fixes
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/object.cpp
Labels: enhancement

#2698 Renamed free flight speed related tag and variable for clarity and safety
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: cleanup

#2699 Fix the loadout memory bug
  code/network/multiteamselect.cpp
Labels: bugfix, multi

#2674 refactor display_name for ships, ship classes, and weapon classes
  code/hud/hudbrackets.cpp
  code/hud/hudescort.cpp
  code/hud/hudsquadmsg.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/io/keycontrol.cpp
  code/lab/lab.cpp
  code/menuui/techmenu.cpp
  code/mission/missionhotkey.cpp
  code/mission/missionlog.cpp
  code/mission/missionmessage.cpp
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/missionui/missionbrief.cpp
  code/missionui/missiondebrief.cpp
  code/missionui/missionshipchoice.cpp
  code/missionui/missionweaponchoice.cpp
  code/network/multi_ingame.cpp
  code/network/multi_pmsg.cpp
  code/network/multiteamselect.cpp
  code/playerman/playercontrol.cpp
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/parse_object.cpp
  code/scripting/api/objs/ship.cpp
  code/scripting/api/objs/shipclass.cpp
  code/scripting/api/objs/weaponclass.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shiphit.cpp
  code/stats/medals.cpp
  code/stats/medals.h
  code/stats/scoring.cpp
  code/weapon/emp.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
  fred2/freddoc.cpp
  fred2/voiceactingmanager.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/Editor.cpp
Labels: bugfix, cleanup, enhancement

#2700 add some vector scripting functions
  code/ai/aibig.cpp
  code/hud/hudartillery.cpp
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/nebula/neblightning.cpp
  code/scripting/api/libs/base.cpp
  code/scripting/api/objs/vecmath.cpp
  code/weapon/beam.cpp
  code/weapon/weapons.cpp
Labels: enhancement

#2593 Change MP Initial Player Wing Ship Behavior to Match SP
  code/ai/aigoals.cpp
Labels: bugfix, mantis, multi
