Repository scp-fs2open/fs2open.github.com, pull requests merged in 2020-01, with the labels that each got.

#2218 Cleanup some unused functions in the graphics subsystem
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/graphics/grstub.cpp
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropengl.h
  code/graphics/opengl/gropengldraw.cpp
  code/graphics/opengl/gropengldraw.h
  code/graphics/opengl/gropenglshader.h
  code/graphics/opengl/gropengltexture.h
  code/model/modelrender.cpp
Labels: cleanup

#2222 Fix fog depth computation
  code/def_files/data/effects/fog-f.sdr
Labels: bugfix

#2231 Better Timing For Interpolation Calc
  code/network/multi_obj.cpp
Labels: multi

#2233 Proposal to cleanup debug log statement regarding turret fire
  code/ai/aiturret.cpp
Labels: cleanup

#2234 Replace Warning with error_display in parselo
  code/parse/parselo.cpp
Labels: bugfix

#2236 Adds Scripting Support for the Ship Flag `gun convergence`
  code/scripting/api/objs/ship.cpp
Labels: enhancement

#2196 Mantis#2129 Address Rare Multi Crash
  code/network/multiutil.cpp
Labels: multi

#2242 Add -post_process to deprecated flags section
  code/cmdline/cmdline.cpp
Labels: bugfix

#1600 Add persistent buffer mapping support for uniform data
  cmake/platformChecks.h.in
  code/decals/decals.cpp
  code/globalincs/pstypes.h
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/graphics/decal_draw_list.cpp
  code/graphics/decal_draw_list.h
  code/graphics/grstub.cpp
  code/graphics/matrix.cpp
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropengldeferred.cpp
  code/graphics/opengl/gropengltnl.cpp
  code/graphics/opengl/gropengltnl.h
  code/graphics/paths/NanoVGRenderer.cpp
  code/graphics/paths/NanoVGRenderer.h
  code/graphics/uniforms.cpp
  code/graphics/util/UniformAligner.cpp
  code/graphics/util/UniformAligner.h
  code/graphics/util/UniformBuffer.cpp
  code/graphics/util/UniformBuffer.h
  code/graphics/util/UniformBufferManager.cpp
  code/graphics/util/UniformBufferManager.h
  code/model/modelrender.cpp
  code/model/modelrender.h
  lib/opengl/gl/extensions.txt
  lib/opengl/gl/glad/include/glad/glad.h
  lib/opengl/gl/glad/src/glad.c
  lib/opengl/gl/glad_wgl/include/glad/glad_wgl.h
  lib/opengl/gl/glad_wgl/src/glad_wgl.c
Labels: enhancement

#2243 Allows Modders to Actually Use Engine Wash Intensity
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/ship/shipfx.cpp
Labels: enhancement
