Repository scp-fs2open/fs2open.github.com, pull requests merged in 2020-04, with the labels that each got.

#2334 fix loading of capship custom weapons
  code/mission/missionparse.cpp
Labels: bugfix

#2331 allow intervals and chain delays to use milliseconds
  code/mission/missiongoals.cpp
  code/mission/missiongoals.h
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  fred2/eventeditor.cpp
  fred2/eventeditor.h
  fred2/fred.rc
  fred2/messageeditordlg.cpp
  fred2/missionsave.cpp
  fred2/resource.h
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, mantis

#2322 Add extended scripting hook system
  .clang-format
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/hud/hudmessage.cpp
  code/mission/missionmessage.cpp
  code/scripting/ade.cpp
  code/scripting/ade.h
  code/scripting/hook_api.cpp
  code/scripting/hook_api.h
  code/scripting/scripting.cpp
  code/scripting/scripting.h
  code/ship/shipfx.cpp
  code/source_groups.cmake
  code/utils/tuples.h
  freespace2/freespace.cpp
  test/src/scripting/lua/Util.cpp
Labels: enhancement
