Repository scp-fs2open/fs2open.github.com, pull requests merged in 2020-11, with the labels that each got.

#2861 Fix a bug with collision_radius_override
  code/weapon/weapons.cpp
Labels: bugfix

#2862 Don't perform automatic hash truncation before template-copying.
  code/ship/ship.cpp
Labels: bugfix, regression

#2857 Update libpng to version 1.6.37
  lib/libpng/png.c
  lib/libpng/png.h
  lib/libpng/pngconf.h
  lib/libpng/pngdebug.h
  lib/libpng/pngerror.c
  lib/libpng/pngget.c
  lib/libpng/pnginfo.h
  lib/libpng/pngmem.c
  lib/libpng/pngpread.c
  lib/libpng/pngpriv.h
  lib/libpng/pngread.c
  lib/libpng/pngrio.c
  lib/libpng/pngrtran.c
  lib/libpng/pngrutil.c
  lib/libpng/pngset.c
  lib/libpng/pngstruct.h
  lib/libpng/pngtrans.c
  lib/libpng/pngwio.c
  lib/libpng/pngwrite.c
  lib/libpng/pngwtran.c
  lib/libpng/pngwutil.c
Labels: graphics, library

#2788 Multiplayer Resimulation for Client Fired Linear Weapons (Rollback)
  code/network/multi.cpp
  code/network/multi.h
  code/network/multi_obj.cpp
  code/network/multi_obj.h
  code/network/multimsgs.cpp
  code/network/multimsgs.h
  code/object/collideshipship.cpp
  code/object/collideshipweapon.cpp
  code/object/objcollide.cpp
  code/object/objcollide.h
  code/object/object.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: bugfix, enhancement, multi

#2823 Allow for continuously spawning weapons
  code/parse/parselo.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, gameplay

#2866 Add CYCLE_PRIMARY_WEAPON_SEQUENCE to Multi controls sent to server.
  code/io/keycontrol.cpp
Labels: bugfix, multi

#2858 Add beam parameter validation
  code/ai/aiturret.cpp
  code/hud/hudartillery.cpp
  code/network/multimsgs.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/weapon/beam.cpp
  code/weapon/beam.h
  code/weapon/weapons.cpp
Labels: cleanup, multi

#2874 Add the "Player" hook variable to the CHA_HUDDRAW scripting trigger
  freespace2/freespace.cpp
Labels: enhancement, scripting

#2872 Should fix some crahes and inaccuracies at high pings
  code/network/multi_obj.cpp
Labels: bugfix, multi

#2878 Fix pilot file data loss
  code/pilotfile/plr.cpp
Labels: bugfix

#2871 AI Edge Case Fix
  code/network/multi_obj.cpp
Labels: bugfix, multi

#2876 Fix 'getFrametime' scripting function
  code/scripting/api/libs/base.cpp
Labels: cleanup, scripting

#2759 Fix multi screen timeouts
  code/cutscene/movie.cpp
  code/missionui/fictionviewer.cpp
  code/missionui/missioncmdbrief.cpp
  code/missionui/redalert.cpp
  code/network/multi.h
  code/network/multi_endgame.cpp
  code/network/multimsgs.cpp
  code/network/multiteamselect.cpp
  code/network/multiteamselect.h
  code/network/multiui.cpp
  code/popup/popup.cpp
  code/popup/popupdead.cpp
  freespace2/freespace.cpp
Labels: bugfix, enhancement, multi

#2881 Two fixes to weapon states
  code/weapon/weapons.cpp
Labels: bugfix, graphics

#2883 Add trail 'spread'
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipcontrails.cpp
  code/weapon/corkscrew.cpp
  code/weapon/trails.cpp
  code/weapon/trails.h
  code/weapon/weapons.cpp
Labels: enhancement, graphics

#2880 Add some new afterburner options
  code/ship/afterburner.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/ship_flags.h
Labels: enhancement, gameplay

#2891 don't access invalid memory if the shipnum is -1
  code/mission/missionmessage.cpp
Labels: cleanup

#2888 Fix a bug with model animation
  code/model/modelanim.cpp
Labels: bugfix

#2865 Some visual fixes to local ssms
  code/weapon/corkscrew.cpp
  code/weapon/weapons.cpp
Labels: bugfix, graphics

#2897 Update no-pspew-lssm with recent changes
  code/weapon/weapons.cpp
Labels: bugfix

#2898 Remove the unused shield_integrity field
  code/ship/ship.cpp
  code/ship/ship.h
Labels: cleanup

#2899 Prevent loadout issues in multi due to iff changes
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/network/multiteamselect.cpp
Labels: bugfix, multi

#2904 Fix a bug with shockwave damage parsing
  code/weapon/shockwave.cpp
  code/weapon/shockwave.h
  code/weapon/weapons.cpp
Labels: bugfix, gameplay

#2906 fix some sort of build problem in the continuous integration
  code/ai/aicode.cpp
  code/graphics/post_processing.cpp
  code/weapon/beam.cpp
Labels: build

#2905 adjust weapon calculations based on Discord analysis
  code/weapon/weapons.cpp
Labels: cleanup

#2910 Update host pointer on standalone after host switch
  code/network/multiutil.cpp
Labels: bugfix, multi

#2843 Fix some issues with warp collision
  code/asteroid/asteroid.cpp
  code/debris/debris.cpp
  code/model/modelrender.cpp
  code/object/collideshipship.cpp
  code/object/collideshipweapon.cpp
  code/ship/shipfx.cpp
  code/ship/shipfx.h
  code/weapon/beam.cpp
Labels: bugfix, cleanup, gameplay

#2901 Make Anti-Rubberbanding less aggressive to keep the client from showing nonsense
  code/network/multi_obj.cpp
Labels: bugfix, gameplay, multi

#2902 Add IFF to missile lock restrictions, and now all missiles can use them
  code/ai/aicode.cpp
  code/hud/hudlock.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, gameplay

#2916 Add 'Dont_override_old_maneuvers' flag to maneuvers
  code/ai/ai.h
  code/ai/ai_flags.h
  code/ai/aicode.cpp
  code/parse/sexp.cpp
  code/physics/physics.h
  code/scripting/api/objs/ship.cpp
Labels: enhancement, gameplay, general modding, scripting

#2909 Add ships.tbl flags to tune most aspects of ETS behaviour
  code/hud/hudets.cpp
  code/hud/hudets.h
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement, gameplay

#2911 Only save hotkeys if the player has actually added to the group, otherwise leave mission defaults in place
  code/mission/missionhotkey.cpp
Labels: bugfix, controls

#2927 Reduce docking 'jitter'
  code/ai/aicode.cpp
  code/ship/ship.cpp
Labels: bugfix, physics

#2915 Warn about and correct invalid squadron wings in multi
  code/mission/missionparse.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: bugfix, general modding, multi

#2918 Fix multiplayer stat save
  code/network/multiui.cpp
Labels: bugfix, multi

#2925 Separate ship splitting explosions from propagating explosions
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement, graphics

#2924 Death roll for big ships and a death roll multiplier
  code/ai/aicode.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/ship_flags.h
  code/ship/shiphit.cpp
Labels: enhancement, gameplay

#2933 Cover edge case in particle code
  code/particle/effects/GenericShapeEffect.h
Labels: bugfix

#2929 Expose the power output in the ship class to sexps and scripting
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/scripting/api/objs/shipclass.cpp
Labels: enhancement, scripting

#2934 Remove erroneous call to CDR.
  code/parse/sexp.cpp
Labels: bugfix, sexps

#2903 Slightly alter when a timestamp warning is written to the log.
  code/network/multi_obj.cpp
Labels: cleanup, multi

#2941 Fix a small copy paste error in weapon parsing
  code/weapon/weapons.cpp
Labels: bugfix
