Repository scp-fs2open/fs2open.github.com, pull requests merged in 2020-07, with the labels that each got.

#2519 Add system for adding SEXPs externally
  .clang-format
  code/parse/sexp/DynamicSEXP.h
  code/parse/sexp/EngineSEXP.cpp
  code/parse/sexp/EngineSEXP.h
  code/parse/sexp/LuaSEXP.cpp
  code/parse/sexp/LuaSEXP.h
  code/parse/sexp/SEXPParameterExtractor.cpp
  code/parse/sexp/SEXPParameterExtractor.h
  code/parse/sexp/sexp_lookup.cpp
  code/source_groups.cmake
Labels: enhancement

#2546 fix copy-paste mistake
  code/parse/sexp.cpp
Labels: bugfix

#2542 add clear-debris sexp
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement

#2550 fix Mantis 2181
  code/network/multi_obj.cpp
Labels: bugfix, mantis

#2551 fix Mantis 2871
  code/mission/missionparse.cpp
Labels: bugfix, mantis

#2547 lazily write the flag list to prevent empty flag lists
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: cleanup

#2553 fix XSTR lookup for $Has XSTR:
  code/controlconfig/controlsconfig.cpp
  code/globalincs/pstypes.h
  code/localization/localize.cpp
  code/localization/localize.h
Labels: bugfix

#2557 Fix numeric arguments
  code/parse/sexp.cpp
Labels: bugfix, cleanup

#2559 Debriefing persona enhancements
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/missionui/missiondebrief.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/stats/scoring.cpp
  code/stats/scoring.h
  freespace2/freespace.cpp
Labels: bugfix, cleanup, enhancement

#2561 traitor table addendum
  code/missionui/missiondebrief.cpp
  code/stats/scoring.cpp
  code/stats/scoring.h
Labels: cleanup

#2565 sometimes the FSO code is like Jenga
  code/mission/missionparse.cpp
Labels: bugfix

#2566 fix FRED's verify_and_fix_arguments
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: bugfix

#2564 Prevent cargo containers from recovering from a collision
  code/ai/aicode.cpp
Labels: bugfix

#2569 some UTF-8 improvements
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/pilotfile/JSONFileHandler.cpp
Labels: bugfix, cleanup

#2562 Fix Standalone Crashes
  code/graphics/2d.cpp
Labels: bugfix

#2578 fix show-subtitle
  code/parse/sexp.cpp
Labels: bugfix

#2575 Improve physics_ship_init safety
  code/ship/ship.cpp
Labels: cleanup

#2577 Allow pasting clipboard contents into input boxes
  code/ui/inputbox.cpp
  code/ui/ui.h
Labels: enhancement

#2570 make _quick quicker
  code/math/vecmat.cpp
  code/math/vecmat.h
  test/src/math/test_vecmat.cpp
Labels: cleanup

#2450 Allow Team Leaders to Send Messages
  code/network/multiteamselect.cpp
  code/network/multiteamselect.h
  code/network/multiutil.cpp
  code/object/object.cpp
Labels: bugfix, cleanup, multi

#2411 fix various issues with PXO stats
  code/network/multi_fstracker.cpp
  code/network/multi_pxo.cpp
  code/network/ptrack.cpp
  code/network/ptrack.h
Labels: cleanup, multi

#2584 Move unsetting of Wep Cheat to Gamestate code
  code/hud/hudets.cpp
  code/hud/hudets.h
  code/missionui/missiondebrief.cpp
  code/ship/ship.cpp
  freespace2/freespace.cpp
Labels: bugfix

#2583 add scripting function to create matrix from vectors
  code/globalincs/pstypes.h
  code/math/vecmat.h
  code/scripting/api/libs/base.cpp
Labels: enhancement

#2573 cleanup of tech room, and scripting stuff
  code/hud/hudparse.cpp
  code/menuui/techmenu.cpp
  code/menuui/techmenu.h
  code/parse/sexp.cpp
  code/pilotfile/csg.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/libs/tables.cpp
  code/scripting/api/objs/event.cpp
  code/scripting/api/objs/intelentry.cpp
  code/scripting/api/objs/intelentry.h
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/ship.cpp
  code/scripting/api/objs/shipclass.cpp
  code/scripting/api/objs/shiptype.cpp
  code/scripting/api/objs/species.cpp
  code/scripting/api/objs/team.cpp
  code/scripting/api/objs/weaponclass.cpp
  code/scripting/api/objs/wing.cpp
  code/scripting/scripting.cpp
  code/ship/ship.cpp
  code/source_groups.cmake
  code/weapon/weapons.cpp
Labels: cleanup, enhancement

#2543 fix sexp auto-complete for manually-entered text
  fred2/eventeditor.cpp
  fred2/eventeditor.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: bugfix, cleanup

#2588 Make Vulkan an optional component
  CMakeLists.txt
  code/CMakeLists.txt
  code/graphics/2d.cpp
  code/source_groups.cmake
  lib/CMakeLists.txt
Labels: build

#2587 Additional scripting enhancements
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/scripting/api/libs/base.cpp
  code/scripting/api/objs/controls.cpp
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/sexpvar.cpp
  code/scripting/api/objs/vecmath.cpp
Labels: enhancement

#2592 fix line number counting
  code/parse/parselo.cpp
Labels: bugfix

#2581 add ship-maneuver flags to ship_info
  code/ai/aicode.cpp
  code/playerman/playercontrol.cpp
  code/ship/ship.cpp
  code/ship/ship_flags.h
Labels: enhancement

#2596 fix/sun_renderdoc: Make Solaris a recognized platform for renderdoc.
  code/libs/renderdoc/renderdoc_app.h
Labels: bugfix, build

#2598 adjust special_ship index if a ship exits a wing
  code/ship/ship.cpp
Labels: bugfix

#2597 fix/sun_sun: Use 'bgsun' instead of 'sun'
  code/starfield/starfield.cpp
Labels: bugfix, build

#2595 fix/sun_fionbio: Load filio.h on Sun for FIONBIO
  code/inetfile/chttpget.cpp
Labels: bugfix, build

#2602 add OTF fonts
  code/cfile/cfile.cpp
  code/scpui/rocket_ui.cpp
Labels: enhancement

#2601 Fix usage of ship_recoil_modifier
  code/ship/ship.cpp
Labels: bugfix

#2207 Merge Multilock
  code/hud/hudlock.cpp
  code/hud/hudlock.h
  code/hud/hudtarget.cpp
  code/network/multi.h
  code/object/object.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/ship_flags.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement

#2605 Multilock Patch
  code/network/multi_obj.cpp
  code/network/multi_obj.h
  code/object/object.cpp
  code/playerman/playercontrol.cpp
  code/ship/ship.cpp
  code/weapon/weapons.cpp
Labels: enhancement, multi

#2609 add sanity check to Lua SEXP arguments
  code/parse/sexp/LuaSEXP.cpp
Labels: bugfix

#2600 add several more scripting functions
  code/scripting/api/libs/base.cpp
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/objs/streaminganim.cpp
Labels: cleanup, enhancement

#2610 Add comment about new hooks system to legacy hook list
  code/scripting/scripting.cpp
  code/scripting/scripting.h
Labels: cleanup

#2603 more complete scripting support for debris
  code/debris/debris.cpp
  code/scripting/api/objs/debris.cpp
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
Labels: enhancement
