Repository scp-fs2open/fs2open.github.com, pull requests merged in 2021-04, with the labels that each got.

#3347 Make fireballs default to 1 LOD
  code/fireball/fireballs.cpp
Labels: bugfix, cleanup

#3358 fix main hall sounds/music not getting stopped on multi clients
  freespace2/freespace.cpp
Labels: bugfix, multi

#3353 make double-character consolidation reusable, and reuse it
  code/mission/missionparse.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/parse/sexp.cpp
Labels: bugfix, cleanup

#3357 Only close common_select when we should
  freespace2/freespace.cpp
Labels: bugfix

#3362 Remove unecessary ship_get_subsys in model_rotate_gun
  code/ai/aiturret.cpp
  code/model/model.h
  code/model/modelread.cpp
  code/scripting/api/objs/subsystem.cpp
Labels: cleanup

#3363 Fix event parsing by setting flags to zero before loading.
  code/mission/missionparse.cpp
  code/parse/parselo.cpp
Labels: bugfix

#3369 Properly cull generic debris
  code/debris/debris.cpp
Labels: bugfix

#3372 Allow Fred to Edit and Allow Command briefs in FRED
  fred2/fredview.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: bugfix, multi

#3383 Make Sure Special Shield Hitpoint Max Gets Transferred
  code/parse/sexp.cpp
Labels: bugfix

#3373 Make an invalid variable name throw an error.
  code/parse/sexp.cpp
Labels: bugfix, sexps

#3339 Make sure the Netgame state is set to prevent a crash
  code/network/multi_respawn.cpp
Labels: bugfix, multi

#3389 Explicitly check that the type is a ship.
  code/network/multi_obj.cpp
Labels: multi

#3379 address issues with error handling in chat_api
  code/network/chat_api.cpp
Labels: bugfix, multi

#3394 Keep Fred from freezing
  fred2/fredrender.cpp
Labels: bugfix, fred

#3396 make is-ship-visible default to the first player
  code/parse/sexp.cpp
Labels: multi, sexps

#3402 Fix fov_edge_checks
  code/ai/aiturret.cpp
Labels: ai, bugfix

#3400 Fix APNG Animation Framecounter
  code/graphics/generic.cpp
Labels: bugfix

#3404 Revert "Fix APNG Animation Framecounter"
  code/graphics/generic.cpp
Labels: regression

#3406 Avoid negative lookup when parsing loadouts.
  code/parse/parselo.cpp
Labels: bugfix, regression
