Repository scp-fs2open/fs2open.github.com, pull requests merged in 2021-07, with the labels that each got.

#3538 Be smarter about when we try to run scripting hooks
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aiturret.cpp
  code/asteroid/asteroid.cpp
  code/controlconfig/controlsconfig.cpp
  code/io/key.cpp
  code/io/mouse.cpp
  code/mission/missioncampaign.cpp
  code/mission/missionparse.cpp
  code/missionui/missionscreencommon.cpp
  code/object/collidedebrisship.cpp
  code/object/collidedebrisweapon.cpp
  code/object/collideshipship.cpp
  code/object/collideshipweapon.cpp
  code/object/collideweaponweapon.cpp
  code/object/object.cpp
  code/parse/sexp.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/scripting.cpp
  code/scripting/scripting.h
  code/ship/afterburner.cpp
  code/ship/ship.cpp
  code/ship/shiphit.cpp
  code/weapon/beam.cpp
  code/weapon/weapons.cpp
Labels: enhancement, scripting

#3551 Adjust event flag reseting position
  code/mission/missionparse.cpp
Labels: fix, regression

#3552 Fix a secondary range bug from AI multilock
  code/hud/hudlock.cpp
Labels: fix

#3553 fix campaign loop in certain cases
  code/mission/missioncampaign.cpp
Labels: fix

#3554 FRED turret info
  fred2/fred.cpp
  fred2/fred.rc
  fred2/fredrender.cpp
  fred2/fredview.cpp
  fred2/fredview.h
  fred2/resource.h
  qtfred/src/mission/EditorViewport.h
  qtfred/src/mission/FredRenderer.cpp
Labels: enhancement, fred

#3557 work around MSVC 2015 and 2017 compiler bug
  qtfred/src/mission/dialogs/MissionSpecDialogModel.cpp
  qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
  qtfred/src/ui/QtGraphicsOperations.cpp
  qtfred/src/ui/widgets/ColorComboBox.cpp
  qtfred/src/ui/widgets/renderwidget.cpp
Labels: build, fix, qtfred

#3560 log when missions are skipped due to XSTR mismatch
  code/menuui/readyroom.cpp
  code/network/multiui.cpp
Labels: cleanup

#3559 Training message preservation
  code/mission/missiontraining.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: enhancement

#3556 Add setVolume function for audio_stream objects
  code/scripting/api/objs/audio_stream.cpp
Labels: enhancement, scripting

#3555 Add "num firepoints for burst shots" flag
  code/ai/aiturret.cpp
  code/ship/ship.cpp
  code/weapon/weapon.h
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
Labels: enhancement, gameplay

#3558 Qtfred menu update
  qtfred/src/mission/EditorViewport.h
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
  qtfred/ui/FredView.ui
Labels: cleanup, enhancement, qtfred

#3561 Minor improvement for generic debris on subsystems
  code/ship/shipfx.cpp
Labels: enhancement, general modding

#3565 fix briefing icons changing to ships unexpectedly
  code/mission/missionbriefcommon.cpp
  code/missionui/missionbrief.cpp
Labels: fix

#3441 Add support for ballistic beams
  code/ship/ship.cpp
  code/weapon/beam.cpp
Labels: feature, gameplay

#3566 Remove extra AI Profiles call
  fred2/management.cpp
  qtfred/src/mission/Editor.cpp
Labels: cleanup

#3567 Fix a nullptr bug with change_ship_type
  code/ship/ship.cpp
Labels: fix

#3500 Animation Overhaul: Phase 1
  code/lab/manager/lab_manager.h
  code/lab/renderer/lab_renderer.cpp
  code/model/modelanim.cpp
  code/model/modelanimation.cpp
  code/model/modelanimation.h
  code/model/modelanimation_segments.cpp
  code/model/modelanimation_segments.h
  code/model/modelread.cpp
  code/object/object.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/source_groups.cmake
  freespace2/freespace.cpp
Labels: cleanup, enhancement, models, refactor

#3570 fix WEAPON_LIST_TYPE parsing for -1
  code/parse/parselo.cpp
Labels: fix

#3562 Force portable if unicode
  code/osapi/osapi.cpp
Labels: fix, sanitizer/stability

#3574 fix Time To: Unknown on the HUD
  code/ship/ship.cpp
Labels: fix, regression

#3576 allow custom briefing icons to always override standard icons
  code/mission/missionbriefcommon.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: fix

#3568 Move some flag setting to subsys_set()
  code/mission/missionparse.cpp
  code/ship/ship.cpp
Labels: fix
