Repository scp-fs2open/fs2open.github.com, pull requests merged in 2021-03, with the labels that each got.

#3259 Added flag to select the warp effect type of LSSM's
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, general modding

#3257 Add flag for beams to track uoffset individually
  code/weapon/beam.cpp
  code/weapon/beam.h
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
Labels: enhancement, graphics

#3262 allow two SEXPs to be used in multiplayer that previously couldn't be
  code/parse/sexp.cpp
  code/scripting/api/objs/ship.cpp
Labels: enhancement, multi, scripting, sexps

#3275 addendum to u_offset
  code/weapon/beam.cpp
Labels: cleanup

#3178 Generic debris expansion and configuration
  code/debris/debris.cpp
  code/debris/debris.h
  code/model/model.h
  code/model/modelinterp.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipfx.cpp
  code/ship/shiphit.cpp
Labels: enhancement, graphics

#3261 Lua add campaign switch function
  code/scripting/api/objs/player.cpp
Labels: enhancement, scripting

#3243 Decouple asteroids from species
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
  code/hud/hudtargetbox.cpp
  code/mission/missionparse.cpp
  fred2/asteroideditordlg.cpp
  fred2/management.cpp
Labels: cleanup, general modding

#3277 Turrets on movable submodels
  code/ai/aiturret.cpp
  code/model/model.h
  code/model/model_flags.h
  code/model/modelread.cpp
  code/scripting/api/objs/subsystem.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/beam.cpp
Labels: enhancement, feature

#3264 Increase max nebula poofs to 32
  code/nebula/neb.cpp
  code/nebula/neb.h
  freespace2/freespace.cpp
Labels: enhancement, general modding, graphics

#3276 add small fix from SEXP containers PR
  code/parse/sexp.cpp
Labels: bugfix

#3281 a few turret fixes
  code/ai/aiturret.cpp
  code/asteroid/asteroid.cpp
  code/scripting/api/objs/subsystem.cpp
  code/ship/ship.h
Labels: bugfix

#3283 fix character type for isdigit
  code/asteroid/asteroid.cpp
Labels: bugfix

#2923 Controls3 - Primary/Secondary Bindings
  code/controlconfig/controlsconfig.cpp
  code/controlconfig/controlsconfig.h
  code/controlconfig/controlsconfigcommon.cpp
  code/gamehelp/gameplayhelp.cpp
  code/pilotfile/csg.cpp
  code/pilotfile/plr.cpp
  code/pilotfile/plr_convert.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: cleanup, controls, enhancement, refactor, ui

#3269 Various annotation fixes
  code/mission/missionparse.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
  fred2/eventeditor.cpp
Labels: bugfix, cleanup

#3271 rewrite stuffing of lists
  code/asteroid/asteroid.cpp
  code/hud/hudparse.cpp
  code/iff_defs/iff_defs.cpp
  code/mission/missioncampaign.cpp
  code/mission/missionparse.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/ship/ship.cpp
  code/weapon/weapons.cpp
Labels: bugfix, cleanup

#3286 Fix for nebula fogging distance
  code/def_files/data/effects/fog-f.sdr
Labels: bugfix, graphics

#3287 Properly initialize trail alpha exponents for afterburner trails
  code/ship/ship.cpp
Labels: bugfix, graphics

#3285 Bugfix for FIT with set-object-facing
  code/ai/aicode.cpp
  code/physics/physics.cpp
Labels: ai, bugfix, physics

#3274 Add shooter damaging weapons
  code/object/objcollide.cpp
  code/object/object_flags.h
  code/playerman/player.h
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
Labels: enhancement, gameplay

#3291 Peoperly initialize alpha decay exponent for contrails
  code/ship/ship.cpp
Labels: bugfix

#3293 simple hotkey range check
  fred2/shipeditordlg.cpp
Labels: bugfix

#3297 Fix ammo safety regressions.
  code/parse/sexp.cpp
Labels: bugfix, regression

#2885 Expose ability to be targeted by 'huge' and 'small only' weapons
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/def_files/data/tables/objecttypes.tbl
  code/ship/ship.cpp
  code/ship/ship_flags.h
  code/weapon/weapons.cpp
Labels: enhancement, gameplay, general modding

#3300 Fix assert with combining flak and non-flak using substitute
  code/ai/aiturret.cpp
  code/network/multimsgs.cpp
  code/ship/ship.cpp
  code/weapon/flak.cpp
Labels: bugfix

#3224 Remove the fireball limit
  code/fireball/fireballs.cpp
  code/fireball/fireballs.h
  code/object/object.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/fireball.cpp
Labels: cleanup, enhancement

#3164 Limit instances of Client Collisions to Avoid Instant Death
  code/network/multi.cpp
  code/network/multi.h
  code/network/multi_obj.cpp
  code/network/multi_obj.h
  code/network/multi_observer.cpp
  code/network/multiui.cpp
  code/network/multiutil.cpp
  code/object/collideshipship.cpp
Labels: bugfix, multi

#3305 Adding "Start missions in Chase View by default" flag in game_settings.tbl
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/playerman/playercontrol.cpp
Labels: enhancement, gameplay

#3284 Fix probability distribution of vm_vec_random_in_circle/sphere
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/scripting/api/objs/vecmath.cpp
  code/weapon/beam.cpp
  code/weapon/trails.cpp
Labels: bugfix

#2900 Play directive completion sounds for clients
  code/mission/missiongoals.cpp
  code/mission/missiongoals.h
  code/mission/missiontraining.cpp
  code/network/multimsgs.cpp
Labels: enhancement, multi

#3312 add mission flag for starting missions in chase view
  code/mission/mission_flags.h
  code/playerman/playercontrol.cpp
  fred2/fred.rc
  fred2/missionnotesdlg.cpp
  fred2/missionnotesdlg.h
  fred2/resource.h
  qtfred/src/ui/dialogs/MissionSpecDialog.cpp
  qtfred/ui/MissionSpecDialog.ui
Labels: enhancement, gameplay

#3278 Switch to exponential fog and other nebula visibility improvements
  code/def_files/data/effects/fog-f.sdr
  code/fireball/fireballs.cpp
  code/fireball/warpineffect.cpp
  code/graphics/opengl/gropengldeferred.cpp
  code/graphics/util/uniform_structs.h
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/model/modelrender.cpp
  code/nebula/neb.cpp
  code/nebula/neb.h
  code/object/objectsort.cpp
  code/particle/particle.cpp
  code/ship/shield.cpp
  code/ship/ship.cpp
  code/weapon/beam.cpp
  code/weapon/shockwave.cpp
  code/weapon/trails.cpp
  code/weapon/weapons.cpp
Labels: enhancement, graphics

#3314 Make sure objects and ships get cleared if leaving mission sync
  freespace2/freespace.cpp
Labels: bugfix, multi

#3320 Add `no impact debris` for whole ship
  code/ship/ship.cpp
  code/ship/ship_flags.h
  code/ship/shiphit.cpp
Labels: enhancement

#2691 SLC2, BSP alignment and POF version 2118 support
  code/model/model.h
  code/model/modelcollide.cpp
  code/model/modelread.cpp
  code/model/modelsinc.h
Labels: bugfix

#3324 Fix #3322
  code/controlconfig/controlsconfig.cpp
Labels: bugfix, controls

#3319 Allow for setting of nebula fog color explicitly
  code/lab/renderer/lab_renderer.cpp
  code/mission/missionparse.cpp
  code/nebula/neb.cpp
  code/nebula/neb.h
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, graphics, sexps

#3331 Check for these states
  freespace2/freespace.cpp
Labels: multi

#3335 change reticle log statements to warnings
  code/hud/hudreticle.cpp
Labels: bugfix, cleanup

#3310 Fix Fov_edge_checks
  code/ai/aiturret.cpp
  code/ship/ship.h
Labels: bugfix, cleanup

#3266 Make nebula poof detail settings partially dynamic
  code/io/keycontrol.cpp
  code/nebula/neb.cpp
  code/nebula/neb.h
Labels: enhancement

#3337 Fix a rare but eventual crash in the interpolation code.
  code/network/multi_obj.cpp
Labels: multi

#3333 log missing XSTR strings only once
  code/localization/localize.cpp
Labels: cleanup

#3309 Update Turret_alt_math for moving subsystems
  code/ai/aiturret.cpp
  code/model/model.h
  code/model/model_flags.h
  code/model/modelread.cpp
  code/scripting/api/objs/subsystem.cpp
  code/ship/ship.cpp
  code/weapon/beam.cpp
Labels: bugfix, cleanup

#3329 Split frame profile trace into two onscreen columns if needed
  freespace2/freespace.cpp
Labels: cleanup

#3345 My kingdom for a semicolon!
  code/ai/aibig.cpp
Labels: ai, bugfix

#3342 modify saving of edited messages
  fred2/eventeditor.cpp
  fred2/eventeditor.h
Labels: bugfix, fred

#3340 make num-valid-arguments work for the for-* sexps
  code/parse/sexp.cpp
Labels: bugfix

#3346 Add a safety check to the $On Frame: Hook
  code/graphics/2d.cpp
Labels: bugfix, scripting

#3344 Fix regression with huge/small only targeting
  code/ship/ship.cpp
Labels: bugfix, gameplay
