Repository scp-fs2open/fs2open.github.com, pull requests merged in 2021-02, with the labels that each got.

#3190 mission save bugfix
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: bugfix, fred

#3176 Angle-based damage multiplier
  code/object/collideshipweapon.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: feature, gameplay

#2591 Add homing primaries
  code/weapon/weapons.cpp
Labels: enhancement, gameplay

#3179 Don't search for empty sound names
  code/gamesnd/gamesnd.cpp
Labels: bugfix, sound

#3193 Remove the Unused Just_updated Flag
  code/object/object.cpp
  code/object/object_flags.h
Labels: cleanup, multi

#3175 Non-linear Trail decay and Texture stretch
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/trails.cpp
  code/weapon/trails.h
  code/weapon/weapons.cpp
Labels: enhancement, graphics

#3196 Make sure to pull from the bounds of the vector.
  code/network/stand_gui.cpp
Labels: bugfix, multi

#3199 add useful function
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/scripting/api/objs/vecmath.cpp
Labels: enhancement, scripting

#3200 Fix Bug with Reading Turret Rotation Axes
  code/model/modelread.cpp
Labels: bugfix, models

#3201 Unhide chocolate
  .github/CODEOWNERS
  code/controlconfig/controlsconfigcommon.cpp
Labels: controls, not a bug

#3144 reimplement look_at
  code/model/model.h
  code/model/modelread.cpp
Labels: bugfix, cleanup, enhancement, mantis, models

#3203 Actually fix radar range turning to -1 after hud gauge config
  code/hud/hudconfig.cpp
Labels: bugfix, ui

#3192 Add turret-set-forced-target SEXP
  code/ai/aiturret.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/ship/ship_flags.h
  fred2/sexp_tree.cpp
Labels: feature, sexps

#3191 Additional FRED features
  code/mission/missiongoals.h
  code/mission/missionparse.cpp
  fred2/eventeditor.cpp
  fred2/eventeditor.h
  fred2/fred.rc
  fred2/freddoc.cpp
  fred2/freddoc.h
  fred2/missionsave.cpp
  fred2/resource.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, fred

#3198 Add 'landmark' logging
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  code/scripting/api/libs/mission.cpp
  code/ship/ship.cpp
Labels: enhancement

#3205 If the first #ControlConfigOverride isn't named, use "default".
  code/controlconfig/controlsconfigcommon.cpp
Labels: bugfix, regression

#3206 restore retail behavior of XSTR
  code/cutscene/ffmpeg/FFMPEGDecoder.cpp
  code/localization/localize.cpp
  code/localization/localize.h
  code/scripting/api/libs/base.cpp
Labels: bugfix, localization, regression

#3180 Split beam width for collision purposes and lighting purposes
  code/weapon/beam.cpp
  code/weapon/beam.h
Labels: enhancement, gameplay

#3207 Fix for waypoint completion with FIT
  code/ai/aicode.cpp
Labels: ai, bugfix

#3217 fix event node deletion behavior
  fred2/sexp_tree.cpp
Labels: bugfix, fred, regression

#3214 fix event editor closing on key press
  fred2/eventeditor.cpp
  fred2/eventeditor.h
Labels: bugfix, fred, regression

#3213 add send-message-chain
  code/mission/missionmessage.cpp
  code/mission/missionmessage.h
  code/network/multimsgs.cpp
  code/network/multimsgs.h
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/sexp_tree.cpp
  fred2/voiceactingmanager.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: enhancement, sexps

#3219 add model instance support to FRED rendering
  fred2/fredrender.cpp
  fred2/management.cpp
Labels: bugfix, fred, models

#3222 add clarification
  code/parse/sexp.cpp
Labels: cleanup, sexps

#3223 make the ship lookup case insensitive
  code/globalincs/vmallocator.h
  code/ship/ship.cpp
  code/ship/ship.h
Labels: bugfix, enhancement

#3226 additional case functions and checks
  code/cfile/cfile.cpp
  code/cutscene/ffmpeg/FFMPEGDecoder.cpp
  code/globalincs/systemvars.cpp
  code/globalincs/vmallocator.h
  code/hud/hudwingmanstatus.cpp
  code/io/joy-sdl.cpp
  code/menuui/readyroom.cpp
  code/mission/missioncampaign.cpp
  code/mission/missionload.cpp
  code/mod_table/mod_table.cpp
  code/model/modelread.cpp
  code/network/multi_data.cpp
  code/network/multiutil.cpp
  code/parse/parselo.cpp
  code/parse/sexp/LuaSEXP.cpp
  code/scripting/lua.cpp
  code/utils/strings.h
  fred2/voiceactingmanager.cpp
  tools/embedfile/embedfile.cpp
Labels: cleanup

#3231 fix mn.evaluateNumericSEXP
  code/parse/sexp.cpp
Labels: bugfix

#3233 Store standalone image on GitHub
  .github/workflows/standalone-image-workflow.yaml
Labels: build

#3234 add SimHitpointsLeft
  code/scripting/api/objs/object.cpp
Labels: enhancement

#3204 Overhaul briefing icon parsing
  code/mission/missionbriefcommon.cpp
  code/mission/missionbriefcommon.h
  code/species_defs/species_defs.cpp
  code/species_defs/species_defs.h
  fred2/management.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/management.cpp
Labels: cleanup, general modding, interface, refactor

#3220 Add turret-set-inaccuracy SEXP
  code/ai/aiturret.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/scripting/api/objs/subsystem.cpp
  code/ship/ship.h
Labels: feature, sexps

#3237 Bugfix to turret_inaccuracy
  code/ai/aiturret.cpp
  code/ship/ship.cpp
Labels: bugfix

#3239 Update Linux build image and make consistent
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/build-test.yaml
  .github/workflows/pr-workflow.yaml
Labels: build

#3061 Add dynamic action programming system
  ci/linux/configure_cmake.sh
  code/actions/Action.cpp
  code/actions/Action.h
  code/actions/Program.cpp
  code/actions/Program.h
  code/actions/common.h
  code/actions/types/MoveToSubmodel.cpp
  code/actions/types/MoveToSubmodel.h
  code/actions/types/ParticleEffectAction.cpp
  code/actions/types/ParticleEffectAction.h
  code/actions/types/PlaySoundAction.cpp
  code/actions/types/PlaySoundAction.h
  code/actions/types/SetDirectionAction.cpp
  code/actions/types/SetDirectionAction.h
  code/actions/types/SetPositionAction.cpp
  code/actions/types/SetPositionAction.h
  code/actions/types/WaitAction.cpp
  code/actions/types/WaitAction.h
  code/gamesnd/gamesnd.cpp
  code/gamesnd/gamesnd.h
  code/model/model.h
  code/model/modelread.cpp
  code/particle/ParticleSource.cpp
  code/particle/ParticleSource.h
  code/particle/ParticleSourceWrapper.cpp
  code/particle/ParticleSourceWrapper.h
  code/ship/ship.cpp
  code/source_groups.cmake
  code/tracing/Monitor.cpp
  code/tracing/Monitor.h
  code/tracing/categories.cpp
  code/tracing/categories.h
  code/utils/id.h
  code/weapon/beam.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
  lib/vulkan.cmake
Labels: enhancement

#3167 Cylinder only tube lights
  code/def_files/data/effects/deferred-f.sdr
  code/graphics/opengl/gropengldeferred.cpp
Labels: enhancement, graphics

#2744 More cleanup and Int3() refactors
  code/ai/ai.h
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/weapon/emp.cpp
Labels: cleanup

#3248 Force aqt to a known good version
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/build-test.yaml
  .github/workflows/pr-workflow.yaml
Labels: bugfix, build

#3246 add missing #include
  code/globalincs/vmallocator.h
Labels: build

#3067 Add full type coverage for return types and variables
  code/scripting/ade.cpp
  code/scripting/ade.h
  code/scripting/ade_api.h
  code/scripting/ade_doc.cpp
  code/scripting/ade_doc.h
  code/scripting/api/libs/async.cpp
  code/scripting/api/libs/base.cpp
  code/scripting/api/libs/cfile.cpp
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/libs/hud.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/libs/options.cpp
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/LuaSEXP.cpp
  code/scripting/api/objs/cockpit_display.cpp
  code/scripting/api/objs/control_info.cpp
  code/scripting/api/objs/file.cpp
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/option.cpp
  code/scripting/api/objs/parse_object.cpp
  code/scripting/api/objs/promise.cpp
  code/scripting/api/objs/shipclass.cpp
  code/scripting/api/objs/sound.cpp
  code/scripting/api/objs/streaminganim.cpp
  code/scripting/api/objs/subsystem.cpp
  code/scripting/api/objs/team.cpp
  code/scripting/api/objs/vecmath.cpp
  code/scripting/doc_html.cpp
  code/scripting/doc_json.cpp
  code/scripting/doc_parser.cpp
  code/scripting/doc_parser.h
  code/scripting/scripting_doc.h
  parsers/arg_parser/ArgumentList.g4
  parsers/arg_parser/generated/ArgumentList.interp
  parsers/arg_parser/generated/ArgumentList.tokens
  parsers/arg_parser/generated/ArgumentListBaseVisitor.h
  parsers/arg_parser/generated/ArgumentListLexer.cpp
  parsers/arg_parser/generated/ArgumentListLexer.h
  parsers/arg_parser/generated/ArgumentListLexer.interp
  parsers/arg_parser/generated/ArgumentListLexer.tokens
  parsers/arg_parser/generated/ArgumentListParser.cpp
  parsers/arg_parser/generated/ArgumentListParser.h
  parsers/arg_parser/generated/ArgumentListVisitor.h
  test/src/scripting/doc_parser.cpp
Labels: enhancement, scripting

#3252 when we're finished parsing a main hall, the next main hall should be a new one
  code/menuui/mainhallmenu.cpp
Labels: bugfix

#3245 Bugfix for disabled fighters interupting their own support calls
  code/ai/aicode.cpp
Labels: ai, bugfix

#3187 Give swarm missile handling a well-deserved makeover
  code/math/floating.cpp
  code/math/floating.h
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/swarm.cpp
  code/weapon/swarm.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: cleanup, gameplay

#3251 Add a CMake platform check for proper non-copyable type support
  code/actions/ActionDefinitionManager.cpp
  code/actions/ActionDefinitionManager.h
  code/actions/expression/FunctionManager.cpp
Labels: bugfix

#3255 Properly initialize trail texture stretch
  code/ship/ship.cpp
  code/weapon/weapons.cpp
Labels: bugfix, graphics

#3244 Set default volume on audiostream creation
  code/scripting/api/objs/audio_stream.cpp
  code/sound/audiostr.cpp
Labels: bugfix, scripting, sound

#3256 add switch and functional-switch operators
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/messageeditordlg.cpp
Labels: feature, sexps
