Repository scp-fs2open/fs2open.github.com, pull requests merged in 2021-08, with the labels that each got.

#3507 Overhaul nebula poof system
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/nebula/neb.cpp
  code/nebula/neb.h
  code/nebula/neblightning.cpp
  code/parse/sexp.cpp
  code/starfield/starfield.cpp
  code/tracing/categories.cpp
  code/tracing/categories.h
  fred2/bgbitmapdlg.cpp
  fred2/dumpstats.cpp
  fred2/management.cpp
  fred2/sexp_tree.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: enhancement, graphics, refactor

#3564 add Draw Outlines on Selected Ships option
  fred2/fred.cpp
  fred2/fred.rc
  fred2/fredrender.cpp
  fred2/fredrender.h
  fred2/fredview.cpp
  fred2/fredview.h
  fred2/resource.h
  qtfred/src/mission/EditorViewport.h
  qtfred/src/mission/FredRenderer.cpp
  qtfred/src/ui/FredView.cpp
  qtfred/ui/FredView.ui
Labels: enhancement, fred, qtfred

#3586 ships, wings, etc. can share names with teams
  fred2/createwingdlg.cpp
  fred2/shipeditordlg.cpp
  fred2/waypointpathdlg.cpp
  fred2/wing_editor.cpp
  qtfred/src/mission/dialogs/FormWingDialogModel.cpp
  qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
  qtfred/src/mission/dialogs/WaypointEditorDialogModel.cpp
Labels: fix, fred

#3585 handle nebula poofs dynamically in FRED
  fred2/bgbitmapdlg.cpp
  fred2/bgbitmapdlg.h
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: cleanup, enhancement, fred

#3571 Add some chase view Improvements
  code/physics/physics.cpp
  code/physics/physics.h
  code/ship/ship.cpp
  code/ship/ship.h
  freespace2/freespace.cpp
Labels: enhancement, gameplay

#3592 Handle turret fired type 5 beams without targets properly
  code/weapon/beam.cpp
Labels: fix, gameplay

#3481 Fix APNG misc mainhall animations.
  code/graphics/generic.cpp
  code/graphics/generic.h
  code/menuui/mainhallmenu.cpp
Labels: fix

#3593 add a version guard for MSVC compiler bug fix
  qtfred/src/mission/dialogs/MissionSpecDialogModel.cpp
  qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
  qtfred/src/ui/QtGraphicsOperations.cpp
  qtfred/src/ui/widgets/ColorComboBox.cpp
  qtfred/src/ui/widgets/renderwidget.cpp
Labels: cleanup, qtfred, build

#3594 Animation Rework Phase 1 Fixes 4 / Performance Issues
  code/model/modelanimation.cpp
  code/model/modelanimation.h
  code/object/object.cpp
Labels: fix

#3596 fix icon on FS1 mission import
  code/mission/missionparse.cpp
Labels: fix, general modding, fred

#3597 Fix for 'anemic' poofs
  code/globalincs/systemvars.cpp
  code/menuui/optionsmenu.cpp
  code/nebula/neb.cpp
  code/nebula/neb.h
  code/render/3ddraw.cpp
Labels: fix, graphics

#3595 improve logging of ship creation and cleanup
  code/mission/missionlog.cpp
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  code/scripting/api/libs/mission.cpp
  code/ship/ship.cpp
Labels: cleanup

#3599 Fix collision retiming to never be in the future
  code/object/objcollide.cpp
  code/object/objcollide.h
Labels: fix, physics

#3604 Some fixes to shockwave rotation
  code/weapon/shockwave.cpp
  code/weapon/weapons.cpp
Labels: fix, graphics

#3605 Add some more missile target restriction checking
  code/ai/aibig.cpp
  code/ai/aiturret.cpp
Labels: fix, gameplay, ai

#3610 some ai_profiles fixes
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aicode.cpp
Labels: fix, ai

#3617 Fixes a typo in controlconfig that causes an issue with std::move.
  code/controlconfig/controlsconfig.cpp
Labels: fix, controls

#3616 fixes to look_at and intrinsic rotation
  code/model/modelread.cpp
Labels: fix

#3620 No chase cam 'slewing' during hyperspace
  freespace2/freespace.cpp
Labels: fix

#3618 Single target multilock missiles should use `targeted_subsys`
  code/ai/aicode.cpp
Labels: fix, ai
