Repository scp-fs2open/fs2open.github.com, pull requests merged in 2021-10, with the labels that each got.

#3679 patch up scripted kills
  code/network/multimsgs.cpp
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
  code/ship/shiphit.cpp
  code/ship/shiphit.h
Labels: fix, scripting

#3670 Clean up beam type naming scheme
  code/hud/hudartillery.cpp
  code/ship/ship.cpp
  code/weapon/beam.cpp
  code/weapon/beam.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: cleanup, general modding

#3684 add OnShipDeathStarted scripting hook
  code/mission/missionparse.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shiphit.cpp
Labels: scripting, feature

#3589 Add ammoless secondaries
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/hud/hud.cpp
  code/hud/hudtarget.cpp
  code/io/keycontrol.cpp
  code/mission/missionparse.cpp
  code/missionui/missionweaponchoice.cpp
  code/object/object.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/swarm.cpp
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
Labels: enhancement, gameplay

#3623 Allow Lua Scripts to draw rotated rectangles
  code/graphics/render.cpp
  code/graphics/render.h
  code/scripting/api/libs/graphics.cpp
Labels: enhancement, graphics, scripting

#3614 Exclude dead subsys from targeting
  code/hud/hudlock.cpp
  code/ship/ship.cpp
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
Labels: fix

#3688 Fix issue 3685
  code/hud/hudtarget.cpp
  code/hud/hudtarget.h
Labels: fix, HUD, Point Release Candidate

#3694 Safety for replace-texture
  code/ship/ship.cpp
Labels: fix

#3665 Actually fix the goal's target being sent
  code/network/multi_obj.cpp
Labels: fix, multi, Point Release Candidate

#3695 Initialize team visibility before using it
  code/ai/aigoals.cpp
Labels: fix, Point Release Candidate

#3696 Fix a possible crash with `ship_secondary_bank_has_ammo`
  code/ship/ship.cpp
Labels: fix

#3683 Fix warnings concerning ballistic weapons
  code/ship/ship.cpp
Labels: cleanup, general modding

#3609 Animation Overhaul: Phase 2
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/lab/dialogs/actions.cpp
  code/lab/dialogs/actions.h
  code/model/model.h
  code/model/modelanim.cpp
  code/model/modelanim.h
  code/model/modelanimation.cpp
  code/model/modelanimation.h
  code/model/modelanimation_segments.cpp
  code/model/modelanimation_segments.h
  code/model/modelread.cpp
  code/network/multi.cpp
  code/network/multi.h
  code/network/multimsgs.cpp
  code/network/multimsgs.h
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/parse/sexp.cpp
  code/scripting/api/objs/ship.cpp
  code/ship/afterburner.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/source_groups.cmake
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: enhancement, cleanup, fix, multi, refactor, models

#3750 better syntax checking for the special argument
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: fix, sexps

#3755 add script-eval-bool
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, sexps

#3741 fix: cmdbrief not saving current stage text by closing the window
  fred2/cmdbrief.cpp
Labels: fred, Point Release Candidate
