Repository scp-fs2open/fs2open.github.com, pull requests merged in 2021-06, with the labels that each got.

#3450 Minor beam sound fix
  code/weapon/beam.cpp
Labels: bugfix, sound

#3446 Add volume effects
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/particle/ParticleEffect.h
  code/particle/ParticleManager.cpp
  code/particle/effects/VolumeEffect.cpp
  code/particle/effects/VolumeEffect.h
  code/source_groups.cmake
Labels: enhancement, graphics, particles

#3460 Fix heatseeker max homing limit for non-players
  code/weapon/weapons.cpp
Labels: bugfix

#3464 Validate user-provided values passed to Random::next()
  code/parse/sexp.cpp
  code/scripting/api/libs/base.cpp
Labels: bugfix, scripting, sexps

#3467 Fix Ai_aims_from_center flag
  code/ai/aicode.cpp
Labels: ai, bugfix

#3455 Remove glowpoint 'depth'
  code/model/modelrender.cpp
Labels: graphics

#3465 Fix calling split_str() with a maximum line length of 0.
  code/missionui/missionshipchoice.cpp
  code/parse/parselo.cpp
Labels: bugfix, regression

#3461 Add random homing target acquisition
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, gameplay

#3472 deprecate script-eval
  code/parse/sexp.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: cleanup

#3475 Remove superfluous warning about missing "child" flag.
  code/weapon/weapons.cpp
Labels: bugfix

#3466 Add "no collide" for weapons
  code/weapon/beam.cpp
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
Labels: enhancement, gameplay

#3060 Range aware secondary selection
  code/ai/ai_profiles.cpp
  code/ai/ai_profiles.h
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, gameplay

#3478 fix bug in subsystem_stricmp
  code/parse/parselo.cpp
Labels: bugfix

#3477 Fix collision culling for accelerating weapons... again
  code/object/objcollide.cpp
Labels: bugfix, physics

#3473 A few small fixes to SEXP container definition
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: bugfix, cleanup, fred, gameplay, qtfred

#3301 Implement substitution for beams
  code/weapon/beam.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: Waiting for Stable, enhancement, gameplay

#3479 Improve particle alpha handling for small particles
  code/particle/particle.cpp
Labels: enhancement, graphics

#3468 Fix a bug with applyWhack scripting function
  code/scripting/api/objs/physics_info.cpp
Labels: bugfix, scripting

#3480 Add No_shield_damage_from_ship_collisions flag
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/object/collidedebrisship.cpp
  code/object/collideshipship.cpp
Labels: enhancement, gameplay

#3476 add scripting functions to control sounds assigned to objects
  code/debris/debris.cpp
  code/object/objectsnd.cpp
  code/object/objectsnd.h
  code/parse/sexp.cpp
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/object.cpp
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/ship/shiphit.cpp
  code/weapon/weapons.cpp
Labels: feature, scripting

#2817 Add Type 5 beams
  code/ai/aiturret.cpp
  code/hud/hudartillery.cpp
  code/network/multimsgs.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/beam.cpp
  code/weapon/beam.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, feature, gameplay

#3486 small followup fix for #3476
  code/scripting/api/objs/object.cpp
Labels: bugfix

#3483 Improve damage type handling when dealing damage
  code/ai/aicode.cpp
  code/asteroid/asteroid.cpp
  code/io/keycontrol.cpp
  code/object/collidedebrisship.cpp
  code/object/collideshipship.cpp
  code/object/collideshipweapon.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/ship/shiphit.cpp
  code/ship/shiphit.h
  code/weapon/beam.cpp
  code/weapon/shockwave.cpp
  code/weapon/weapons.cpp
Labels: bugfix, cleanup, gameplay

#3488 add warning for supported POF file versions
  code/model/modelread.cpp
Labels: cleanup

#3382 Fix missing clang-9 binary in build image
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/build-test.yaml
  .github/workflows/pr-workflow.yaml
Labels: build

#3326 POF 2118 and SLC2 support
  code/model/modelcollide.cpp
  code/model/modelread.cpp
  code/model/modelsinc.h
Labels: Waiting for Stable, bugfix, models

#3487 center the persistent sound by default
  code/ship/ship.cpp
Labels: cleanup, gameplay, sound

#3463 karajorma's SEXP containers, Part 3: "Add/Modify Container" FRED dialog
  fred2/CMakeLists.txt
  fred2/addmodifycontainerdlg.cpp
  fred2/addmodifycontainerdlg.h
  fred2/editcontainernamedlg.cpp
  fred2/editcontainernamedlg.h
  fred2/fred.rc
  fred2/resource.h
  fred2/resource.hm
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
Labels: enhancement, feature, fred

#3493 fix to #3476
  code/object/objectsnd.cpp
  code/object/objectsnd.h
  code/scripting/api/objs/object.cpp
Labels: bugfix, scripting, sound

#3496 add a scripting function for playing cutscenes in the UI
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/enums.cpp
Labels: interface, scripting, ui

#3494 Bugfix for waypoint turnrate
  code/ai/ai_flags.h
  code/ai/aicode.cpp
Labels: ai, bugfix

#3499 Add escape character for < and > in html output
  code/parse/sexp.cpp
Labels: bugfix, general modding

#3498 Add Menu and Mission resetting to scripting state.
  freespace2/freespace.cpp
Labels: Point Release Candidate, bugfix

#3505 Add Keyboard Shortcut for `Save As` in FRED
  fred2/fred.rc
Labels: enhancement, fred

#3506 some bitwise operation enhancements
  code/scripting/api/libs/bitops.cpp
  test/src/scripting/api/bitops.cpp
  test/test_data/scripting/bitops/addBit/data/scripts/test.lua
  test/test_data/scripting/bitops/setBit/data/scripts/test.lua
  test/test_data/scripting/bitops/unsetBit/data/scripts/test.lua
Labels: enhancement, scripting

#3508 add bitwise operations with enums
  code/scripting/api/libs/bitops.cpp
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/object.cpp
Labels: enhancement, scripting

#3497 fix missiles locking during pause
  code/hud/hudlock.cpp
Labels: Point Release Candidate, bugfix

#3509 Add shadow map generation for briefing
  code/missionui/missionbrief.cpp
Labels: bugfix, graphics

#3354 actually use GS_STATE_INVALID
  code/gamesequence/gamesequence.cpp
  code/graphics/2d.cpp
Labels: cleanup

#3520 Restore original error handling of stuff_int_list
  code/parse/parselo.cpp
Labels: cleanup

#3489 add some more sophisticated POF version handling
  code/model/modelread.cpp
Labels: cleanup, models

#3514 Properly handle death due to negative hull repair rate
  code/ship/ship.cpp
Labels: fix, gameplay

#3511 Bugfix for beam attenuation damage
  code/weapon/beam.cpp
  code/weapon/beam.h
Labels: fix, gameplay

#3524 Remove usage of deprecated CMake module
  cmake/Cxx11.cmake
  cmake/platformChecks.cmake
  cmake/platformChecks.h.in
  code/cutscene/Decoder.h
  code/cutscene/ffmpeg/internal.h
  code/globalincs/pstypes.h
  code/globalincs/scp_defines.h
  code/globalincs/toolchain/gcc.h
  code/globalincs/toolchain/mingw.h
  code/graphics/opengl/ShaderProgram.h
  code/graphics/software/FontManager.h
  code/graphics/util/UniformAligner.h
  code/math/fix.h
  code/network/multi_sexp.h
  code/particle/ParticleSourceWrapper.h
  code/particle/effects/ConeShape.h
  code/particle/effects/SphereShape.h
  code/pilotfile/FileHandler.h
  code/source_groups.cmake
  code/utils/unicode.cpp
Labels: build

#3521 Bugfix type 5 shooter scale offset
  code/weapon/beam.cpp
Labels: fix, gameplay

#3457 Add weapon optimum range for AI fighters
  code/ai/aibig.cpp
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/lab/dialogs/class_variables.cpp
  code/ship/ship.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: ai, enhancement

#3485 support opening of web urls on PXO screens
  code/network/multi_pxo.cpp
  code/network/multi_pxo.h
Labels: multi

#3501 Add in-game options menu options for lightshafts and bloom
  code/graphics/opengl/gropenglpostprocessing.cpp
  code/graphics/post_processing.cpp
  code/graphics/post_processing.h
  code/lab/dialogs/render_options.cpp
  code/lab/renderer/lab_renderer.h
Labels: fix, graphics, ui

#3504 maintain a copy of the default translations to check against untranslated strings
  code/localization/localize.cpp
  fred2/management.cpp
  qtfred/src/mission/management.cpp
Labels: cleanup, fix, localization

#3469 Add external weapon model angle offset
  code/hud/hudtarget.cpp
  code/model/model.h
  code/model/modelread.cpp
  code/object/object.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: cleanup, enhancement

#3064 Feature/time to goal
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement, sexps

#3525 Use ccache to speed up some PR builds
  .github/workflows/master-build.yaml
  .github/workflows/pr-workflow.yaml
Labels: build

#3528 add is-language
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: enhancement, localization, sexps

#3512 Fix leaking of game objects and memory in F3 lab
  code/lab/dialogs/actions.cpp
  code/lab/dialogs/actions.h
  code/lab/dialogs/backgrounds.cpp
  code/lab/dialogs/backgrounds.h
  code/lab/dialogs/class_descriptions.cpp
  code/lab/dialogs/class_descriptions.h
  code/lab/dialogs/class_options.cpp
  code/lab/dialogs/class_options.h
  code/lab/dialogs/class_variables.cpp
  code/lab/dialogs/class_variables.h
  code/lab/dialogs/lab_dialog.h
  code/lab/dialogs/render_options.cpp
  code/lab/dialogs/render_options.h
  code/lab/dialogs/ship_classes.cpp
  code/lab/dialogs/ship_classes.h
  code/lab/dialogs/weapon_classes.cpp
  code/lab/dialogs/weapon_classes.h
  code/lab/labv2.cpp
  code/lab/labv2_internal.h
  code/lab/manager/lab_manager.cpp
  code/lab/manager/lab_manager.h
  code/lab/renderer/lab_renderer.cpp
  code/lab/renderer/lab_renderer.h
Labels: cleanup, fix, interface, ui

#2922 Refactor hud escort list to be less crazy
  code/hud/hudescort.cpp
  code/hud/hudescort.h
  code/network/multi.cpp
  code/object/object.h
  code/parse/sexp.cpp
  freespace2/freespace.cpp
Labels: HUD, cleanup, enhancement, multi

#3183 Add AI support for multilock
  code/ai/ai.h
  code/ai/aicode.cpp
  code/hud/hudlock.cpp
  code/ship/ship.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: ai, enhancement, fix, gameplay

#3529 Add shield regen hit delay
  code/ai/aicode.cpp
  code/hud/hudets.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement, gameplay

#3443 Optimize trail rendering
  code/tracing/categories.cpp
  code/tracing/categories.h
  code/weapon/trails.cpp
Labels: enhancement, graphics

#3470 Reimplement matrix3 multiplication based on a common overloaded operator
  code/globalincs/pstypes.h
  code/math/vecmat.cpp
  code/math/vecmat.h
Labels: cleanup

#3533 Initialize shield regen hit delay
  code/ship/ship.cpp
Labels: fix

#3532 Bugfix with ai multilock and no dumbfire
  code/ship/ship.cpp
Labels: fix, gameplay

#3531 Fix model point shield handling for mini target shields
  code/hud/hudshield.cpp
Labels: HUD, fix

#3534 Initialize `n_quadrants` before setting shield strength
  code/ship/ship.cpp
Labels: fix

#3535 Inline matrix multiplication ops for performance improvements
  code/math/vecmat.cpp
  code/math/vecmat.h
Labels: enhancement

#3536 allow characters in SEXP help
  code/parse/sexp/LuaSEXP.cpp
Labels: fix

#3545 fix 3539
  code/parse/parselo.cpp
Labels: fix

#3540 Remove Buggy Function and Let Debris End Naturally
  code/debris/debris.cpp
  code/debris/debris.h
Labels: fix
