Repository scp-fs2open/fs2open.github.com, pull requests merged in 2021-11, with the labels that each got.

#3743 make gamesnd a little more robust
  code/gamesnd/gamesnd.cpp
  code/gamesnd/gamesnd.h
  code/scripting/api/objs/sound.cpp
  code/ship/ship.cpp
Labels: enhancement, sound

#3749 Refactor CI scripts to make release builds more robust and flexible
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/nightly-trigger.yml
  ci/post/file_list.py
  ci/post/forum.py
  ci/post/installer.py
  ci/post/main.py
  ci/post/nebula.py
  ci/post/nightly.mako
  ci/post/release.mako
  ci/post/requirements.txt
  ci/post/util.py
Labels: ci

#3748 Add head-on laser bitmaps
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: graphics, feature

#3764 fix a major bug in ba.rand32f
  code/scripting/api/libs/base.cpp
Labels: fix, scripting, Point Release Candidate

#3745 spelling fixes
  code/ai/aicode.cpp
  code/hud/hud.cpp
  code/hud/hudbrackets.cpp
  code/mod_table/mod_table.cpp
  code/parse/sexp.cpp
  code/scripting/ade.cpp
  code/scripting/ade_api.h
  code/tracing/categories.cpp
  code/tracing/categories.h
  test/src/mod/test_mod_table.cpp
  test/test_data/mod/correct_targeted_version/data/tables/test-mod.tbm
  test/test_data/mod/future_targeted_version/data/tables/test-mod.tbm
Labels: cleanup

#3714 Split From #3674 Flags Dialog
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/ShipFlagsDialogModel.cpp
  qtfred/src/mission/dialogs/ShipFlagsDialogModel.h
  qtfred/src/ui/dialogs/ShipEditorDialog.cpp
  qtfred/src/ui/dialogs/ShipEditorDialog.h
  qtfred/src/ui/dialogs/ShipFlagsDialog.cpp
  qtfred/src/ui/dialogs/ShipFlagsDialog.h
  qtfred/src/ui/widgets/ShipFlagCheckbox.cpp
  qtfred/src/ui/widgets/ShipFlagCheckbox.h
  qtfred/ui/ShipFlagsDialog.ui
Labels: qtfred

#3761 polish sexp syntax checking
  code/mission/missioncampaign.cpp
  code/parse/sexp.cpp
Labels: fix, sexps

#3767 guard against CTD in sexp variables
  code/parse/sexp.cpp
Labels: sexps

#3752 Add destroy-instantly-with-debris
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement, sexps

#3717 Split From #3674 Goals Dialog
  qtfred/source_groups.cmake
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/Editor.h
  qtfred/src/mission/dialogs/ShipGoalsDialogModel.cpp
  qtfred/src/mission/dialogs/ShipGoalsDialogModel.h
  qtfred/src/ui/dialogs/ShipEditorDialog.cpp
  qtfred/src/ui/dialogs/ShipEditorDialog.h
  qtfred/src/ui/dialogs/ShipGoalsDialog.cpp
  qtfred/src/ui/dialogs/ShipGoalsDialog.h
  qtfred/ui/ShipGoalsDialog.ui
Labels: qtfred

#3715 Split From #3674 Initial Status Dialog
  code/object/objectdock.cpp
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/ShipInitialStatusDialogModel.cpp
  qtfred/src/mission/dialogs/ShipInitialStatusDialogModel.h
  qtfred/src/ui/dialogs/ShipEditorDialog.cpp
  qtfred/src/ui/dialogs/ShipEditorDialog.h
  qtfred/src/ui/dialogs/ShipInitialStatusDialog.cpp
  qtfred/src/ui/dialogs/ShipInitialStatusDialog.h
  qtfred/ui/ShipInitialStatus.ui
Labels: qtfred

#3676 Expose nebula visibility factors
  code/fireball/fireballs.cpp
  code/mod_table/mod_table.cpp
  code/model/modelrender.cpp
  code/nebula/neb.cpp
  code/nebula/neb.h
  code/particle/particle.cpp
  code/ship/shield.cpp
  code/weapon/beam.cpp
  code/weapon/shockwave.cpp
  code/weapon/trails.cpp
  code/weapon/weapons.cpp
Labels: enhancement, graphics

#3762 Ai use lock status for optimum range choice
  code/ai/aibig.cpp
  code/ai/aicode.cpp
Labels: fix, ai

#3765 allow subtitles to use different line spacing
  code/camera/camera.cpp
  code/camera/camera.h
  code/parse/sexp.cpp
Labels: sexps, feature

#3772 Add ship flag for toggling ship passive lightning
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/ship_flags.h
  code/ship/shipfx.cpp
Labels: enhancement, graphics

#3786 refactor submodel flags and add $rotate_accel
  code/missionui/missionscreencommon.cpp
  code/model/model.h
  code/model/model_flags.h
  code/model/modelcollide.cpp
  code/model/modelinterp.cpp
  code/model/modelread.cpp
  code/model/modelrender.cpp
  code/network/multi_obj.cpp
  code/object/collideshipship.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipfx.cpp
Labels: models

#3774 indicate ambiguous goal or event matches
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: cleanup, fix, sexps

#3781 Dont exclude primary targets from 'no dead subsys targeting'
  code/hud/hudlock.cpp
Labels: fix, gameplay

#3787 Correctly size glow head-on bitmaps
  code/weapon/weapons.cpp
Labels: fix, graphics

#3771 Dont do passive lightning on destroyed subsystems
  code/ship/shipfx.cpp
Labels: fix, graphics

#3790 Change rectangle rotation to use radians
  code/graphics/render.cpp
  code/graphics/render.h
  code/scripting/api/libs/graphics.cpp
Labels: graphics, scripting

#3734 clean up some inconsistencies in cfilesystem
  code/cfile/cfilesystem.cpp
Labels: cleanup, fix

#3789 Correctly position tail for laser head on glows
  code/weapon/weapons.cpp
Labels: fix, graphics

#3796 Fix Weapon-Loadout-Specific Models
  code/missionui/missionweaponchoice.cpp
Labels: fix
