Repository scp-fs2open/fs2open.github.com, pull requests merged in 2022-12, with the labels that each got.

#4954 fix event status evaluation for repeating events
  code/parse/sexp.cpp
Labels: fix, timer/timestamp

#4943 Improved error message for missing sexp action
  code/parse/sexp/LuaSEXP.cpp
Labels: cleanup, sexps

#4948 add mouseButtonDownCount and flushMouse
  code/scripting/api/libs/controls.cpp
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/enums.h
Labels: controls, scripting

#4860 set-asteroid-field and set-debris-field sexps
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
  code/object/object.h
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
Labels: enhancement, sexps, Requested by Active Mod

#4955 Allow setting glowpoint light intensity
  code/model/model.h
  code/model/modelread.cpp
  code/model/modelrender.cpp
Labels: enhancement

#4964 fix wing name matching
  code/ship/ship.cpp
Labels: fix, Requested by Active Mod

#4962 add some additional weapon checks
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: fix

#4936 Animate More Things
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/model/modelanimation.cpp
  code/model/modelanimation.h
  code/object/object.cpp
  code/parse/sexp.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/animation_handle.cpp
  code/scripting/api/objs/animation_handle.h
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/source_groups.cmake
  code/starfield/starfield.cpp
  fred2/missionsave.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, scripting, models

#4966 Properly init cockpit_model_instance to -1
  code/ship/ship.cpp
Labels: fix

#4974 move @ removal up
  code/ship/ship.cpp
  code/weapon/weapons.cpp
Labels: cleanup

#4969 custom colors for passive lightning
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/model/model.h
  code/model/modelread.cpp
  code/model/modelrender.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipfx.cpp
Labels: enhancement

#4976 move player-is-cheating to the correct category
  code/parse/sexp.h
Labels: cleanup, sexps

#4946 per weapon auto aim feature
  code/ship/ship.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: Requested by Active Mod

#4953 Add mission flag to show bg bitmaps despite fullneb
  code/mission/mission_flags.h
  code/starfield/starfield.cpp
  fred2/bgbitmapdlg.cpp
  fred2/bgbitmapdlg.h
  fred2/fred.rc
  fred2/resource.h
Labels: enhancement

#4973 Fix custom data when using tbms
  code/ship/ship.cpp
Labels: fix, general modding

#4977 add changeable formation flying
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: enhancement, sexps, Requested by Active Mod

#4967 Mod Table Settings for Arc Widths
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/model/modelrender.cpp
Labels: enhancement, Requested by Active Mod

#4979 do correct math at parse
  code/weapon/weapons.cpp
Labels: fix

#4981 Fix edge case bugs with moveables in combination with special polymodels being animated
  code/scripting/api/libs/mission.cpp
  code/ship/ship.cpp
  code/starfield/starfield.cpp
Labels: fix

#4949 clean traitor.tbl parsing
  code/stats/scoring.cpp
Labels: cleanup

#4982 Only set the colors for passive lightning
  code/model/modelread.cpp
Labels: fix

#4983 exposes wing formation via scripting
  code/scripting/api/libs/tables.cpp
  code/scripting/api/objs/fireballclass.cpp
  code/scripting/api/objs/wing.cpp
  code/scripting/api/objs/wingformation.cpp
  code/scripting/api/objs/wingformation.h
  code/source_groups.cmake
Labels: enhancement, scripting

#4985 try disabling Qt builds
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/build-test.yaml
  .github/workflows/cache-master.yaml
  .github/workflows/test-pull_request.yaml
  ci/appveyor/build.ps1
  ci/linux/configure_cmake.sh
  ci/travis/before_script.sh
Labels: build

#4963 make message queue dynamic
  code/globalincs/memory/memory.h
  code/globalincs/systemvars.h
  code/mission/missionmessage.cpp
Labels: enhancement, Requested by Active Mod

#4961 clean up support ship mode in all cases
  code/ai/aicode.cpp
Labels: cleanup, fix, ai

#4875 dynamic events and goals
  code/gamesnd/eventmusic.cpp
  code/globalincs/vmallocator.h
  code/menuui/playermenu.cpp
  code/mission/missioncampaign.cpp
  code/mission/missioncampaign.h
  code/mission/missiongoals.cpp
  code/mission/missiongoals.h
  code/mission/missionlog.cpp
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/mission/missiontraining.cpp
  code/network/multi_campaign.cpp
  code/network/multimsgs.cpp
  code/network/stand_gui-unix.cpp
  code/network/stand_gui.cpp
  code/parse/sexp.cpp
  code/pilotfile/csg.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/briefing.cpp
  code/scripting/api/objs/event.cpp
  code/ship/ship.cpp
  fred2/campaigntreeview.cpp
  fred2/dumpstats.cpp
  fred2/eventeditor.cpp
  fred2/eventeditor.h
  fred2/freddoc.cpp
  fred2/fredview.cpp
  fred2/management.cpp
  fred2/management.h
  fred2/messageeditordlg.cpp
  fred2/missiongoalsdlg.cpp
  fred2/missiongoalsdlg.h
  fred2/missionsave.cpp
  fred2/sexp_tree.cpp
  fred2/voiceactingmanager.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/dialogs/MissionGoalsDialogModel.cpp
  qtfred/src/mission/dialogs/MissionGoalsDialogModel.h
  qtfred/src/mission/missionsave.cpp
  qtfred/src/ui/dialogs/EventEditorDialog.cpp
  qtfred/src/ui/dialogs/EventEditorDialog.h
  qtfred/src/ui/dialogs/MissionGoalsDialog.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: cleanup, refactor

#4986 Ensure effect animations load before static bitmaps
  code/nebula/neb.cpp
  code/weapon/weapons.cpp
Labels: fix, graphics

#4965 SEXP operators, categories, and subcategories refactoring
  code/globalincs/counter.hpp
  code/network/multi.h
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp/EngineSEXP.cpp
  code/parse/sexp/EngineSEXP.h
  code/parse/sexp/LuaSEXP.cpp
  code/parse/sexp/sexp_lookup.cpp
  code/parse/sexp/sexp_lookup.h
  code/scripting/api/objs/oswpt.cpp
  code/source_groups.cmake
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, refactor, Requested by Active Mod

#4992 fix crash in ship_close_cockpit_displays
  code/ship/ship.cpp
Labels: fix

#4870 Asteroid/Debris cleanup + Modular asteroids table
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
  code/hud/hudtargetbox.cpp
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  code/starfield/starfield.h
  fred2/asteroideditordlg.cpp
  fred2/dumpstats.cpp
  fred2/fred.rc
  fred2/missionsave.cpp
  fred2/resource.h
  fred2/sexp_tree.cpp
  qtfred/src/mission/dialogs/AsteroidEditorDialogModel.cpp
  qtfred/src/mission/missionsave.cpp
  qtfred/src/ui/dialogs/AsteroidEditorDialog.cpp
  qtfred/src/ui/dialogs/AsteroidEditorDialog.h
  qtfred/ui/AsteroidEditorDialog.ui
Labels: enhancement, cleanup, general modding

#4995 fix subcategory comparison
  code/mission/missionparse.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix

#4997 subcategory fixes and followup
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp/EngineSEXP.cpp
  code/parse/sexp/EngineSEXP.h
  code/parse/sexp/LuaAISEXP.cpp
  code/parse/sexp/sexp_lookup.cpp
  fred2/management.cpp
  freespace2/freespace.cpp
  qtfred/src/main.cpp
  qtfred/src/mission/management.cpp
  qtfred/src/mission/management.h
Labels: cleanup, fix, sexps, scripting

#4996 Add missing locale argument to `std::isdigit()` calls.
  code/scripting/api/libs/base.cpp
Labels: fix, windows

#4960 Rework Script Conditions
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aiturret.cpp
  code/asteroid/asteroid.cpp
  code/controlconfig/controlsconfig.cpp
  code/debris/debris.cpp
  code/globalincs/version.cpp
  code/globalincs/version.h
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/hud/hudmessage.cpp
  code/io/key.cpp
  code/io/mouse.cpp
  code/io/mouse.h
  code/menuui/readyroom.cpp
  code/menuui/readyroom.h
  code/mission/missioncampaign.cpp
  code/mission/missionmessage.cpp
  code/mission/missionparse.cpp
  code/missionui/missionscreencommon.cpp
  code/object/collidedebrisship.cpp
  code/object/collidedebrisweapon.cpp
  code/object/collideshipship.cpp
  code/object/collideshipweapon.cpp
  code/object/collideweaponweapon.cpp
  code/object/object.cpp
  code/parse/sexp.cpp
  code/pilotfile/plr.cpp
  code/scripting/api/libs/engine.cpp
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/doc_html.cpp
  code/scripting/doc_json.cpp
  code/scripting/global_hooks.cpp
  code/scripting/global_hooks.h
  code/scripting/hook_api.cpp
  code/scripting/hook_api.h
  code/scripting/hook_conditions.cpp
  code/scripting/hook_conditions.h
  code/scripting/scripting.cpp
  code/scripting/scripting.h
  code/scripting/scripting_doc.h
  code/ship/afterburner.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipfx.cpp
  code/ship/shiphit.cpp
  code/source_groups.cmake
  code/weapon/beam.cpp
  code/weapon/weapons.cpp
  freespace2/freespace.cpp
Labels: enhancement, cleanup, fix, scripting, refactor, documentation

#4999 Remove problematic counter library
  code/globalincs/counter.hpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/source_groups.cmake
Labels: fix, build

#5001 Fix Hook Refactor Bug
  freespace2/freespace.cpp
Labels: regression, fix, scripting

#5000 Allow player turrets to fire despite play dead
  code/ai/aicode.cpp
  code/ship/ship.cpp
Labels: fix, gameplay

#5002 beam teams
  code/scripting/api/objs/beam.cpp
Labels: enhancement, scripting, Requested by Active Mod

#5015 fix vintage copypasta bug
  code/ai/aicode.cpp
Labels: fix

#5016 initialize NavPoint properly
  code/autopilot/autopilot.h
Labels: fix

#5014 Do not include -destroyed subobjects in renderTechModel
  code/scripting/api/objs/shipclass.cpp
Labels: fix

#5004 Use the correct variables in this function
  code/network/multi_interpolate.cpp
Labels: fix, multi

#5008 Add missing asteroid debris argument type error checking
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/sexp_tree.cpp
Labels: cleanup, general modding

#5021 Fix OnBeamCollision Oversight
  code/scripting/global_hooks.cpp
Labels: fix

#5024 Change check of POST response result
  .github/workflows/post-build-release.yaml
  ci/post/forum.py
Labels: fix, build

#5027 add hu.isCommMenuOpen
  code/scripting/api/libs/hud.cpp
Labels: scripting, Requested by Active Mod

#5030 address issues related to cf.openFile() error handling
  code/cfile/cfile.cpp
  code/scripting/api/libs/cfile.cpp
Labels: fix

#5025 Update 22.4 version references to 23.0
  code/ai/ai_profiles.cpp
  code/mod_table/mod_table.cpp
  code/scripting/api/objs/enums.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: fix, build

#5029 Update regen rates and autoaim fov on ship class change
  code/ship/ship.cpp
Labels: fix

#5038 patch some crash vulnerabilities in hud_target_live_turret
  code/hud/hudtarget.cpp
Labels: fix, HUD

#5037 patch hud-lock iteration for objects that aren't ships
  code/hud/hudlock.cpp
  code/ship/awacs.cpp
Labels: fix, HUD

#5043 Fix a crash in `change_ship_type`
  code/ship/ship.cpp
Labels: fix

#5041 consolidation of tech rendering methods
  code/model/modelrender.cpp
  code/model/modelrender.h
  code/scripting/api/objs/shipclass.cpp
  code/scripting/api/objs/weaponclass.cpp
Labels: fix, graphics

#5040 add should-be-dead checks for all ship iterations
  code/ai/aibig.cpp
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aiturret.cpp
  code/asteroid/asteroid.cpp
  code/autopilot/autopilot.cpp
  code/gamesnd/eventmusic.cpp
  code/hud/hud.cpp
  code/hud/hudescort.cpp
  code/hud/hudsquadmsg.cpp
  code/hud/hudtarget.cpp
  code/hud/hudwingmanstatus.cpp
  code/mission/missionhotkey.cpp
  code/mission/missionparse.cpp
  code/missionui/redalert.cpp
  code/network/multi_ingame.cpp
  code/network/multi_respawn.cpp
  code/network/multi_team.cpp
  code/network/multimsgs.cpp
  code/network/multiutil.cpp
  code/parse/sexp.cpp
  code/playerman/playercontrol.cpp
  code/scripting/api/objs/oswpt.cpp
  code/ship/awacs.cpp
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/weapon/emp.cpp
  code/weapon/weapons.cpp
  freespace2/freespace.cpp
Labels: cleanup, fix

#5051 fix wing cues and add some more error checks
  code/parse/sexp.cpp
  fred2/wing.cpp
  qtfred/src/mission/EditorWing.cpp
Labels: fix

#5052 apply the HDR colorspace stuff _after_ mixing in the team color glows
  code/def_files/data/effects/main-f.sdr
Labels: fix

#5057 Use `textify_scancode_universal()` in more places.
  code/scripting/scripting.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: regression, fix, qtfred, controls, fred, scripting

#5056 comment tweak
  code/mission/missiongoals.cpp
Labels: cleanup, documentation

#5059 Check for parse object before team color change
  code/ship/ship.cpp
Labels: fix
