Repository scp-fs2open/fs2open.github.com, pull requests merged in 2022-11, with the labels that each got.

#4828 allow borrowing flyby sounds from a previously parsed species
  code/gamesnd/gamesnd.cpp
  code/species_defs/species_defs.cpp
  code/species_defs/species_defs.h
Labels: fix, sound

#4824 Further limit what built-in UI elements can be setup when using SCPUI
  code/missionui/missionbrief.cpp
  code/missionui/missionscreencommon.cpp
  code/missionui/missionscreencommon.h
  code/missionui/missionshipchoice.cpp
  code/missionui/missionshipchoice.h
  code/missionui/missionweaponchoice.cpp
  code/missionui/missionweaponchoice.h
  code/scripting/api/libs/ui.cpp
Labels: fix, ui, scripting

#4842 Clearable Ship/Subsystem Targets via script
  code/scripting/api/objs/ship.cpp
  code/scripting/api/objs/subsystem.cpp
Labels: enhancement, scripting

#4839 add a few scripting dock functions
  code/physics/physics.cpp
  code/physics/physics.h
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
Labels: enhancement, scripting

#4844 fix timestamp_in_between functions
  code/io/timer.cpp
  code/io/timer.h
Labels: fix, multi, timer/timestamp

#4834 implement modular nebula.tbl
  code/mission/missionparse.cpp
  code/nebula/neb.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, general modding

#4822 libRocket Texture Passthrough
  code/scpui/RocketRenderingInterface.cpp
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/texture.cpp
  code/scripting/api/objs/texture.h
Labels: ui, scripting, refactor

#4841 Make sure that the escort list only lists valid targets on multi
  code/hud/hudescort.cpp
Labels: fix, multi, HUD

#4850 Minor lighting shader fixes
  code/def_files/data/effects/deferred-f.sdr
  code/def_files/data/effects/lighting.sdr
  code/def_files/data/effects/main-f.sdr
Labels: fix, graphics

#4848 Small fix for `turret_next_fire_pos` in beam-fire
  code/parse/sexp.cpp
Labels: fix, sexps

#4853 properly get badge name
  code/scripting/api/libs/ui.cpp
Labels: cleanup, ui, scripting

#4852 Allow overriding `gvec` in `fireWeapon` on subsystems
  code/scripting/api/objs/subsystem.cpp
Labels: enhancement, scripting

#4859 always set the default gloss uniform since it is now always used
  code/graphics/uniforms.cpp
Labels: fix, graphics

#4847 Add burst shots and delay to script API
  code/scripting/api/objs/weaponclass.cpp
Labels: enhancement, scripting

#4846 Add `isMultipart` and `getModelFlag` functions on subsystems
  code/scripting/api/objs/subsystem.cpp
  code/ship/ship.h
Labels: enhancement, scripting

#4862 improve SEXP syntax checking
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
Labels: fix, sexps

#4845 Modular iff table
  code/iff_defs/iff_defs.cpp
Labels: enhancement, general modding

#4857 toggle-asteroid-field sexp
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, sexps

#4851 Modular medals
  code/network/multi_fstracker.cpp
  code/network/multimsgs.cpp
  code/parse/sexp.cpp
  code/pilotfile/csg.cpp
  code/pilotfile/csg_convert.cpp
  code/stats/medals.cpp
  code/stats/medals.h
  code/stats/scoring.cpp
  code/stats/scoring.h
  fred2/management.cpp
  fred2/sexp_tree.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/management.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: enhancement, general modding

#4826 Optional discord presence
  code/libs/discord/discord.cpp
  code/libs/discord/discord.h
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  freespace2/freespace.cpp
Labels: enhancement

#4868 fix decal debug warnings in FRED
  code/decals/decals.cpp
Labels: fix, fred

#4863 add numDocked and isDocked
  code/scripting/api/objs/ship.cpp
Labels: enhancement, scripting

#4856 refactor mission initialization
  code/lab/renderer/lab_renderer.cpp
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/nebula/neb.cpp
  code/nebula/neb.h
  code/object/waypoint.cpp
  code/object/waypoint.h
  code/ship/ship.cpp
  code/ship/ship.h
  code/starfield/nebula.cpp
  code/starfield/nebula.h
  code/starfield/starfield.cpp
  fred2/bgbitmapdlg.cpp
  fred2/dumpstats.cpp
  fred2/freddoc.cpp
  fred2/fredrender.cpp
  fred2/fredrender.h
  fred2/management.cpp
  fred2/missionsave.cpp
  fred2/wing.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/EditorWing.cpp
  qtfred/src/mission/management.cpp
  qtfred/src/mission/missionsave.cpp
Labels: qtfred, fred, refactor, Requested by Active Mod

#4869 Fix num comparison for FS2 medals
  code/stats/medals.cpp
Labels: fix

#4872 fix lab CTD
  code/lab/manager/lab_manager.cpp
Labels: fix

#4865 clean up some obsolete fields
  code/ai/ai.cpp
  code/ai/ai.h
  code/ai/aicode.cpp
  code/autopilot/autopilot.cpp
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/ship/ship.cpp
  fred2/management.cpp
  fred2/missionsave.cpp
  fred2/wing.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/missionsave.cpp
Labels: cleanup

#4874 use correct path masks for parse objects
  code/mission/missionparse.cpp
Labels: fix

#4879 Fix poof name parsing and fix lab not knowing about the new parsing
  code/lab/renderer/lab_renderer.cpp
  code/mission/missionparse.cpp
  code/nebula/neb.cpp
  code/nebula/neb.h
Labels: fix

#4866 add wing formation align button
  code/ai/aicode.cpp
  code/math/floating.h
  code/mission/missionparse.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  fred2/fred.rc
  fred2/missionsave.cpp
  fred2/resource.h
  fred2/wing_editor.cpp
  fred2/wing_editor.h
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, fred, Requested by Active Mod

#4849 increase object limits
  code/asteroid/asteroid.h
  code/globalincs/globals.h
Labels: enhancement, discussion, gameplay, general modding

#4886 Make sound environment SEXP errors recoverable.
  code/parse/sexp.cpp
Labels: fix, sound, sexps

#4882 Bugfix argument order in `drawImageCentered`
  code/scripting/api/libs/graphics.cpp
Labels: fix, scripting

#4876 replace keybinds in debriefing
  code/missionui/missiondebrief.cpp
Labels: enhancement

#4764 3d select settings
  code/cmdline/cmdline.cpp
  code/missionui/missionscreencommon.cpp
  code/missionui/missionshipchoice.cpp
  code/missionui/missionweaponchoice.cpp
  code/missionui/missionweaponchoice.h
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/shipclass.cpp
Labels: general modding, refactor

#4888 use correct math for animated textures
  code/model/modelinterp.cpp
Labels: fix

#4891 add cannot-perform-scan flag
  code/mission/mission_flags.h
  code/mission/missionparse.cpp
  code/playerman/playercontrol.cpp
  code/ship/ship.cpp
  code/ship/ship_flags.h
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, Requested by Active Mod

#4867 Refactor Lua Enums
  code/scripting/api/libs/bitops.cpp
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/libs/testing.cpp
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/enums.h
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/option.cpp
  code/scripting/api/objs/order.cpp
  code/scripting/api/objs/ship.cpp
  code/scripting/api/objs/ship_registry_entry.cpp
Labels: cleanup, fix, scripting, refactor

#4890 fix wing leader check
  code/ai/aigoals.cpp
Labels: fix

#4791 Enable client turrets to track targets
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/model/modelread.cpp
  code/network/multi.cpp
  code/network/multi.h
  code/network/multi_turret_manager.cpp
  code/network/multi_turret_manager.h
  code/network/multimsgs.cpp
  code/network/multimsgs.h
  code/network/multiutil.cpp
  code/network/multiutil.h
  code/ship/ship.cpp
  code/ship/ship.h
  code/source_groups.cmake
  freespace2/freespace.cpp
Labels: enhancement, multi, Requested by Active Mod

#4836 Fix in game joining
  code/cmdline/cmdline.cpp
  code/globalincs/flagset.h
  code/hud/hudshield.cpp
  code/io/timer.cpp
  code/io/timer.h
  code/mission/missionparse.cpp
  code/network/multi.h
  code/network/multi_ingame.cpp
  code/network/multi_obj.cpp
  code/network/multi_team.cpp
  code/network/multi_time_manager.cpp
  code/network/multi_time_manager.h
  code/network/multimsgs.cpp
  code/network/multiui.cpp
  code/network/multiutil.cpp
  code/ship/ship.cpp
Labels: enhancement, multi, Requested by Active Mod

#4881 fix swapping of things in FRED
  fred2/campaigneditordlg.cpp
  fred2/eventeditor.cpp
  fred2/missiongoalsdlg.cpp
Labels: fix, fred

#4896 Fix Enum assignments
  code/scripting/lua.cpp
Labels: fix

#4771 add support for subfolders to cfile
  cmake/platform-win32.cmake
  code/bmpman/bmpman.cpp
  code/cfile/cfile.cpp
  code/cfile/cfile.h
  code/cfile/cfilesystem.cpp
  code/cfile/cfilesystem.h
  code/def_files/data/scripts/cfile_require.lua
  code/graphics/generic.cpp
  code/graphics/software/FontManager.cpp
  code/localization/localize.cpp
  code/localization/localize.h
  code/pilotfile/csg_convert.cpp
  code/pilotfile/plr_convert.cpp
  code/sound/ffmpeg/FFmpegWaveFile.cpp
  fred2/campaigneditordlg.cpp
  test/src/cfile/cfile.cpp
  test/test_data/cfile/subfolder_list/data/tables/file.tbl
  test/test_data/cfile/subfolder_list/data/tables/folder/file.tbl
  test/test_data/cfile/subfolders/data/tables/file.tbl
  test/test_data/cfile/subfolders/data/tables/sub/file2.tbl
  test/test_data/cfile/subfolders/data/tables/sub/folder/file3.tbl
Labels: enhancement

#4897 Make sure that we check the correct instance
  code/network/multiutil.cpp
Labels: fix, multi

#4892 Increase default Briefing window size and allow custom setting
  code/mission/missionbriefcommon.h
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  fred2/briefingeditordlg.cpp
  fred2/fredrender.cpp
  qtfred/src/mission/FredRenderer.cpp
Labels: enhancement, qtfred, fred

#4902 Fix Flashlights
  code/def_files/data/effects/deferred-f.sdr
Labels: fix, graphics

#4893 Fix overhead style
  code/missionui/missionscreencommon.cpp
  code/mod_table/mod_table.cpp
Labels: fix, ui

#4895 Check nebula and poof bitmaps at parse time
  code/nebula/neb.cpp
Labels: fix, general modding

#4907 by default, start texture animation at the beginning of a mission
  code/io/timer.cpp
  code/io/timer.h
  code/model/modelrender.cpp
Labels: models, timer/timestamp

#4908 Add special ship info index
  code/ai/aigoals.cpp
  code/hud/hudsquadmsg.cpp
  code/mission/missionparse.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: fix, ai

#4903 Move the assertion
  code/ai/aicode.cpp
Labels: cleanup, ai

#4905 setup callsign and altname fields to use the full 31 characters allowed
  fred2/fred.rc
  fred2/shipeditordlg.cpp
Labels: cleanup, fred

#4885 fix campaign loading in FRED
  code/cfile/cfilesystem.cpp
  code/menuui/readyroom.cpp
  code/mission/missioncampaign.cpp
  code/mission/missioncampaign.h
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/pilotfile/csg.cpp
  code/scripting/api/objs/player.cpp
  fred2/campaigneditordlg.cpp
  fred2/campaigneditordlg.h
  fred2/campaignfilelistbox.cpp
  fred2/campaignfilelistbox.h
  fred2/campaigntreeview.cpp
  fred2/campaigntreewnd.cpp
Labels: fix, fred

#4898 hud-force-sensor-static sexp
  code/hud/hudtargetbox.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/radar/radar.cpp
  code/radar/radardradis.cpp
  code/radar/radarorb.cpp
  code/ship/ship.cpp
  code/ship/subsysdamage.h
Labels: enhancement, HUD, sexps

#4915 fix a copy+paste error
  code/mission/missionparse.cpp
Labels: fix

#4913 Adjust ssssssssssi in one more place
  code/mission/missionparse.cpp
  code/ship/ship.cpp
Labels: fix, ai

#4917 fix crash when changing ship classes in FRED
  code/ship/ship.cpp
Labels: fix, fred

#4901 Fix a warning
  code/scripting/api/objs/control_binding.cpp
Labels: fix, controls, scripting

#4877 option to always hide hidden hotkey ships
  code/mission/missionhotkey.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: enhancement

#4911 Setting up Vampirism again... again
  code/ship/shiphit.cpp
  code/weapon/weapon.h
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
Labels: gameplay, feature

#4803 Implement gravity
  code/ai/aibig.cpp
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
  code/debris/debris.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtarget.h
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/model/model.h
  code/network/multi_interpolate.cpp
  code/network/multi_interpolate.h
  code/object/collideshipweapon.cpp
  code/object/objcollide.cpp
  code/object/object.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/physics/physics.cpp
  code/physics/physics.h
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/physics_info.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipfx.cpp
  code/ship/shiphit.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
  fred2/fredrender.cpp
  qtfred/src/mission/EditorViewport.cpp
Labels: ai, physics, feature

#4919 fix full ship list selection in FRED
  fred2/fredview.cpp
  fred2/mainfrm.cpp
  fred2/mainfrm.h
  fred2/management.cpp
  fred2/management.h
  qtfred/src/mission/Editor.cpp
  qtfred/src/ui/widgets/ColorComboBox.cpp
Labels: fix, fred

#4923 avoid playing voice messages with aux effects (EFX)
  code/sound/ds.cpp
Labels: fix, sound

#4914 add text-to-speech support for macOS
  CMakeLists.txt
  cmake/finder/FindSpeech.cmake
  code/sound/speech.cpp
  code/sound/speech.mm
  code/source_groups.cmake
Labels: enhancement, sound, mac

#4858 Add yaml file defining build options for vscode cmake tools users.
  cmake-variants.yaml
Labels: discussion, build

#4861 More old dead shader override code that isn't hooked to anything anymore
  code/def_files/data/effects/main-f.sdr
  code/def_files/data/effects/main-g.sdr
  code/def_files/data/effects/main-v.sdr
  code/globalincs/systemvars.cpp
  code/globalincs/systemvars.h
  code/graphics/uniforms.cpp
  code/graphics/util/uniform_structs.h
Labels: cleanup, graphics

#4244 Fix strange warp glow sizing
  code/fireball/warpineffect.cpp
Labels: fix, discussion, graphics

#4926 Fix an oversight in collision code from recent changes
  code/object/objcollide.cpp
Labels: fix, physics

#4924 Add '+Don't Interrupt Playing Sounds'
  code/model/modelanimation_segments.cpp
  code/model/modelanimation_segments.h
Labels: enhancement, sound, models

#4928 style tweaks for recently added options
  code/mission/missionhotkey.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: cleanup

#4927 add no_fred flag for weapons, and patch no_fred for ships
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
  fred2/shipeditordlg.cpp
  fred2/shipeditordlg.h
  fred2/weaponeditordlg.cpp
  fred2/weaponeditordlg.h
Labels: enhancement, fred

#4884 add set-order-allowed-for-target sexp
  code/ai/ailua.cpp
  code/ai/ailua.h
  code/hud/hudsquadmsg.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement, ai, Requested by Active Mod

#4931 fix two warnings
  code/object/collideshipweapon.cpp
Labels: cleanup

#4880 Modular bolts
  code/nebula/neblightning.cpp
  code/nebula/neblightning.h
Labels: enhancement, general modding

#4937 Fix RefCounting on invalid textures
  code/scripting/api/objs/texture.cpp
Labels: fix, scripting

#4934 don't process turrets or subsystems when playing dead
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ship/ship.cpp
Labels: fix, ai

#4938 Enhance OnDialogX Hooks to encompass Death Popups
  code/popup/popup.cpp
  code/popup/popupdead.cpp
  code/scripting/global_hooks.cpp
Labels: enhancement, ui, scripting

#4940 add proper support of subfolders to lua listFiles
  code/scripting/api/libs/cfile.cpp
Labels: fix, scripting

#4942 use case-insensitive comparison of cfile pathtypes
  code/cfile/cfile.cpp
Labels: fix

#4932 make sexp_tree dragging more user-friendly
  fred2/campaigneditordlg.cpp
  fred2/campaigneditordlg.h
  fred2/eventeditor.cpp
  fred2/eventeditor.h
  fred2/missiongoalsdlg.cpp
  fred2/missiongoalsdlg.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: enhancement, fred

#4929 fix the rest of the autoscaled attributes
  code/ai/ai.h
  code/ai/aicode.cpp
Labels: fix, ai

#4944 fix crash on mission load
  code/ai/aigoals.cpp
Labels: fix

#4916 guard against unknown variables
  code/parse/sexp.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, qtfred, fred

#4387 Cheat framework allowing for custom cheats, sexp for cheat used and On Cheat lua hook
  code/cheats_table/cheats_table.cpp
  code/cheats_table/cheats_table.h
  code/def_files/data/tables/cheats.tbl
  code/io/key.cpp
  code/io/key.h
  code/io/keycontrol.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/scripting/global_hooks.cpp
  code/scripting/global_hooks.h
  code/source_groups.cmake
  freespace2/freespace.cpp
Labels: discussion, gameplay, feature, Requested by Active Mod
