Repository scp-fs2open/fs2open.github.com, pull requests merged in 2022-06, with the labels that each got.

#4319 Add gr.CurrentResizeMode
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/enums.h
Labels: enhancement, scripting

#4323 minor cleanup of turret names
  code/hud/hudtargetbox.cpp
Labels: cleanup

#4305 Support using string-based containers in some when-argument SEXPs
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: enhancement, qtfred, sexps, fred

#4168 Set up Mac builds on CI
  .github/workflows/build-nightly.yaml
  .github/workflows/build-test.yaml
  .github/workflows/test-pull_request.yaml
  CMakeLists.txt
  ci/linux/configure_cmake.sh
  ci/linux/create_dist_pack.sh
  ci/linux/run_tests.sh
Labels: build, ci

#4332 clean up ship arrival and departure effects
  code/ship/shipfx.cpp
Labels: cleanup, fix

#4341 better error checking of campaign loop branches in FRED
  fred2/campaigntreewnd.cpp
Labels: fix, fred

#4343 Add overload for timestamp_elapsed_safe
  code/io/timer.cpp
  code/io/timer.h
Labels: cleanup, timer/timestamp

#4208 Weapon lights
  code/graphics/color.cpp
  code/graphics/color.h
  code/graphics/opengl/gropengldeferred.cpp
  code/lighting/lighting.cpp
  code/lighting/lighting.h
  code/lighting/lighting_profiles.cpp
  code/lighting/lighting_profiles.h
  code/object/object.cpp
  code/parse/parsehi.cpp
  code/parse/parsehi.h
  code/source_groups.cmake
  code/weapon/beam.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, graphics

#4339 log non-psnet packets for debugging
  code/network/psnet2.cpp
Labels: fix, multi

#4317 fix a bunch of graphics functions to respect GR_STUB
  code/decals/decals.cpp
  code/graphics/2d.cpp
  code/graphics/light.cpp
  code/graphics/post_processing.cpp
  code/graphics/render.cpp
  code/graphics/shadows.cpp
  code/starfield/starfield.cpp
Labels: fix, graphics

#4326 Support using containers with random-multiple-of SEXP
  code/parse/sexp.cpp
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
Labels: enhancement, sexps

#4347 Fix line endings in a few more files
  freespace2/resources/win/version.rc2
  lib/prebuilt.cmake
Labels: cleanup

#4346 Fix line endings in the core codebase
  code/graphics/opengl/gropenglquery.cpp
  code/graphics/opengl/gropenglquery.h
  code/parse/parselo.cpp
  code/pilotfile/BinaryFileHandler.cpp
  code/pilotfile/BinaryFileHandler.h
  code/pilotfile/FileHandler.h
  code/sound/ffmpeg/FFmpegAudioReader.cpp
  code/tracing/TraceEventWriter.h
  code/tracing/categories.cpp
  code/tracing/categories.h
  code/utils/boost/syncboundedqueue.h
  fred2/wing_editor.cpp
Labels: cleanup

#4342 Add option to expand warning on unbound keys
  code/mission/missiontraining.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: enhancement, controls, HUD

#4331 Draw 3d lines in space with Lua
  code/graphics/material.cpp
  code/graphics/material.h
  code/render/batching.cpp
  code/render/batching.h
  code/scripting/api/libs/graphics.cpp
Labels: enhancement, graphics, scripting

#4327 add some extra safeguards to gr.drawString
  code/scripting/api/libs/graphics.cpp
Labels: cleanup

#4314 Fix rollback primary collisions
  code/network/multi_obj.cpp
  code/network/multimsgs.cpp
Labels: fix, multi

#4306 De-Bitfield-y Player Orders
  code/ai/ailua.cpp
  code/hud/hudsquadmsg.cpp
  code/hud/hudsquadmsg.h
  code/mission/missionparse.cpp
  fred2/management.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, cleanup, multi, ai, HUD

#4264 Multi sexp fixes
  code/network/multi_sexp.cpp
  code/network/multi_sexp.h
  code/parse/sexp.cpp
Labels: multi, sexps

#4144 Interpolation Overhaul 2
  code/mission/missionparse.cpp
  code/network/multi_ingame.cpp
  code/network/multi_interpolate.cpp
  code/network/multi_interpolate.h
  code/network/multi_obj.cpp
  code/network/multi_obj.h
  code/network/multi_respawn.cpp
  code/network/multi_time_manager.cpp
  code/network/multi_time_manager.h
  code/network/multimsgs.cpp
  code/object/collideshipship.cpp
  code/object/object.cpp
  code/object/object.h
  code/ship/ship.cpp
  code/source_groups.cmake
  freespace2/freespace.cpp
Labels: enhancement, fix, multi

#4349 Multi Bump for 22.2 release
  code/network/multi.h
Labels: enhancement, multi

#4316 Cached subsystem indexing
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aiturret.cpp
  code/hud/hudsquadmsg.cpp
  code/network/multi_obj.cpp
  code/network/multimsgs.cpp
  code/parse/sexp.cpp
  code/scripting/api/objs/order.cpp
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/ship_flags.h
  code/ship/shiphit.cpp
  fred2/fredview.cpp
  fred2/shipgoalsdlg.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/dialogs/ShipGoalsDialogModel.cpp
Labels: enhancement, cleanup

#4330 Detect concurrent container modification
  code/parse/sexp.cpp
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
Labels: fix, sexps

#4133 Controls6: Keyboard Localization and Scripted Contols
  code/cmdline/cmdline.cpp
  code/controlconfig/controlsconfig.cpp
  code/controlconfig/controlsconfig.h
  code/controlconfig/controlsconfigcommon.cpp
  code/controlconfig/presets.cpp
  code/controlconfig/presets.h
  code/debugconsole/console.cpp
  code/io/joy-sdl.cpp
  code/io/joy.h
  code/io/key.cpp
  code/io/key.h
  code/io/keycontrol.cpp
  code/io/keycontrol.h
  code/io/mouse.h
  code/mission/missionhotkey.cpp
  code/mission/missionload.cpp
  code/pilotfile/plr.cpp
  code/playerman/playercontrol.cpp
  code/scripting/api/libs/controls.cpp
  code/scripting/api/libs/controls.h
  code/scripting/api/objs/control_binding.cpp
  code/scripting/api/objs/control_binding.h
  code/scripting/lua.cpp
  code/source_groups.cmake
  code/ui/inputbox.cpp
  code/ui/ui.h
Labels: cleanup, controls, scripting, refactor, localization / translation

#3769 Implemented debug sphere queuing and rendering.
  code/graphics/debug_sphere.cpp
  code/graphics/debug_sphere.h
  code/source_groups.cmake
  freespace2/freespace.cpp
Labels: enhancement

#4357 additional checks for FS1 message conversion
  code/mission/missionmessage.cpp
Labels: fix

#4307 tweak strdup handling for argument vector
  code/parse/sexp.cpp
Labels: cleanup

#4358 add additional XSTR entries
  code/hud/hudreticle.cpp
  code/localization/localize.cpp
Labels: fix, localization / translation

#4354 save PXO stats to local pilot file
  code/network/multi_fstracker.cpp
  code/pilotfile/pilotfile.cpp
  code/pilotfile/pilotfile.h
Labels: fix, multi

#4359 Small fix for music initialization
  code/gamesnd/eventmusic.cpp
Labels: fix, sound

#4360 Correct some Bad Documentation
  code/cfile/cfile.cpp
Labels: cleanup, documentation

#4355 Convert some Lua hooks to the new style to add documentation
  code/asteroid/asteroid.cpp
  code/object/collidedebrisship.cpp
  code/object/collideshipship.cpp
  code/object/collideshipweapon.cpp
  code/scripting/global_hooks.cpp
  code/scripting/global_hooks.h
  code/scripting/hook_api.cpp
  code/scripting/hook_api.h
  code/scripting/scripting.cpp
  code/scripting/scripting.h
  code/ship/ship.cpp
  code/ship/shiphit.cpp
  code/source_groups.cmake
  code/weapon/beam.cpp
  fred2/management.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/management.cpp
Labels: enhancement, scripting

#4368 Use correct call signature for subprocess.check_output
  ci/post/main.py
Labels: fix, ci

#4371 Check string, not number in release version regex
  ci/post/main.py
Labels: cleanup, fix

#4375 Ensure legacy order for HUD commands
  code/hud/hudsquadmsg.cpp
  code/hud/hudsquadmsg.h
Labels: fix, HUD

#4377 re-enable mod-only controls that have a tab.
  code/controlconfig/controlsconfigcommon.cpp
Labels: fix, controls

#4379 Fix FRED Crash with Team Colors
  code/ship/ship.cpp
Labels: fix, fred

#4363 Clean up list modifier code
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
Labels: cleanup, fix, sexps

#4376 disable compilation warnings in BitOp
  code/CMakeLists.txt
Labels: fix, build

#4389 Remove a pointless assert
  code/parse/sexp.cpp
Labels: cleanup, sexps

#4391 fix use of default tech database flags
  code/menuui/techmenu.cpp
  code/menuui/techmenu.h
  code/ship/ship_flags.h
  code/weapon/weapon_flags.h
Labels: fix

#4406 Properly set rotation data from LuaAI
  code/ai/ai.h
  code/ai/aicode.cpp
  code/scripting/api/objs/ai_helper.cpp
Labels: fix, ai, scripting

#4392 Disallow using Replace Container Data with special argument list
  code/parse/sexp_container.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, sexps

#4399 Handle weapons-locked slots that aren't ship-locked in selection screens.
  code/missionui/missionshipchoice.cpp
Labels: fix, interface

#4380 Changelog.py improvements and post-release-build.yaml debugging
  .github/workflows/post-build-release.yaml
  ci/post/changelog.py
Labels: fix, ci

#4404 Fix the standalone ship being added to ship list
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/network/multiutil.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: fix, discussion, multi

#4403 some tweaks to the FRED error checking
  fred2/fredview.cpp
  qtfred/src/mission/Editor.cpp
Labels: cleanup, qtfred, fred

#4414 split subsystem warning display checks
  code/model/modelread.cpp
Labels: cleanup

#4417 Update `ai_turn_towards_vector` to use a target vel for banking
  code/ai/aicode.cpp
  code/math/vecmat.cpp
Labels: ai, physics

#4410 Fix issues with loading of hud config presets
  code/cfile/cfile.cpp
  code/cfile/cfilesystem.cpp
Labels: fix, discussion, HUD

#4422 Followup improvement for the LuaAI AI Control Helper
  code/ai/ai.h
  code/ai/aicode.cpp
  code/scripting/api/objs/ai_helper.cpp
Labels: fix, ai, scripting

#4413 end the campaign properly when a mission is skipped
  code/mission/missioncampaign.cpp
  code/missionui/missionbrief.cpp
Labels: fix

#4420 only display one popup when the player gets to the main hall
  code/menuui/mainhallmenu.cpp
  code/menuui/playermenu.cpp
  code/menuui/playermenu.h
Labels: cleanup, interface

#4423 fix parsing issues with hud color presets
  code/hud/hudconfig.cpp
Labels: fix, HUD

#4424 fix control chars test that also excluded space key
  code/ui/inputbox.cpp
Labels: fix

#4425 Autotrigger on either workflow_call or push event.
  .github/workflows/post-build-release.yaml
Labels: fix, ci

#4426 Flush the mouse state after toggling between Use_mouse_to_fly states
  code/scripting/api/libs/controls.cpp
Labels: fix, controls, scripting

#4428 more fixes for the skip-training-mission crash
  code/mission/missioncampaign.cpp
Labels: fix

#4431 fix clearing a skybox model when it isn't the mission default
  code/parse/sexp.cpp
  code/starfield/starfield.cpp
Labels: cleanup, fix, sexps

#4436 Fixes Team Colors not working with `show-ship`
  code/ship/ship.cpp
Labels: fix, graphics

#4437 fix crash when removing form-on-wing
  code/ai/aigoals.cpp
Labels: fix, ai, sexps

#4440 better handling of invalid message sources
  code/parse/sexp.cpp
Labels: cleanup, fix

#4439 Use correct needs elements for post build action
  .github/workflows/build-release.yaml
Labels: fix, build

#4446 Fix Seg Fault on Standalones with Safer Check for Secondaries
  code/io/keycontrol.cpp
Labels: fix, multi

#4447 even more fixes for the skip-training-mission crash
  code/mission/missioncampaign.cpp
Labels: fix

#4451 Fix AI Goal Display Strings
  code/ship/ship.cpp
Labels: fix, HUD

#4452 set up debug_filter.cfg to have default filters that can be turned off
  code/osapi/outwnd.cpp
Labels: enhancement

#4448 add some logging to waitAsync
  code/osapi/outwnd.cpp
  code/scripting/api/LuaPromise.cpp
  code/scripting/api/libs/async.cpp
  code/scripting/api/libs/mission.cpp
Labels: cleanup

#4407 A comprehensive fix for the `player.target_is_dying` variable.
  code/hud/hud.cpp
  code/hud/hudbrackets.cpp
  code/hud/hudlock.cpp
  code/hud/hudtarget.cpp
  code/playerman/playercontrol.cpp
Labels: fix, HUD

#4434 sync Orientation virtvars
  code/scripting/api/objs/modelinstance.cpp
  code/scripting/api/objs/subsystem.cpp
Labels: cleanup

#4456 Small clarity edit to getTurretHeading() docs
  code/scripting/api/objs/subsystem.cpp
Labels: documentation
