Repository scp-fs2open/fs2open.github.com, pull requests merged in 2022-05, with the labels that each got.

#4020 Implement Replace Data for Number and String in qtFRED
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: qtfred, required feature

#4222 Model code cleanup #1
  code/model/model.h
  code/model/modelcollide.cpp
  code/model/modelinterp.cpp
  code/model/modeloctant.cpp
  code/model/modelread.cpp
  code/model/modelsinc.h
Labels: cleanup

#4212 patch the freeing of SEXP nodes
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/campaigntreeview.cpp
Labels: cleanup, fix

#4234 Encapsulate testing for LoS in a function and expose to Lua
  code/ai/ai.h
  code/ai/aicode.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/lua/LuaValue.h
Labels: scripting

#4235 Add Subsystem Flag to Hide Turrets from Ship Loadout Stats
  code/missionui/missionshipchoice.cpp
  code/model/model_flags.h
  code/ship/ship.cpp
Labels: enhancement

#4225 Make the "$Player Weapon Precedence:" list actually give precedence.
  code/missionui/missionweaponchoice.cpp
Labels: enhancement, cleanup

#3852 SEXP containers, Part 6: FRED/qtFRED SEXP trees
  code/mission/missioncampaign.h
  code/missionui/missiondebrief.cpp
  code/parse/sexp.cpp
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
  fred2/addmodifycontainerdlg.cpp
  fred2/addmodifycontainerdlg.h
  fred2/fred.rc
  fred2/res/container_data.bmp
  fred2/res/container_name.bmp
  fred2/resource.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  freespace2/freespace.cpp
  qtfred/resources/images/container_data.png
  qtfred/resources/images/container_name.png
  qtfred/resources/resources.qrc
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: enhancement, qtfred, sexps, fred, feature

#4186 background bitmap fix
  code/globalincs/pstypes.h
  code/lab/renderer/lab_renderer.cpp
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/scripting/api/libs/mission.cpp
  code/source_groups.cmake
  code/starfield/starfield.cpp
  code/starfield/starfield.h
  code/starfield/starfield_flags.h
  fred2/bgbitmapdlg.cpp
  fred2/bgbitmapdlg.h
  fred2/fred.rc
  fred2/missionsave.cpp
  fred2/resource.h
  fred2/sexp_tree.cpp
  qtfred/src/mission/missionsave.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, qtfred, fred

#4239 fix two bugs associated with custom tech databases
  code/menuui/readyroom.cpp
  code/menuui/techmenu.cpp
  code/scripting/api/objs/player.cpp
Labels: regression, fix, gameplay, pilot file

#4243 disable Enter and Escape in the container dialog
  fred2/addmodifycontainerdlg.cpp
  fred2/addmodifycontainerdlg.h
  fred2/fred.rc
Labels: enhancement, fix, fred

#4245 Fix background sun positioning as well
  code/starfield/starfield.cpp
Labels: fix, graphics

#4232 add some UX guards to the briefing editor icons
  code/mission/missionbriefcommon.cpp
  code/mission/missionbriefcommon.h
  fred2/briefingeditordlg.cpp
  fred2/briefingeditordlg.h
Labels: fix, fred

#3861 SEXP containers, Part 7: Status SEXPs
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
Labels: enhancement, sexps, feature

#4246 Fix memory leak and use tmap verts directly
  code/model/modelcollide.cpp
  code/model/modelinterp.cpp
  code/model/modeloctant.cpp
  code/model/modelread.cpp
Labels: fix

#3862 SEXP containers, Part 8: Change SEXPs
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
Labels: enhancement, sexps, feature

#4247 Implement query_modified() for Add/Modify Container FRED dialog
  fred2/addmodifycontainerdlg.cpp
  fred2/addmodifycontainerdlg.h
Labels: fix, fred

#4252 use the proper time for the newly added timestamps
  code/io/timer.cpp
Labels: fix

#4250 assign cues when a ship is ship-created
  code/ship/ship.cpp
Labels: fix, sexps

#4242 clean up some parse problems in FRED
  fred2/management.cpp
  qtfred/src/mission/Editor.cpp
Labels: cleanup, qtfred, fred

#4253 keep default identity orientation when host flag is active
  code/camera/camera.cpp
Labels: fix

#4256 partial revert of targeting distance ranking change
  code/hud/hudtarget.cpp
Labels: regression, fix

#4255 Fix clear-container SEXP
  code/parse/sexp.cpp
  code/parse/sexp_container.cpp
Labels: enhancement, fix, sexps

#4249 fix assignment of alt-name when using the hash
  code/parse/sexp.cpp
Labels: regression, fix, sexps

#4260 revised disabling of Enter and Escape
  fred2/addmodifycontainerdlg.cpp
Labels: fix, fred

#4209 Limit all MP client collisions to prevent bugs
  code/object/collideshipship.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: fix, multi, physics

#4159 guard against off-by-one errors in replace_one and replace_all
  code/mission/missionmessage.cpp
  code/mission/missionparse.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/parse/sexp.cpp
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
  code/scripting/api/objs/message.cpp
  fred2/bgbitmapdlg.cpp
  fred2/briefingeditordlg.cpp
  fred2/campaigneditordlg.cpp
  fred2/campaigntreewnd.cpp
  fred2/cmdbrief.cpp
  fred2/debriefingeditordlg.cpp
  fred2/management.cpp
  fred2/management.h
  fred2/missiongoalsdlg.cpp
  fred2/missionnotesdlg.cpp
  fred2/missionsave.cpp
  fred2/orienteditor.cpp
  fred2/shipeditordlg.cpp
  fred2/voiceactingmanager.cpp
  fred2/waypointpathdlg.cpp
  fred2/wing_editor.cpp
  qtfred/src/mission/missionsave.cpp
  test/src/parse/test_replace.cpp
  test/src/source_groups.cmake
Labels: cleanup, fix

#4262 miscellaneous fixes related to old Coverity fixes
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/object/objectsnd.cpp
  code/scripting/api/objs/cockpit_display.cpp
  code/scripting/doc_html.cpp
Labels: cleanup, fix

#4261 disable sun bank controls
  fred2/bgbitmapdlg.cpp
Labels: cleanup, fred

#4258 Correct sun position compensation math
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  code/scripting/api/libs/mission.cpp
  code/starfield/starfield.cpp
  code/starfield/starfield.h
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: fix, graphics

#4263 Replace "Always_show_goals" with "Toggle_showing_goals"
  code/mission/mission_flags.h
  code/missionui/missionbrief.cpp
  fred2/fred.rc
  fred2/missionnotesdlg.cpp
  fred2/missionnotesdlg.h
  fred2/resource.h
  qtfred/src/ui/dialogs/MissionSpecDialog.cpp
  qtfred/ui/MissionSpecDialog.ui
Labels: enhancement, qtfred, fred

#4265 fix a standalone crash from disabled uniform buffer manager
  code/graphics/2d.cpp
Labels: fix, multi

#4268 some wing wave cleanup
  code/ai/aigoals.cpp
  code/ship/ship.h
Labels: cleanup

#4271 fix maybePlayCutscene arguments
  code/scripting/api/libs/ui.cpp
Labels: fix, scripting

#4267 Add cancel-future-waves
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, sexps

#4257 Ensure Replace/Add String and (Add) Paste are disabled for container name nodes
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, qtfred, fred

#4198 LuaAI
  code/ai/ai.h
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aigoals.h
  code/ai/ailua.cpp
  code/ai/ailua.h
  code/hud/hudsquadmsg.cpp
  code/hud/hudsquadmsg.h
  code/parse/sexp.cpp
  code/parse/sexp/LuaAISEXP.cpp
  code/parse/sexp/LuaAISEXP.h
  code/parse/sexp/LuaSEXP.cpp
  code/parse/sexp/LuaSEXP.h
  code/parse/sexp/sexp_lookup.cpp
  code/parse/sexp/sexp_lookup.h
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/ai_helper.cpp
  code/scripting/api/objs/ai_helper.h
  code/scripting/api/objs/luaaisexp.cpp
  code/scripting/api/objs/luaaisexp.h
  code/ship/ship.cpp
  code/source_groups.cmake
  fred2/management.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/management.cpp
Labels: ai, scripting, feature

#4233 Add TBL Viewer
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/ShipTBLViewerModel.cpp
  qtfred/src/mission/dialogs/ShipTBLViewerModel.h
  qtfred/src/ui/dialogs/ShipEditorDialog.cpp
  qtfred/src/ui/dialogs/ShipEditorDialog.h
  qtfred/src/ui/dialogs/ShipTBLViewer.cpp
  qtfred/src/ui/dialogs/ShipTBLViewer.h
  qtfred/ui/ShipTBLViewer.ui
Labels: qtfred, required feature

#4280 add improvements to aid in multi troubleshooting
  code/cmdline/cmdline.cpp
  code/network/multi_log.cpp
  code/network/multi_options.cpp
  code/osapi/dialogs.cpp
Labels: multi

#4266 address multiple timestamp issues with multi
  code/io/timer.cpp
  code/io/timer.h
  code/network/multi.cpp
  code/network/multi.h
  code/network/multi_fstracker.cpp
  code/network/multi_ingame.cpp
  code/network/multi_kick.cpp
  code/network/multi_observer.cpp
  code/network/multi_options.cpp
  code/network/multi_pmsg.cpp
  code/network/multi_pxo.cpp
  code/network/multi_respawn.cpp
  code/network/multi_voice.cpp
  code/network/multi_xfer.cpp
  code/network/multimsgs.cpp
  code/network/multiui.cpp
  code/network/multiutil.cpp
  code/object/collideshipship.cpp
  freespace2/freespace.cpp
Labels: fix, multi

#4281 Enable Doxygen for QTFred
  cmake/doxygen.cmake
Labels: build, documentation

#4279 Lab Environment-Map Export
  code/def_files/data/effects/envmap-sphere-warp-f.sdr
  code/graphics/2d.h
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropenglshader.cpp
  code/lab/manager/lab_manager.cpp
  code/lab/renderer/lab_renderer.cpp
  code/lab/renderer/lab_renderer.h
  code/source_groups.cmake
Labels: enhancement, graphics

#4282 Replace +Orders Accepted: Bitfield with flag list
  code/mission/missionparse.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: cleanup, ai

#4275 Allow SCPUI to run `$On Briefing Stage:` hooks
  code/scripting/api/libs/ui.cpp
Labels: ui, scripting

#4273 resolve FIXME for AIM_GET_BEHIND
  code/ai/ai.h
  code/ai/aicode.cpp
Labels: cleanup

#4277 add hu.getTargetDistance()
  code/scripting/api/libs/hud.cpp
Labels: enhancement, scripting

#4283 Fix HUD squad menu PageDown
  code/hud/hudsquadmsg.cpp
Labels: fix, ui

#4289 briefing icon behavior tweaks per request
  fred2/briefingeditordlg.cpp
  fred2/briefingeditordlg.h
Labels: fred

#4291 Add copy-container SEXP
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp_container.cpp
Labels: enhancement, sexps

#4301 Fix FRED Add/Replace
  fred2/fred.rc
  fred2/sexp_tree.cpp
Labels: fix, fred

#4303 Activate LuaAI custom message parsing
  code/parse/sexp/LuaAISEXP.cpp
Labels: enhancement, ai

#4310 Fix +Orders Accepted List: parse
  code/mission/missionparse.cpp
Labels: fix

#4299 Add container name subtype to Sexp_nodes
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
  fred2/addmodifycontainerdlg.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: cleanup, fix, qtfred, sexps, fred

#4312 Fix Orders Accepted List properly
  code/mission/missionparse.cpp
Labels: fix

#4296 Add for-* SEXPs for containers
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
Labels: enhancement, sexps

#4320 fix NAME_LENGTH discrepancy
  code/ship/ship.cpp
Labels: fix

#4304 Add LuaAI validity callbacks
  code/ai/aigoals.cpp
  code/ai/aigoals.h
  code/ai/ailua.cpp
  code/ai/ailua.h
  code/parse/sexp/LuaAISEXP.cpp
  code/parse/sexp/LuaAISEXP.h
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/enums.h
  code/scripting/api/objs/luaaisexp.cpp
Labels: enhancement, ai

#4318 use proper buffer size for PXO chat line
  code/network/multi_pxo.cpp
Labels: fix, multi

#4308 Handle deprecated cmdline flags programmatically.
  code/cmdline/cmdline.cpp
Labels: cleanup, refactor

#4313 Allow Weapon To Override Turret Name
  code/hud/hudtargetbox.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement

#4286 add timestamp_since
  code/ai/aiturret.cpp
  code/io/cursor.cpp
  code/io/timer.cpp
  code/io/timer.h
  code/ship/ship.cpp
Labels: enhancement

#4322 Fix is_for_op() to follow existing conventions
  code/parse/sexp.cpp
Labels: cleanup, sexps

#4290 Make number of player orders FRED can handle dynamic
  fred2/fred.rc
  fred2/ignoreordersdlg.cpp
  fred2/ignoreordersdlg.h
  fred2/resource.h
Labels: ai, fred

#4328 Remove pointless assertion in mission parsing.
  code/mission/missionparse.cpp
Labels: fix

#4324 timestamp comparisons
  code/io/timer.cpp
  code/io/timer.h
Labels: enhancement
