Repository scp-fs2open/fs2open.github.com, pull requests merged in 2022-04, with the labels that each got.

#4125 21.0-22.0 changelog
  Changelog.md
Labels: build

#4124 bump version to 22.1.x
  cmake/version.cmake
Labels: build

#4123 Make sure that zero-length strings still get the proper height; fixes missing whitespace in the credits
  code/graphics/software/VFNTFont.cpp
  code/graphics/software/font.cpp
Labels: fix

#4062 add missile list iterator
  code/scripting/api/libs/mission.cpp
Labels: enhancement, scripting, Waiting for Stable

#4056 add capability (plus sexps) to set navpoint color
  code/autopilot/autopilot.cpp
  code/autopilot/autopilot.h
  code/hud/hudnavigation.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, sexps, Waiting for Stable

#4096 enhance help text for Lua sexps
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/parse/sexp/LuaSEXP.cpp
  code/parse/sexp/LuaSEXP.h
Labels: enhancement, qtfred, sexps, fred, scripting, Waiting for Stable

#4085 add campaign start hook
  code/menuui/readyroom.cpp
  code/menuui/readyroom.h
  code/playerman/managepilot.cpp
  code/scripting/api/objs/player.cpp
Labels: scripting, Waiting for Stable, feature

#4118 add a class encapsulation for Volition's linked list
  code/globalincs/linklist.h
Labels: Waiting for Stable, feature

#3960 add scripting support for decals
  code/decals/decals.cpp
  code/decals/decals.h
  code/scripting/api/libs/tables.cpp
  code/scripting/api/objs/decaldefinition.cpp
  code/scripting/api/objs/decaldefinition.h
  code/scripting/api/objs/model.cpp
  code/source_groups.cmake
Labels: enhancement, scripting, Waiting for Stable, feature

#4117 dynamic IFF list in the ship select editor
  fred2/fred.rc
  fred2/resource.h
  fred2/ship_select.cpp
  fred2/ship_select.h
Labels: enhancement, fred, Waiting for Stable

#4087 Add delay into ai_new_maybe_reposition_attack_subsys for performance
  code/ai/ai.h
  code/ai/aibig.cpp
  code/ai/aicode.cpp
Labels: enhancement, Waiting for Stable

#4136 follow-up to 4074
  code/menuui/playermenu.cpp
Labels: enhancement

#4135 address highlighting for events with background colors
  fred2/eventeditor.cpp
Labels: enhancement, fred

#4090 FRED Nebula background UI enhancements
  code/lab/renderer/lab_renderer.cpp
  code/mission/mission_flags.h
  code/mission/missionparse.cpp
  code/nebula/neb.cpp
  code/nebula/neb.h
  code/parse/sexp.cpp
  fred2/bgbitmapdlg.cpp
  fred2/bgbitmapdlg.h
  fred2/fred.rc
  fred2/missionsave.cpp
  fred2/resource.h
  freespace2/freespace.cpp
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, fred, Waiting for Stable

#4121 make HUD target distance consistent
  code/hud/hud.cpp
  code/hud/hudbrackets.cpp
  code/hud/hudtarget.cpp
Labels: cleanup, fix, Waiting for Stable

#4138 Fix destroyed submodels showing in Techroom
  code/model/modelread.cpp
Labels: fix, models

#4132 lua ship.checkVisibility mimicing sexp ship-is-visible
  code/parse/sexp.cpp
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement, scripting

#4084 Add 'pause on reverse' Animation Flag
  code/model/modelanimation.cpp
  code/model/modelanimation.h
Labels: enhancement, models

#4139 Fix techroom turret lookup and make animations more robust
  code/model/modelanimation.cpp
  code/model/modelanimation.h
Labels: fix, models

#4050 Feature/texture replacement dialog
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
  qtfred/src/mission/dialogs/ShipEditorDialogModel.h
  qtfred/src/mission/dialogs/ShipTextureReplacementDialogModel.cpp
  qtfred/src/mission/dialogs/ShipTextureReplacementDialogModel.h
  qtfred/src/ui/dialogs/ShipEditorDialog.cpp
  qtfred/src/ui/dialogs/ShipEditorDialog.h
  qtfred/src/ui/dialogs/ShipTextureReplacementDialog.cpp
  qtfred/src/ui/dialogs/ShipTextureReplacementDialog.h
  qtfred/ui/ShipTextureReplacementDialog.ui
Labels: enhancement, qtfred

#4134 Removed collide_remove_weapons from weapon_create
  code/weapon/weapons.cpp
Labels: cleanup

#4101 add flags to keep same warp effects when docked
  code/mission/mission_flags.h
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  code/ship/ship_flags.h
  code/ship/shipfx.cpp
  fred2/fred.rc
  fred2/missionsave.cpp
  fred2/resource.h
  fred2/shipeditordlg.cpp
  fred2/shipeditordlg.h
  fred2/wing_editor.cpp
  fred2/wing_editor.h
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, fred

#4093 add player loaded hook
  code/pilotfile/plr.cpp
  code/scripting/hook_api.h
Labels: scripting, feature

#4143 remove daisy-chained mission flag
  code/mission/mission_flags.h
  code/object/objectdock.cpp
  fred2/fred.rc
  fred2/missionnotesdlg.cpp
  fred2/missionnotesdlg.h
  fred2/resource.h
  qtfred/src/ui/dialogs/MissionSpecDialog.cpp
  qtfred/ui/MissionSpecDialog.ui
Labels: cleanup, fred

#4141 $AI ignores aspect lock for leading: AIP flag implemented
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aicode.cpp
Labels: enhancement, ai

#4145 Check for valid index before accessing Weapon_info
  code/ai/aicode.cpp
Labels: fix, ai

#4127 vectorize Soundtracks and Spooled_music
  code/gamesnd/eventmusic.cpp
  code/gamesnd/eventmusic.h
  code/mission/missionparse.cpp
  code/missionui/missionscreencommon.cpp
  code/parse/sexp.cpp
  fred2/FictionViewerDlg.cpp
  fred2/briefingeditordlg.cpp
  fred2/debriefingeditordlg.cpp
  fred2/missionnotesdlg.cpp
  fred2/sexp_tree.cpp
  qtfred/src/mission/dialogs/FictionViewerDialogModel.cpp
  qtfred/src/ui/dialogs/MissionSpecDialog.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: enhancement, cleanup

#4147 fix show-subtitle again
  code/parse/sexp.cpp
Labels: fix, sexps

#4111 Fred object orientation features
  fred2/CMakeLists.txt
  fred2/calcrelativecoordsdlg.cpp
  fred2/calcrelativecoordsdlg.h
  fred2/fred.cpp
  fred2/fred.rc
  fred2/fredview.cpp
  fred2/fredview.h
  fred2/orienteditor.cpp
  fred2/orienteditor.h
  fred2/resource.h
Labels: fred, feature

#4150 add an additional check to the convert-to-Command logic
  code/mission/missionmessage.cpp
Labels: cleanup

#4146 Add SEXP constants for containers
  code/parse/sexp.h
Labels: enhancement, sexps

#4153 refactor supernova code
  code/graphics/post_processing.cpp
  code/hud/hud.cpp
  code/mission/missioncampaign.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/parse/sexp.cpp
  code/starfield/starfield.cpp
  code/starfield/supernova.cpp
  code/starfield/supernova.h
  freespace2/freespace.cpp
Labels: enhancement, cleanup, fix

#4151 Fix cockpit engine sound volume changing unexpectedly
  code/hud/hud.cpp
Labels: fix, sound

#4156 upgrade supernova timestamps
  code/io/timer.cpp
  code/io/timer.h
  code/starfield/supernova.cpp
Labels: enhancement

#4155 Insertion sort update
  ci/linux/clang_tidy.sh
  code/ai/aigoals.cpp
  code/globalincs/systemvars.cpp
  code/globalincs/systemvars.h
  code/globalincs/windebug.cpp
  code/hud/hudtarget.cpp
  code/mission/missionmessage.cpp
  code/mission/missiontraining.cpp
  code/parse/sexp.cpp
Labels: enhancement, cleanup

#4157 add game_settings.tbl option to specify subtitle coords in pixels
  code/camera/camera.cpp
  code/camera/camera.h
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/parse/sexp.cpp
Labels: enhancement, HUD, sexps

#4162 prevent crashes in the event of a subsystem mismatch
  code/ship/ship.cpp
Labels: fix

#4126 Fix auto-trigger for post-release build workflow, Checkout passed release tag, Fix version string
  .github/CODEOWNERS
  .github/workflows/build-release.yaml
  .github/workflows/post-build-release.yaml
  ci/post/changelog.py
  ci/post/forum.py
  ci/post/github.py
  ci/post/main.py
Labels: fix, build, ci

#4169 add preload ability for mission-set-subspace
  code/parse/sexp.cpp
  code/starfield/starfield.cpp
  code/starfield/starfield.h
Labels: enhancement, sexps, models

#4167 Update PREBUILT_VERSION_NAME to latest (mac libs)
  lib/prebuilt.cmake
Labels: build

#4128 Switched light shader attenuation math to something that looks more real
  code/def_files/data/effects/deferred-f.sdr
Labels: enhancement, graphics

#4158 add the ability for subtitles to be scaled correctly to the screen
  code/camera/camera.cpp
  code/camera/camera.h
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/parse/sexp.cpp
  freespace2/freespace.cpp
Labels: enhancement, HUD, sexps

#4163 Increase POF vertex limit
  code/model/model.h
  code/model/modelcollide.cpp
  code/model/modelinterp.cpp
  code/model/modeloctant.cpp
  code/model/modelread.cpp
  code/model/modelsinc.h
  code/render/3d.h
  code/render/3ddraw.cpp
Labels: enhancement, refactor

#4175 Create commandline option for logging data packets
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
  code/network/multi.cpp
Labels: enhancement

#4177 various HUD gauge fixes
  code/hud/hud.cpp
  code/parse/sexp.cpp
Labels: fix

#4176 Disengage the sound limiters
  code/gamesnd/gamesnd.cpp
  code/sound/ds.cpp
  code/sound/ds.h
  code/sound/rtvoice.cpp
  code/sound/sound.cpp
  code/sound/sound.h
Labels: enhancement, sound

#4180 Log data packets2
  code/network/multi.cpp
Labels: enhancement, multi

#4172 add optional flag to not change subtitle aspect ratio
  code/camera/camera.cpp
  code/camera/camera.h
  code/parse/sexp.cpp
Labels: enhancement, HUD, sexps

#4189 Fix FRED accessibility of new flag `ai-attackable-if-no-collide`
  code/mission/missionparse.cpp
  code/object/object.cpp
  code/parse/sexp.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: fix, qtfred, fred

#4190 More Pof space optimizations
  code/model/modelcollide.cpp
  code/model/modelinterp.cpp
  code/model/modeloctant.cpp
  code/model/modelread.cpp
  code/model/modelsinc.h
  code/render/3ddraw.cpp
Labels: enhancement, cleanup

#4192 probably fix #4187
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
Labels: cleanup, fix

#4194 Fix FRED accessibility of new flag `ai-attackable-if-no-collide` V2
  code/object/object.h
Labels: fix, qtfred, fred

#4200 Don't treat a bare <argument> as an error.
  code/parse/sexp.cpp
Labels: regression, fix

#4201 Delay processing "$Player Weapon Precedence:" until after parsing.
  code/missionui/missionweaponchoice.cpp
  code/ship/ship.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: fix

#4191 Random chance of particle spawning
  code/particle/effects/GenericShapeEffect.h
  code/particle/effects/VolumeEffect.cpp
  code/particle/effects/VolumeEffect.h
Labels: enhancement, particles

#4203 Add a ship flag to allow the firing fail sound to play with locked primaries
  code/mission/mission_flags.h
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/ship_flags.h
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, sound

#4206 add some script functions for HUD gauge data
  code/hud/hud.cpp
  code/hud/hud.h
  code/hud/hudparse.cpp
  code/hud/hudparse.h
  code/scripting/api/objs/font.cpp
  code/scripting/api/objs/hudgauge.cpp
Labels: fix, HUD, scripting, feature

#3737 Remove light filtering data
  code/lighting/lighting.cpp
  code/lighting/lighting.h
  code/model/modelrender.cpp
  code/model/modelrender.h
  code/object/object.cpp
  code/weapon/beam.cpp
Labels: cleanup, graphics

#3607 Reinforcements Dialog
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/ReinforcementsEditorDialogModel.cpp
  qtfred/src/mission/dialogs/ReinforcementsEditorDialogModel.h
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
  qtfred/src/ui/dialogs/ReinforcementsEditorDialog.cpp
  qtfred/src/ui/dialogs/ReinforcementsEditorDialog.h
  qtfred/ui/ReinforcementsDialog.ui
Labels: qtfred, required feature

#4207 Fix Texture Replace and Team Colors with Ship Changes
  code/ship/ship.cpp
Labels: fix, models

#4217 Always record primary bank ammo capacity during ship creation.
  code/ship/ship.cpp
Labels: fix

#4211 Beam light cleanup
  code/weapon/beam.cpp
Labels: cleanup

#4216 Fix RTT Cockpits Gauges with Change Ship Class
  code/parse/sexp.cpp
  code/scripting/api/objs/ship.cpp
Labels: fix, HUD

#3490 SEXP containers, Part 4: Text replacement
  code/camera/camera.cpp
  code/mission/missionmessage.cpp
  code/mission/missiontraining.cpp
  code/missionui/missionbrief.cpp
  code/missionui/missioncmdbrief.cpp
  code/missionui/missiondebrief.cpp
  code/parse/sexp.cpp
  code/parse/sexp_container.cpp
  code/parse/sexp_container.h
  code/scripting/api/objs/message.cpp
Labels: enhancement, gameplay, HUD, sexps, scripting, interface, feature

#4215 Early return instead of assert on 0 or less sized hud brackets
  code/hud/hudbrackets.cpp
  code/hud/hudbrackets.h
Labels: graphics, refactor

#4205 Move of special parsing functions out of lighting_profiles into new file
  code/lighting/lighting_profiles.cpp
  code/parse/parsehi.cpp
  code/parse/parsehi.h
  code/source_groups.cmake
Labels: cleanup

#4223 Actually clear delayed SSM parsing data when it's no longer needed.
  code/weapon/weapons.cpp
Labels: cleanup, refactor

#4213 add a script function to flash parts of the target box
  code/globalincs/scp_defines.h
  code/parse/sexp.cpp
  code/scripting/api/libs/hud.cpp
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/enums.h
Labels: HUD, scripting

#4221 Avoid setting .rest for Locked_sexp_true/false with malformed SEXPs.
  code/parse/sexp.cpp
Labels: fix, sexps

#4218 make variable list parsing a little more robust
  code/parse/sexp.cpp
Labels: fix

#4231 fix up conditions for script hooks
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aiturret.cpp
  code/controlconfig/controlsconfig.cpp
  code/object/collidedebrisship.cpp
  code/object/collidedebrisweapon.cpp
  code/object/collideshipship.cpp
  code/object/collideshipweapon.cpp
  code/object/collideweaponweapon.cpp
  code/scripting/hook_api.h
  code/scripting/scripting.cpp
  code/scripting/scripting.h
  code/ship/ship.cpp
  code/weapon/beam.cpp
  code/weapon/weapons.cpp
  freespace2/freespace.cpp
Labels: fix, scripting

#4224 Allow an unlimited number of ship flags to be parsed at once.
  code/ship/ship.cpp
Labels: enhancement, cleanup
