Repository scp-fs2open/fs2open.github.com, pull requests merged in 2023-05, with the labels that each got.

#5377 remove some obsolete FRED components
  fred2/CMakeLists.txt
  fred2/dialog1.cpp
  fred2/dialog1.h
  fred2/folderdlg.cpp
  fred2/folderdlg.h
  fred2/freddoc.cpp
  fred2/mainfrm.cpp
  fred2/mainfrm.h
  fred2/resource.h
Labels: cleanup, fred

#5389 clear caches for both nodes in rand_sexp
  code/parse/sexp.cpp
Labels: cleanup, regression, fix, sexps

#5386 Warn instead of error for bitmap fonts in unicode
  code/graphics/software/font.cpp
Labels: cleanup

#5375 Modernise CFLAGS on Mac/Linux
  cmake/toolchain-apple-clang.cmake
  cmake/toolchain-clang.cmake
  cmake/toolchain-gcc.cmake
  code/fireball/fireballs.cpp
  code/fireball/warpineffect.cpp
  code/gamesnd/eventmusic.cpp
  code/globalincs/systemvars.cpp
  code/graphics/2d.cpp
  code/graphics/opengl/gropengltexture.cpp
  code/graphics/post_processing.cpp
  code/io/mouse.cpp
  code/jpgutils/jpgutils.cpp
  code/mission/missionbriefcommon.cpp
  code/mod_table/mod_table.cpp
  code/nebula/neb.cpp
  code/sound/sound.cpp
  code/weapon/shockwave.cpp
  freespace2/freespace.cpp
Labels: cleanup, build

#5373 Remove model octants
  code/ai/aibig.cpp
  code/model/model.h
  code/model/modelcollide.cpp
  code/model/modelinterp.cpp
  code/model/modeloctant.cpp
  code/model/modelread.cpp
  code/model/modelsinc.h
  code/source_groups.cmake
  code/tracing/categories.cpp
  code/tracing/categories.h
  code/weapon/beam.cpp
Labels: cleanup, fix, models

#5379 Some additional splash screen features
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  freespace2/freespace.cpp
Labels: enhancement

#5388 Fix HDR conversions in main shader
  code/def_files/data/effects/main-f.sdr
Labels: fix, graphics

#5392 Collision fix for weapons with lots of inherited velocity
  code/object/collideshipweapon.cpp
Labels: fix

#5391 make number parsing a little more forgiving
  code/parse/parselo.cpp
Labels: cleanup

#5394 Add additional checks for Animation List handling of nonexistent polymodel instances
  code/model/modelanimation.cpp
Labels: fix, models

#5396 Fix two undocking bugs for small ships
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
Labels: fix, ai

#5398 update type_flags when dock name changes
  code/model/modelreplace.cpp
Labels: fix, models

#5347 lighting profile code reorg
  code/globalincs/adjustment.cpp
  code/globalincs/adjustment.h
  code/graphics/light.cpp
  code/graphics/opengl/gropengldeferred.cpp
  code/graphics/opengl/gropenglpostprocessing.cpp
  code/lab/dialogs/lab_ui.cpp
  code/lab/dialogs/lab_ui_helpers.cpp
  code/lab/manager/lab_manager.cpp
  code/lab/renderer/lab_renderer.cpp
  code/lab/renderer/lab_renderer.h
  code/lighting/lighting.cpp
  code/lighting/lighting_profiles.cpp
  code/lighting/lighting_profiles.h
  code/object/object.cpp
  code/source_groups.cmake
  code/weapon/beam.cpp
  freespace2/freespace.cpp
Labels: cleanup

#5400 MSAA
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
  code/def_files/data/effects/copy-f.sdr
  code/def_files/data/effects/msaa-f.sdr
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/graphics/opengl/gropengldeferred.cpp
  code/graphics/opengl/gropengldraw.cpp
  code/graphics/opengl/gropengldraw.h
  code/graphics/opengl/gropenglshader.cpp
  code/graphics/opengl/gropenglstate.cpp
  code/graphics/opengl/gropenglstate.h
  code/graphics/opengl/gropengltnl.cpp
  code/graphics/util/uniform_structs.h
  code/ship/ship.cpp
  code/source_groups.cmake
Labels: graphics, feature, opengl

#5397 add ship:isPlayer()
  code/parse/sexp.cpp
  code/scripting/api/objs/parse_object.cpp
  code/scripting/api/objs/ship.cpp
Labels: enhancement, scripting

#5408 Ensure curves are initialized in FRED
  fred2/management.cpp
Labels: fix

#5404 Traitor overrides feature
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/missionui/missiondebrief.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/stats/scoring.cpp
  code/stats/scoring.h
  fred2/management.cpp
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/mission/management.cpp
  qtfred/src/mission/management.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: enhancement, general modding

#5410 fix qtFRED initialization
  qtfred/src/main.cpp
  qtfred/src/mission/Editor.cpp
Labels: fix, qtfred

#5380 Ltp/multiple profiles
  code/globalincs/adjustment.cpp
  code/globalincs/adjustment.h
  code/lab/dialogs/lab_ui.cpp
  code/lab/renderer/lab_renderer.cpp
  code/lighting/lighting_profiles.cpp
  code/lighting/lighting_profiles.h
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  fred2/bgbitmapdlg.cpp
  fred2/bgbitmapdlg.h
  fred2/fred.rc
  fred2/management.cpp
  fred2/missionsave.cpp
  fred2/resource.h
  fred2/weaponeditordlg.cpp
  qtfred/src/ui/dialogs/MissionSpecDialog.h
Labels: graphics, feature, Requested by Active Mod

#5409 some cleanup and refactoring
  code/globalincs/globals.h
  code/globalincs/pstypes.h
  code/globalincs/systemvars.cpp
  code/globalincs/vmallocator.h
  code/mission/missionmessage.cpp
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/model/modelanimation.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/parse/sexp.cpp
  code/ship/ship.cpp
  fred2/freddoc.cpp
Labels: cleanup, fred

#5414 fix evaluation of event status for some events
  code/parse/sexp.cpp
Labels: fix, timer/timestamp

#5406 Add player damage inflicted factor
  code/ai/ai_profiles.cpp
  code/ai/ai_profiles.h
  code/def_files/ai_profiles.tbl
  code/ship/shiphit.cpp
Labels: enhancement, gameplay

#5415 add lcase_equal and lcase_lessthan
  code/globalincs/systemvars.cpp
  code/globalincs/vmallocator.h
  code/math/curve.cpp
  code/model/modelreplace.cpp
  code/nebula/neb.cpp
  code/parse/sexp.cpp
  code/parse/sexp/LuaSEXP.cpp
  code/parse/sexp/sexp_lookup.cpp
  code/scripting/hook_conditions.cpp
  code/scripting/lua.cpp
  code/starfield/starfield.cpp
  code/stats/scoring.cpp
  fred2/eventeditor.cpp
  fred2/missiongoalsdlg.cpp
  fred2/musicplayerdlg.cpp
  qtfred/src/mission/dialogs/MissionGoalsDialogModel.cpp
  qtfred/src/ui/dialogs/EventEditorDialog.cpp
Labels: cleanup, refactor

#5417 fix #5416 by loading correct table filenames and ensuring tonemapper …
  code/lighting/lighting_profiles.cpp
Labels: fix, graphics

#5412 Use volume particles for poofs
  code/nebula/neb.cpp
  code/render/batching.cpp
  code/render/batching.h
Labels: enhancement, graphics

#5411 add support for loose lz4 compressed files
  code/cfile/cfilesystem.cpp
Labels: enhancement, general modding

#5424 patch qtFRED's handling of hud gauges
  qtfred/src/main.cpp
  qtfred/src/mission/management.cpp
  qtfred/src/mission/management.h
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, qtfred

#5425 add hooks for comm menu opening and closing
  code/hud/hudsquadmsg.cpp
  code/scripting/global_hooks.cpp
  code/scripting/global_hooks.h
Labels: enhancement, HUD, scripting

#5419 Fix asteroid wrapping
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
  code/io/keycontrol.cpp
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  fred2/asteroideditordlg.cpp
  fred2/asteroideditordlg.h
  fred2/fred.rc
  fred2/missionsave.cpp
  fred2/resource.h
  qtfred/src/mission/dialogs/AsteroidEditorDialogModel.cpp
  qtfred/src/mission/dialogs/AsteroidEditorDialogModel.h
  qtfred/src/mission/missionsave.cpp
  qtfred/src/ui/dialogs/AsteroidEditorDialog.cpp
  qtfred/src/ui/dialogs/AsteroidEditorDialog.h
  qtfred/ui/AsteroidEditorDialog.ui
Labels: enhancement, fix

#5429 Allow using container data with ai-waypoints* SEXPs
  code/ai/aigoals.cpp
Labels: fix, ai, sexps

#5426 All poofs on by default
  code/mission/missionparse.cpp
Labels: regression, fix

#5421 Virtual POFs: Modify Subsystems
  code/model/modelreplace.cpp
  code/model/modelreplace.h
Labels: enhancement, models
