Repository scp-fs2open/fs2open.github.com, pull requests merged in 2023-01, with the labels that each got.

#5050 add should-be-dead checks for object iterations
  code/ai/aibig.cpp
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aiturret.cpp
  code/asteroid/asteroid.cpp
  code/autopilot/autopilot.cpp
  code/hud/hudlock.cpp
  code/hud/hudsquadmsg.cpp
  code/hud/hudtarget.cpp
  code/io/keycontrol.cpp
  code/mission/missionhotkey.cpp
  code/mission/missionparse.cpp
  code/network/multiteamselect.cpp
  code/object/objcollide.cpp
  code/object/object.cpp
  code/object/object.h
  code/object/objectsnd.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/ship/shiphit.cpp
  code/weapon/shockwave.cpp
  code/weapon/weapons.cpp
Labels: cleanup, fix

#5062 Ensure 'split ships' are team colored
  code/ship/shipfx.cpp
Labels: fix, graphics

#5066 use correct joystick id type (instance -> device)
  code/io/joy-sdl.cpp
Labels: fix, controls

#5065 swap loop order to fix joystick detection issue
  code/io/joy-sdl.cpp
Labels: fix, controls

#5058 add should-be-dead checks for missile and asteroid iterations
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/asteroid/asteroid.cpp
  code/hud/hudtarget.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/weapon/emp.cpp
  code/weapon/weapons.cpp
Labels: cleanup, fix

#5039 more robust object iteration
  code/object/object.h
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/object.cpp
Labels: fix, scripting

#5073 restore retail behavior of chaining to repeating events
  code/mission/missiongoals.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/parse/sexp.cpp
Labels: timer/timestamp

#5060 SCPUI needs to be able run game_close_level
  code/scripting/api/libs/mission.cpp
Labels: fix, ui

#5078 Disallow overly large input in FRED Orientation Editor
  fred2/orienteditor.cpp
Labels: fix, fred

#5076 Warn dogfight weapons
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: fix, multi, fred

#5087 fix api brief map not rendering icon highlight arrows
  code/missionui/missionbrief.cpp
Labels: fix, ui

#5082 This case was never ported to qtFRED
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, qtfred

#5097 Add missing help for ship-untag sexp
  code/parse/sexp.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, sexps

#5095 Avoid calling `asteroid_add_target()` in FRED.
  code/asteroid/asteroid.cpp
  code/mission/missionparse.cpp
Labels: regression, fix, fred

#5100 Fix regression in sexp argument saving
  code/parse/sexp.cpp
Labels: fix, sexps, fred

#5098 fix team color parsing
  code/mission/missionparse.cpp
  fred2/initialstatus.cpp
Labels: fix, fred

#5105 don't skip first debris item
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix

#5108 Remove the screen signature
  code/anim/animplay.cpp
  code/anim/packunpack.cpp
  code/anim/packunpack.h
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/graphics/generic.cpp
Labels: cleanup, graphics

#5115 do not update the gl buffer for a batch if the batch is empty
  code/render/batching.cpp
Labels: fix, graphics

#5110 make sure we have an argument
  code/parse/sexp.cpp
Labels: fix, sexps

#5114 Fix and expand upon debug safety catcher for ccfg.tbl flag reading.
  code/controlconfig/controlsconfig.h
  code/controlconfig/controlsconfigcommon.cpp
Labels: controls

#5118 update the .mako file for release posts
  ci/post/release.mako
Labels: build

#5127 don't blast no-collide objects
  code/asteroid/asteroid.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/weapon/shockwave.cpp
  code/weapon/weapons.cpp
Labels: fix

#5106 Allow negative number in event editor
  fred2/eventeditor.cpp
  fred2/eventeditor.h
  fred2/fred.rc
  qtfred/src/ui/dialogs/EventEditorDialog.cpp
Labels: enhancement, cleanup, fred

#5129 Move these checks into asteroid.cpp
  code/asteroid/asteroid.cpp
  code/parse/sexp.cpp
Labels: fix, sexps

#5111 Improve handling of failure to find spawn weapons
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: fix

#5126 adding proper launcher documentation for some of my recent flags
  code/cmdline/cmdline.cpp
Labels: cleanup

#5130 Better account for runtime gravity changes
  code/object/objcollide.cpp
  code/object/objcollide.h
  code/parse/sexp.cpp
  code/scripting/api/libs/mission.cpp
Labels: fix, physics

#5135 fix sunglares when lightshafts are disabled
  freespace2/freespace.cpp
Labels: fix

#5140 Warn if beams have damage factors while damage factors are disabled
  code/weapon/weapons.cpp
Labels: cleanup

#5143 patch player tips
  code/menuui/playermenu.cpp
Labels: fix

#5141 Allow way to prevent scpui loading hires animations
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/scpui/RocketRenderingInterface.cpp
Labels: enhancement, Waiting for Stable

#5144 If we're not drawing weapon models then skip all this
  code/ship/ship.cpp
Labels: cleanup, fix

#5142 Removed unhelpful optimization from trail rendering
  code/weapon/trails.cpp
Labels: cleanup, graphics

#5107 some validity checks to order sending
  code/hud/hudsquadmsg.cpp
  code/hud/hudsquadmsg.h
  code/ship/ship.cpp
  code/ship/ship.h
Labels: cleanup, fix, HUD

#5151 better safety for `ai_select_secondary_weapon`
  code/ai/aicode.cpp
Labels: fix

#5153 Don't try to choose a secondary if there are no choices
  code/ai/aicode.cpp
Labels: fix, ai
