Repository scp-fs2open/fs2open.github.com, pull requests merged in 2023-08, with the labels that each got.

#5537 Fix: Prevent loadout related CTD
  code/scripting/api/objs/shipwepselect.cpp
Labels: fix

#5539 Fix animated background bitmaps rendering with incorrect framerate
  code/starfield/starfield.cpp
Labels: fix, graphics

#5527 add model filename back into debug log
  code/model/modelread.cpp
Labels: fix

#5513 fix a couple bugs in the campaign editor
  code/mission/missioncampaign.h
  fred2/campaigneditordlg.cpp
  fred2/campaigneditordlg.h
  fred2/campaigntreewnd.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: regression, fix, fred

#5546 Fix "File exists" error
  cmake/util.cmake
Labels: build

#5526 add screen resolution scaling for hud-set-coords
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/parse/sexp.cpp
Labels: enhancement, fix, HUD, sexps

#5528 'detonate on expiration' weapon flag
  code/ship/shiphit.cpp
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
Labels: enhancement, fix

#5551 remove Int3()'s in ai_mission_goal_achievable
  code/ai/aigoals.cpp
Labels: cleanup, fix

#5553 nightly build updates
  .travis.yml
  Readme.md
  appveyor.yml
  ci/appveyor/build.ps1
  ci/appveyor/test.ps1
  ci/linux/upload_dist_package.sh
  ci/post/main.py
  ci/post/release.mako
  ci/travis/before_deploy.sh
  ci/travis/before_install.sh
  ci/travis/before_script.sh
  ci/travis/check_release.sh
  ci/travis/ftp_deploy.sh
  ci/travis/install.sh
  ci/travis/release.sh
  ci/travis/script.sh
  code/ai/ai_flags.h
  code/cmdline/cmdline.cpp
  code/menuui/credits.cpp
  code/missionui/missionshipchoice.cpp
Labels: build, ci

#5548 ai-stay-near-ship fixes
  code/ai/aigoals.cpp
  code/parse/sexp.cpp
Labels: fix, sexps

#5550 fix flags in modular weapon entries being cleared
  code/globalincs/flagset.h
  code/weapon/weapons.cpp
Labels: fix, general modding

#5558 some streaming animation fixes
  code/graphics/generic.cpp
  code/graphics/generic.h
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/libs/graphics.h
  code/scripting/api/objs/streaminganim.cpp
Labels: fix, scripting, Requested by Active Mod

#5559 assign weapon particle effects properly
  code/weapon/weapons.cpp
Labels: fix

#5560 improve launching of FRED help
  fred2/mainfrm.cpp
Labels: fix, fred

#5563 fix $Movie subtitle font: for custom fonts
  code/cutscene/movie.cpp
  code/mod_table/mod_table.cpp
Labels: fix

#5567 handle extension mismatch in event music
  code/sound/ffmpeg/FFmpegWaveFile.cpp
Labels: fix

#5568 fix crash in campaign editor
  fred2/fred.cpp
Labels: fix, fred

#5572 fix validity check for soundtracks
  code/gamesnd/eventmusic.cpp
  code/sound/ffmpeg/FFmpegWaveFile.cpp
Labels: fix

#5573 Fix issues with newer Nvidia driver
  code/def_files/data/effects/deferred-f.sdr
  code/def_files/data/effects/deferred-v.sdr
Labels: fix, graphics, opengl

#5575 fix persistent sounds not clearing their tally
  code/object/objectsnd.cpp
  code/object/objectsnd.h
Labels: fix

#5578 fix soundtrack timestamp when change-soundtrack is called immediately
  code/gamesnd/eventmusic.cpp
Labels: fix

#5577 additional music checks
  code/gamesnd/eventmusic.cpp
  code/gamesnd/eventmusic.h
  code/mission/missionparse.cpp
  code/missionui/missionscreencommon.cpp
  code/missionui/missionscreencommon.h
  code/scripting/api/libs/ui.cpp
Labels: fix
