Repository scp-fs2open/fs2open.github.com, pull requests merged in 2023-12, with the labels that each got.

#5506 Restore (mostly-)retail debrief failure counting behavior.
  code/mission/missioncampaign.cpp
  code/missionui/missiondebrief.cpp
Labels: regression, fix, discussion

#4634 add reset-event and reset-goal
  code/mission/missioncampaign.cpp
  code/mission/missiongoals.cpp
  code/mission/missiongoals.h
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: sexps, feature

#5853 add mac arm64 builds to CI workflow
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/build-test.yaml
  .github/workflows/test-pull_request.yaml
  ci/linux/create_dist_pack.sh
  ci/linux/run_tests.sh
  ci/post/release.mako
  cmake/platform-darwin.cmake
  tools/embedfile/CMakeLists.txt
Labels: build

#5799 Add safety to crusty old physics code (coverity issue)
  code/physics/physics.cpp
Labels: cleanup, physics

#5854 fix Lua API arguments
  code/scripting/api/objs/movie_player.cpp
Labels: fix, scripting

#5855 change two global variables to be scoped
  code/osapi/osapi.cpp
Labels: coverity, cleanup

#5858 VR Lua interface
  code/scripting/api/libs/graphics.cpp
  code/scripting/scripting.cpp
  code/scripting/scripting.h
Labels: scripting

#5862 allow nonexistence of arrival overlays
  code/gamesnd/eventmusic.cpp
Labels: enhancement, Requested by Active Mod

#5864 fix query_node_argument_type()
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, qtfred, fred

#5861 Avoid a casting warning in cmdline.cpp
  code/cmdline/cmdline.cpp
Labels: cleanup

#5866 add more autosaving in FRED
  fred2/addvariabledlg.cpp
  fred2/asteroideditordlg.cpp
  fred2/bgbitmapdlg.cpp
  fred2/briefingeditordlg.cpp
  fred2/cmdbrief.cpp
  fred2/debriefingeditordlg.cpp
  fred2/eventeditor.cpp
  fred2/messageeditordlg.cpp
  fred2/messageeditordlg.h
  fred2/missioncutscenesdlg.cpp
  fred2/missioncutscenesdlg.h
  fred2/missiongoalsdlg.cpp
  fred2/missiongoalsdlg.h
  fred2/missionnotesdlg.cpp
  fred2/orienteditor.cpp
  fred2/playerstarteditor.cpp
  fred2/shipeditordlg.cpp
  fred2/shipspecialhitpoints.cpp
  fred2/shipspecialhitpoints.h
  fred2/wing_editor.cpp
Labels: enhancement, fred

#5828 Deferred light mesh submission optimizations
  code/graphics/opengl/gropengldeferred.cpp
  code/graphics/opengl/gropengldeferred.h
Labels: cleanup, graphics, optimization

#5867 Change the discord option category to "game"
  code/graphics/2d.cpp
  code/mod_table/mod_table.cpp
Labels: cleanup, ui

#5607 LuaDrawstring optimization
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/scripting/api/libs/graphics.cpp
Labels: enhancement, graphics, scripting

#5811 implement on-mission-skip SEXP
  code/mission/missioncampaign.cpp
  code/mission/missioncampaign.h
  code/mission/missiongoals.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: gameplay, sexps, Requested by Active Mod

#5451 Animation Drivers
  code/lab/dialogs/lab_ui.h
  code/lab/manager/lab_manager.h
  code/math/curve.cpp
  code/math/curve.h
  code/mission/missionparse.h
  code/model/animation/modelanimation.cpp
  code/model/animation/modelanimation.h
  code/model/animation/modelanimation_driver.cpp
  code/model/animation/modelanimation_driver.h
  code/model/animation/modelanimation_moveables.cpp
  code/model/animation/modelanimation_moveables.h
  code/model/animation/modelanimation_segments.cpp
  code/model/animation/modelanimation_segments.h
  code/scripting/api/objs/animation_handle.h
  code/ship/ship.cpp
  code/ship/ship.h
  code/source_groups.cmake
  code/weapon/weapon.h
Labels: general modding, models, feature

#5829 replace pointers with indexes in ship registry and oswpt
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/hud/hudbrackets.cpp
  code/mission/missionparse.cpp
  code/mission/missiontraining.cpp
  code/missionui/redalert.cpp
  code/network/multiteamselect.cpp
  code/network/multiutil.cpp
  code/object/waypoint.cpp
  code/object/waypoint.h
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp/LuaSEXP.cpp
  code/playerman/playercontrol.cpp
  code/scripting/api/objs/oswpt.cpp
  code/scripting/api/objs/ship_registry_entry.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: general modding, refactor

#5871 juggling fix
  fred2/briefingeditordlg.cpp
Labels: fix, fred

#5877 bump missionlog limit
  code/mission/missionlog.cpp
Labels: fix, Requested by Active Mod

#5865 Scpui multi options
  code/localization/localize.cpp
  code/menuui/barracks.cpp
  code/menuui/mainhallmenu.cpp
  code/menuui/optionsmenumulti.cpp
  code/menuui/playermenu.cpp
  code/network/multi.h
  code/network/multi_endgame.cpp
  code/network/multi_fstracker.cpp
  code/network/multi_options.cpp
  code/network/multi_options.h
  code/network/multi_pxo.cpp
  code/network/multiui.cpp
  code/network/multiui.h
  code/pilotfile/plr.cpp
  code/scripting/api/libs/options.cpp
Labels: enhancement, multi, ui, scripting

#5879 QOL: Don't reset the position in the player list if we switch modes
  code/menuui/playermenu.cpp
  code/menuui/playermenu.h
Labels: enhancement, ui

#5880 Fix renderOverheadModel's reliance on wss_slots
  code/missionui/missionweaponchoice.cpp
  code/missionui/missionweaponchoice.h
  code/scripting/api/objs/shipclass.cpp
Labels: cleanup, scripting

#5868 More scpui options
  code/localization/localize.cpp
  freespace2/freespace.cpp
Labels: enhancement, ui

#5888 fix crash in QtFRED
  qtfred/ui/FredView.ui
Labels: fix, qtfred

#5827 tweak event status evaluation when the game is not in-mission
  code/parse/sexp.cpp
Labels: enhancement, sexps

#5892 Fix Coverity WorkFlow
  .github/workflows/weekly-coverity-scan.yaml
Labels: fix, build

#5898 make error messages more accurate
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: fix, sexps, Requested by Active Mod

#5901 Fix typo in lua error prints
  code/scripting/lua/LuaFunction.cpp
  code/scripting/lua/LuaTable.cpp
Labels: fix, scripting

#5863 Make beams respect 'check hull' and 'can damage shooter' flags
  code/weapon/beam.cpp
Labels: fix, gameplay

#5837 untangle turret code a bit
  code/ai/aicode.cpp
  code/ai/aiinternal.h
  code/ai/aiturret.cpp
  code/camera/camera.cpp
  code/model/model.h
  code/model/model_flags.h
  code/model/modelread.cpp
  code/scripting/api/objs/subsystem.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/beam.cpp
Labels: cleanup, fix, refactor

#5907 Fix unbalanced stack when retrieving Lua main thread
  code/scripting/lua/LuaUtil.cpp
Labels: fix, scripting

#5906 additional HUD fixes for VR
  code/hud/hud.cpp
  code/hud/hud.h
  freespace2/freespace.cpp
Labels: fix, HUD

#5903 Improve description of `type` and `instance`
  code/object/object.h
Labels: documentation
