Repository scp-fs2open/fs2open.github.com, pull requests merged in 2023-11, with the labels that each got.

#5611 Force rearm sexp
  code/ai/aicode.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, sexps

#5732 Fix for ets changes when engines are <15%
  code/hud/hudets.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: fix, gameplay

#5624 xstr debug filter
  code/localization/localize.cpp
Labels: enhancement, localization / translation

#5746 Fix #5743
  code/graphics/uniforms.cpp
Labels: fix, graphics, Point Release Candidate

#5741 some polishing of recent changes
  code/ai/ailua.cpp
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/missionui/missionweaponchoice.h
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: fix

#5712 Add a weekly coverity workflow
  .github/workflows/weekly-coverity-scan.yaml
Labels: ci, sanitizer/stability

#5536 Mission custom data
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/scripting/api/libs/mission.cpp
  fred2/CMakeLists.txt
  fred2/customdatadlg.cpp
  fred2/customdatadlg.h
  fred2/fred.cpp
  fred2/fred.h
  fred2/fred.rc
  fred2/fredview.cpp
  fred2/management.cpp
  fred2/missionnotesdlg.cpp
  fred2/missionnotesdlg.h
  fred2/missionsave.cpp
  fred2/missionsave.h
  fred2/resource.h
  qtfred/src/mission/missionsave.cpp
  qtfred/src/mission/missionsave.h
Labels: enhancement, qtfred, fred, scripting, Requested by Active Mod

#5740 Fix subsys positions in `ai_new_maybe_reposition_attack_subsys`... again
  code/ai/aibig.cpp
Labels: fix, ai

#5729 Change the scope of this pointer
  code/ai/aibig.cpp
Labels: coverity, fix, sanitizer/stability

#5744 Handle oct30 covscan issues
  code/cfile/cfile.cpp
  code/model/modelrender.cpp
  code/starfield/nebula.cpp
Labels: coverity, sanitizer/stability

#5739 how about an if/then/else that actually works?
  code/ai/ailua.cpp
Labels: cleanup, sexps

#5694 Upgrade Lua Sound Handling methods
  code/scripting/api/libs/audio.cpp
  code/scripting/api/objs/sound.cpp
  code/sound/ds.cpp
  code/sound/sound.cpp
  code/sound/sound.h
Labels: sound, scripting, Requested by Active Mod

#5698 Waypoints upgrade
  code/ai/ai.h
  code/ai/ai_flags.h
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aigoals.h
  code/autopilot/autopilot.cpp
  code/mission/missiongrid.cpp
  code/mission/missiongrid.h
  code/network/multi_obj.cpp
  code/object/object.cpp
  code/object/object.h
  code/object/waypoint.cpp
  code/object/waypoint.h
  code/parse/sexp.cpp
  code/scripting/api/objs/order.cpp
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
  fred2/dumpstats.cpp
  fred2/editor.h
  fred2/fredrender.cpp
  fred2/fredview.cpp
  fred2/management.cpp
  fred2/management.h
  fred2/missionsave.cpp
  fred2/missionsave.h
  fred2/sexp_tree.cpp
  fred2/shipgoalsdlg.cpp
  fred2/waypointpathdlg.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/dialogs/SelectionDialogModel.cpp
  qtfred/src/mission/dialogs/ShipGoalsDialogModel.cpp
  qtfred/src/mission/dialogs/WaypointEditorDialogModel.cpp
  qtfred/src/mission/dialogs/WaypointEditorDialogModel.h
  qtfred/src/mission/missionsave.cpp
  qtfred/src/mission/missionsave.h
  qtfred/src/ui/dialogs/ShipGoalsDialog.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: enhancement, gameplay, Requested by Active Mod

#5756 Missed a couple out of bounds checks
  fred2/customdatadlg.cpp
Labels: fix

#5752 Mod setting to disable FSO's internal loadout restoration
  code/missionui/missionscreencommon.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: enhancement, scripting, Requested by Active Mod

#5760 Fix #5759 Sticky Support Ship
  code/ai/aicode.cpp
Labels: fix, ai

#5758 Coverity improper use of negative
  code/ai/aicode.cpp
  code/parse/sexp.cpp
Labels: coverity, sexps, sanitizer/stability

#5750 Provide a way to account for timer padding in the mission log
  code/hud/hudmessage.cpp
  code/hud/hudmessage.h
  code/mission/missionlog.cpp
  code/mission/missionlog.h
  code/scripting/api/objs/missionlog.cpp
Labels: enhancement, scripting, Requested by Active Mod

#5593 Rank display name and title
  code/localization/localize.cpp
  code/missionui/missiondebrief.cpp
  code/network/multi_pinfo.cpp
  code/network/multi_pxo.cpp
  code/network/multiui.cpp
  code/network/multiui.h
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/rank.cpp
  code/stats/medals.cpp
  code/stats/scoring.cpp
  code/stats/scoring.h
Labels: cleanup, localization / translation

#5764 two small tweaks
  code/gamesnd/eventmusic.cpp
  code/parse/sexp.cpp
Labels: cleanup

#5762 Command fixes and tweaks
  code/mission/missionmessage.cpp
  code/mission/missionmessage.h
  code/parse/sexp.cpp
Labels: fix, sexps, general modding

#5770 fix a FRED compilation warning
  fred2/fred.rc
  fred2/resource.h
  fred2/voiceactingmanager.cpp
Labels: fred, compiler

#5742 Get rid of remaining int3s in AI code
  code/ai/aibig.cpp
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aiturret.cpp
  code/anim/packunpack.cpp
Labels: cleanup, ai

#5775 Removed unused variables in HUD code
  code/hud/hud.h
Labels: cleanup, HUD

#5772 protect eval_enemy_obj_struct input values
  code/ai/aiturret.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/ship/ship.h
  code/weapon/weapons.cpp
Labels: cleanup, gameplay

#5771 protect model_collide input values
  code/asteroid/asteroid.cpp
  code/debris/debris.cpp
  code/model/model.h
  code/object/collideshipship.cpp
  code/weapon/flak.h
Labels: cleanup, physics

#5776 FRED import fixes
  fred2/freddoc.cpp
Labels: fix, fred

#5779 Fix collision bug
  code/asteroid/asteroid.cpp
  code/debris/debris.cpp
  code/object/collideshipship.cpp
Labels: fix, physics

#5777 Only untarget jumpnode if we're in a mission
  code/jumpnode/jumpnode.cpp
Labels: fix, Point Release Candidate

#5784 add version check to fix older ffmpeg versions
  code/sound/ffmpeg/FFmpegWaveFile.cpp
Labels: fix

#5785 fix invalid pointer access to waypoint lists
  code/object/waypoint.cpp
  code/object/waypoint.h
Labels: fix, fred, Point Release Candidate

#5786 Fix wingman headanis
  code/graphics/generic.cpp
  code/graphics/generic.h
  code/hud/hudmessage.cpp
Labels: fix, graphics, HUD

#5773 convert some instances of frand_range to Random::next
  code/ai/aiturret.cpp
  code/cheats_table/cheats_table.cpp
  code/hud/hudartillery.cpp
  code/menuui/fishtank.cpp
  code/nebula/neblightning.cpp
  code/network/multi_pxo.cpp
  code/network/multiui.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/weapon/beam.cpp
  code/weapon/emp.cpp
  freespace2/freespace.cpp
Labels: cleanup, graphics, gameplay

#5774 Add lua burst values
  code/scripting/api/objs/ship_bank.cpp
Labels: enhancement, scripting

#5755 Allow particles to inherit size and lifetime
  code/particle/ParticleSource.cpp
  code/particle/ParticleSource.h
  code/particle/util/ParticleProperties.cpp
  code/particle/util/ParticleProperties.h
Labels: enhancement, particles

#5781 Mainhall ignore input
  code/menuui/mainhallmenu.cpp
  code/menuui/mainhallmenu.h
  code/scripting/api/libs/ui.cpp
Labels: enhancement, ui, scripting

#5676 Add command line option for window resolution
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/graphics/grstub.cpp
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropengldraw.cpp
  code/graphics/opengl/gropengldraw.h
  code/graphics/opengl/gropengltexture.cpp
  code/graphics/vulkan/vulkan_stubs.cpp
  code/io/mouse.cpp
  freespace2/SDLGraphicsOperations.cpp
  freespace2/freespace.cpp
Labels: graphics, required feature

#5782 a few build fixes
  code/cfile/cfilesystem.cpp
  code/network/psnet2.cpp
  code/utils/HeapAllocator.cpp
Labels: cleanup, build, compiler

#5701 add const where appropriate to the jump node API
  code/jumpnode/jumpnode.cpp
  code/jumpnode/jumpnode.h
  code/parse/sexp.cpp
  fred2/jumpnodedlg.cpp
  fred2/missionsave.cpp
  fred2/missionsave.h
  qtfred/src/mission/missionsave.cpp
  qtfred/src/mission/missionsave.h
Labels: cleanup

#5766 Expose more submodel instance and submodel attributes and functions to Lua
  code/model/model.h
  code/model/modelread.cpp
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/modelinstance.cpp
  test/src/model/test_modelread.cpp
Labels: enhancement, scripting

#5789 Fix documentation error in On State Start
  code/scripting/global_hooks.cpp
Labels: cleanup, documentation

#5753 Moar curves
  code/object/collideshipweapon.cpp
  code/object/collideweaponweapon.cpp
  code/weapon/beam.cpp
  code/weapon/shockwave.cpp
  code/weapon/shockwave.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, graphics, gameplay

#5645 Lua Child Enums for Sexp types
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp/LuaSEXP.cpp
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: sexps, scripting, feature, Requested by Active Mod

#5522 Custom lua action for mainhall esc keypress
  code/menuui/mainhallmenu.cpp
  code/menuui/mainhallmenu.h
Labels: enhancement, discussion, controls, ui, scripting, Requested by Active Mod

#5790 Add built-in xstrs for SCP-added custom controls
  code/controlconfig/controlsconfigcommon.cpp
  code/localization/localize.cpp
Labels: cleanup, controls

#5765 optimization for checking whether subsystems are blown
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/object/object.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipfx.cpp
Labels: general modding, optimization

#5788 rcs thruster refactor
  code/globalincs/flagset.h
  code/ship/ship.cpp
  code/ship/ship.h
Labels: refactor

#5797 fix 5773
  code/ai/aiturret.cpp
Labels: fix

#5787 refactor argument functions
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/messageeditordlg.cpp
Labels: sexps, refactor

#5794 FRED missionsave updates
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: fix, qtfred, fred

#5793 Disallow Replace Container Data for all special argument SEXPs
  code/parse/sexp.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, qtfred, sexps, fred

#5748 Event currency tweaks
  code/mission/missioncampaign.cpp
  code/mission/missiongoals.cpp
  code/mission/missiongoals.h
  code/mission/missiontraining.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: cleanup, fix

#5795 Fix incorrect out of bounds check
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, sexps

#5791 Downgrade this warning to a log print
  code/parse/sexp/LuaSEXP.cpp
Labels: cleanup

#5792 Add ability to remove an enum item from a list
  code/scripting/api/objs/LuaEnum.cpp
Labels: enhancement

#5778 Don't ignore user-set -O* flags
  cmake/toolchain-clang.cmake
  cmake/toolchain-gcc.cmake
Labels: fix, sanitizer/stability, linux

#5801 Allow Modders to Set Rotational Scaling Multiplier for Asteroids/Debris
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
Labels: enhancement

#5608 move -no_unfocused_pause
  code/cmdline/cmdline.cpp
Labels: discussion

#5806 Fix for changing the number of banks on a ship
  code/ship/ship.cpp
Labels: fix, Point Release Candidate

#5802 Add way to offset directive help text only
  code/hud/hudparse.cpp
  code/mission/missiontraining.cpp
  code/mission/missiontraining.h
Labels: enhancement, cleanup, HUD

#5807 Revert removal of allowRelative in `applyToParticleInfo`
  code/particle/ParticleSource.cpp
  code/particle/ParticleSource.h
Labels: fix, particles

#5618 Fred cutscene dialog
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/CMakeLists.txt
  fred2/fred.cpp
  fred2/fred.h
  fred2/fred.rc
  fred2/fredview.cpp
  fred2/fredview.h
  fred2/management.cpp
  fred2/missioncutscenesdlg.cpp
  fred2/missioncutscenesdlg.h
  fred2/resource.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
Labels: enhancement, qtfred, sexps, fred

#5798 Add child enum suffix option
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp/LuaSEXP.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: enhancement, sexps, scripting

#5813 small briefing bugfix
  fred2/briefingeditordlg.cpp
Labels: fix, fred

#5808 rename Vaporize Percent Chance
  code/ai/ai_profiles.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shiphit.cpp
Labels: general modding, refactor

#5816 Expose `isValid` parse object check to scripting
  code/scripting/api/objs/parse_object.cpp
Labels: cleanup, scripting

#5810 Remove is-docked check for transfer-cargo sexp
  code/parse/sexp.cpp
Labels: enhancement, cleanup, sexps

#5814 Deprecate IsValid in favor of isValid
  code/scripting/api/objs/eye.cpp
Labels: cleanup, scripting

#5819 FRED checkbox upgrade
  fred2/checkboxlistdlg.cpp
  fred2/checkboxlistdlg.h
  fred2/ignoreordersdlg.cpp
  fred2/ignoreordersdlg.h
  fred2/initialships.cpp
  fred2/initialships.h
  fred2/playerstarteditor.cpp
  fred2/playerstarteditor.h
  fred2/restrictpaths.cpp
  fred2/restrictpaths.h
  fred2/ship_select.h
Labels: enhancement, fix, fred

#5817 fix loadout dialog updating in FRED
  fred2/playerstarteditor.cpp
Labels: fix, fred

#5761 These std moves were suggested by Coverity as optimizations
  code/hud/hudsquadmsg.cpp
  code/model/modelanimation.cpp
  code/model/modelread.cpp
  code/parse/sexp/sexp_lookup.cpp
  code/scripting/api/libs/ui.cpp
  code/ship/shipfx.cpp
  code/ship/shiphit.cpp
  freespace2/freespace.cpp
Labels: coverity, sanitizer/stability

#5818 Remove redundant batching_render_all calls
  code/object/objectsort.cpp
  code/particle/particle.cpp
Labels: graphics, particles, optimization

#5825 Fix for lasers with head on bitmaps
  code/weapon/weapons.cpp
Labels: fix, graphics

#5569 Do not validate loadouts
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  fred2/fred.rc
  fred2/freddoc.cpp
  fred2/missionsave.cpp
  fred2/playerstarteditor.cpp
  fred2/playerstarteditor.h
  fred2/resource.h
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/missionsave.cpp
Labels: qtfred, fred, Requested by Active Mod

#5824 Localize strings in ship_select_blit_info
  code/localization/localize.cpp
  code/missionui/missionshipchoice.cpp
Labels: cleanup

#5751 upgrade timestamps referenced in freespace.cpp
  code/globalincs/systemvars.cpp
  code/globalincs/systemvars.h
  code/graphics/light.cpp
  code/graphics/light.h
  code/mission/missiontraining.cpp
  code/mission/missiontraining.h
  code/parse/sexp.cpp
  code/parse/sexp.h
  freespace2/freespace.cpp
Labels: refactor, timer/timestamp

#5803 Add Start/Loop/End sounds for weapons
  code/ai/aicode.cpp
  code/hud/hudlock.cpp
  code/object/object.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/ship_flags.h
  code/weapon/weapon.h
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
Labels: sound, feature

#5815 Implement direction-blind contrails option.
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/ship/shipcontrails.cpp
Labels: enhancement, Requested by Active Mod

#5826 Scpui language selector
  code/graphics/software/font.cpp
  code/localization/localize.cpp
  code/localization/localize.h
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: enhancement, ui, scripting, localization / translation

#5544 Mission custom strings
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/scripting/api/libs/mission.cpp
  code/scripting/global_hooks.cpp
  code/scripting/global_hooks.h
  fred2/CMakeLists.txt
  fred2/customstringsdlg.cpp
  fred2/customstringsdlg.h
  fred2/fred.h
  fred2/fred.rc
  fred2/fredview.cpp
  fred2/missionnotesdlg.cpp
  fred2/missionnotesdlg.h
  fred2/missionsave.cpp
  fred2/resource.h
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, qtfred, fred, scripting, Requested by Active Mod

#5835 Verify this is in bounds and add vector_inbound macro
  code/globalincs/vmallocator.h
  code/localization/localize.cpp
Labels: cleanup, fix, localization / translation

#5836 Do not translate these if setting is enabled
  code/hud/hudtargetbox.cpp
Labels: fix, localization / translation

#5800 avoid storing ship_info pointers in data structures
  code/scripting/api/objs/cockpit_display.cpp
  code/scripting/api/objs/cockpit_display.h
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/ship/shipfx.h
Labels: general modding, refactor

#5833 Update PR build image and compilers
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/build-standalone.yaml
  .github/workflows/build-test.yaml
  .github/workflows/cache-master.yaml
  .github/workflows/test-pull_request.yaml
  CMakeLists.txt
  ci/linux/configure_cmake.sh
  code/bmpman/bmpman.cpp
  code/controlconfig/controlsconfigcommon.cpp
  code/cutscene/cutscenes.cpp
  code/globalincs/pstypes.h
  code/globalincs/toolchain/clang.h
  code/globalincs/toolchain/gcc.h
  code/globalincs/toolchain/mingw.h
  code/globalincs/toolchain/msvc.h
  code/hud/hudparse.cpp
  code/hud/hudtargetbox.cpp
  code/io/joy-sdl.cpp
  code/io/key.cpp
  code/mission/missionlog.cpp
  code/model/modelrender.cpp
  code/network/multi_lua.cpp
  code/object/collideshipship.cpp
  code/object/objectshield.cpp
  code/parse/sexp/EngineSEXP.cpp
  code/parse/sexp/EngineSEXP.h
  code/scripting/hook_api.cpp
  code/scripting/util/LuaValueDeserializer.cpp
  code/ship/shipfx.cpp
Labels: cleanup, build, compiler

#5841 Update container image to fix artifact uploads
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/build-test.yaml
  .github/workflows/cache-master.yaml
  .github/workflows/test-pull_request.yaml
Labels: build

#5830 Vectorize multi pxo
  code/network/multi_pxo.cpp
  code/network/multi_pxo.h
Labels: cleanup, multi, ui, scripting

#5843 Reenable QtFred building for Linux CI builds
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/build-test.yaml
  .github/workflows/cache-master.yaml
  .github/workflows/test-pull_request.yaml
  .github/workflows/weekly-coverity-scan.yaml
  ci/linux/configure_cmake.sh
Labels: fix, build

#5840 Add cockpit 'sway'
  code/hud/hud.cpp
  code/scripting/api/libs/hud.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement, Requested by Active Mod

#5839 make radar timestamps type-safe
  code/radar/radar.cpp
  code/radar/radardradis.cpp
  code/radar/radardradis.h
  code/radar/radarorb.cpp
  code/radar/radarsetup.cpp
  code/radar/radarsetup.h
Labels: refactor, timer/timestamp
