Repository scp-fs2open/fs2open.github.com, pull requests merged in 2023-07, with the labels that each got.

#5476 Clear C++ Handles to LuaThread-stuff more aggressively
  code/scripting/lua/LuaThread.cpp
Labels: fix

#5479 fix instructor check
  code/ai/aicode.cpp
Labels: fix

#5477 Avoid displaying hidden ship names in the escort list.
  code/hud/hudescort.cpp
Labels: enhancement, refactor

#5482 fix some bugs revealed by ships with long display names
  code/playerman/player.h
  code/playerman/playercontrol.cpp
  code/ship/shiphit.cpp
Labels: fix

#5485 Properly deinit io-lib LuaFunctions
  code/controlconfig/controlsconfigcommon.cpp
Labels: fix

#5492 Ignore voice recognition events while game is paused.
  code/sound/voicerec.cpp
Labels: fix

#5491 When playing the demo, don't try to reset if no campaign is active.
  code/menuui/readyroom.cpp
Labels: fix

#5483 Improved hud gauge loading safety
  code/bmpman/bmpman.cpp
  code/hud/hud.cpp
  code/hud/hudescort.cpp
  code/hud/hudets.cpp
  code/hud/hudlock.cpp
  code/hud/hudreticle.cpp
  code/hud/hudshield.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/hud/hudwingmanstatus.cpp
  code/mission/missiontraining.cpp
  code/radar/radar.cpp
  code/radar/radarorb.cpp
Labels: fix, HUD

#5498 add missing #includes to fix compilation
  code/sound/voicerec.cpp
Labels: fix, build

#5497 Add a warning for cases when we couldn't load a trail bitmap
  code/render/batching.cpp
  code/ship/ship.cpp
  code/weapon/trails.cpp
  code/weapon/weapons.cpp
Labels: cleanup, fix, general modding

#5496 Improve performance of collision retiming
  code/autopilot/autopilot.cpp
  code/object/objcollide.cpp
  code/object/objcollide.h
  code/object/object_flags.h
  code/parse/sexp.cpp
  code/scripting/api/objs/object.cpp
  code/tracing/categories.cpp
  code/tracing/categories.h
Labels: fix, physics

#5499 fix Lua API access to Fireballs array
  code/fireball/fireballs.h
  code/scripting/api/libs/mission.cpp
Labels: fix

#5500 Remove `Int3()`s from `message_translate_tokens()`.
  code/mission/missiontraining.cpp
Labels: fix

#5488 Fix weapon flags +override handling wrt spawn flag
  code/weapon/weapons.cpp
Labels: fix, general modding

#5475 prevent AI autoscaling for only a single autoscaled class
  code/ai/aicode.cpp
Labels: fix, ai

#5501 Explicitly zero out persona bitfields
  code/mission/missionmessage.cpp
Labels: fix

#5504 Fix for countermeasures with a single segment trail
  code/cmeasure/cmeasure.cpp
Labels: fix, graphics

#5511 Add more error checking in joy-sdl.cpp.
  code/io/joy-sdl.cpp
Labels: controls, refactor

#5509 Some more fixes for laser single segment trails
  code/weapon/trails.cpp
  code/weapon/weapons.cpp
Labels: fix, graphics

#5517 fix mission corruption in FRED
  fred2/missionsave.cpp
  fred2/missionsave.h
  qtfred/src/mission/missionsave.cpp
  qtfred/src/mission/missionsave.h
Labels: fix, qtfred, fred

#5520 SEXP parsing cleanup and fixes
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/parse/sexp.cpp
  fred2/freddoc.cpp
Labels: cleanup, fix, sexps
