Repository scp-fs2open/fs2open.github.com, pull requests merged in 2023-03, with the labels that each got.

#5222 Fix retail star look by applying gamma correction
  code/starfield/starfield.cpp
Labels: fix, graphics

#5225 Fix On Beam Fired hook variable name
  code/scripting/global_hooks.cpp
Labels: regression, fix

#5075 Use weapon tech model if no anim
  code/menuui/techmenu.cpp
Labels: ui, feature

#5119 Refactor gameplay help
  code/gamehelp/gameplayhelp.cpp
  code/gamehelp/gameplayhelp.h
Labels: ui, refactor

#5104 Persona species enhancements
  code/mission/missionmessage.cpp
  code/mission/missionmessage.h
  fred2/shipeditordlg.cpp
  qtfred/src/ui/dialogs/ShipEditorDialog.cpp
Labels: enhancement

#5230 Fix damage scaling oversight
  code/ship/shiphit.cpp
Labels: fix

#5224 Update some movement flags to work for AI too
  code/ai/aicode.cpp
Labels: fix, ai

#5229 add some XSTR entries
  code/controlconfig/controlsconfigcommon.cpp
  code/io/joy-sdl.cpp
  code/lab/renderer/lab_renderer.cpp
  code/localization/localize.cpp
  code/missionui/missionshipchoice.cpp
  code/playerman/playercontrol.cpp
Labels: fix, localization / translation

#5177 Document options files
  code/options/Option.cpp
  code/options/Option.h
  code/options/OptionsManager.cpp
Labels: cleanup, ui, documentation

#5217 Use subsystem names instead of model names
  code/mission/missionlog.cpp
Labels: enhancement

#5233 Small fix for thruster flicker
  code/model/modelrender.cpp
Labels: fix

#5237 Add new OpenGL Debug Mode to cmake
  CMakeLists.txt
  code/CMakeLists.txt
  freespace2/CMakeLists.txt
Labels: build

#5033 Enhance Dynamic SEXPs with parent parameters
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp/DynamicSEXP.h
  code/parse/sexp/EngineSEXP.cpp
  code/parse/sexp/EngineSEXP.h
  code/parse/sexp/LuaAISEXP.cpp
  code/parse/sexp/LuaAISEXP.h
  code/parse/sexp/LuaSEXP.cpp
  code/parse/sexp/LuaSEXP.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: enhancement, sexps, scripting

#5090 SCPUI methods required for handling closeup briefing icon stuff
  code/missionui/missionbrief.cpp
  code/missionui/missionbrief.h
  code/model/modelrender.cpp
  code/model/modelrender.h
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/shipclass.cpp
  code/scripting/api/objs/weaponclass.cpp
Labels: enhancement, ui, scripting

#5238 Remove `Attach_thrusters` submodel flag
  code/model/model_flags.h
  code/model/modelread.cpp
Labels: cleanup

#5235 use large asteroids speed when chucking asteroids
  code/asteroid/asteroid.cpp
Labels: fix

#5223 Add shudder multipliers
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
  freespace2/freespace.cpp
Labels: enhancement

#5240 Adjust movement sanity checks to account for more situations
  code/model/modelread.cpp
Labels: fix, models

#5243 add some ship flags to the alter-ship-flag lists
  code/ship/ship.cpp
Labels: enhancement

#5234 add missing HUD gauges
  code/hud/hudparse.cpp
Labels: fix, HUD

#5247 fix submodel sanity check
  code/model/modelread.cpp
Labels: fix, models

#5250 fix Techroom_modelnum references
  code/menuui/techmenu.cpp
Labels: fix, models

#5245 fixup error checking in regards to sexps using dynamic parameters
  code/parse/sexp.cpp
Labels: fix, sexps, scripting

#5254 Always test review-suggested code for errors
  code/parse/sexp.cpp
Labels: fix, sexps

#5259 Use qtfred style warning instead of fred style
  qtfred/src/mission/missionsave.cpp
Labels: fix, qtfred

#3392 QtFRED campaign editor
  code/menuui/readyroom.cpp
  code/mission/missioncampaign.cpp
  code/mission/missioncampaign.h
  fred2/campaigntreewnd.cpp
  qtfred/source_groups.cmake
  qtfred/src/CheckedDataListModel.h
  qtfred/src/main.cpp
  qtfred/src/mission/dialogs/CampaignEditorDialogModel.cpp
  qtfred/src/mission/dialogs/CampaignEditorDialogModel.h
  qtfred/src/mission/management.cpp
  qtfred/src/mission/management.h
  qtfred/src/mission/missionsave.cpp
  qtfred/src/mission/missionsave.h
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
  qtfred/src/ui/dialogs/CampaignEditorDialog.cpp
  qtfred/src/ui/dialogs/CampaignEditorDialog.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
  qtfred/ui/CampaignEditorDialog.ui
Labels: qtfred, required feature

#5261 Fix a bug in mission log with subsys names
  code/mission/missionlog.cpp
Labels: fix, ui

#5125 Toggle auto-assigning personas
  code/mission/missionmessage.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: enhancement, general modding

#5275 Add some parameters for corkscrew starting angle
  code/weapon/corkscrew.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, general modding

#5242 Scpui Mission Log
  code/hud/hudmessage.h
  code/mission/missionlog.cpp
  code/mission/missionlog.h
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/missionlog.cpp
  code/scripting/api/objs/missionlog.h
  code/source_groups.cmake
Labels: enhancement, ui, scripting

#5239 SCPUI methods for the Game Help UI
  code/gamehelp/gameplayhelp.cpp
  code/gamehelp/gameplayhelp.h
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/gamehelp.cpp
  code/scripting/api/objs/gamehelp.h
  code/source_groups.cmake
Labels: ui, scripting

#5282 FIX: Incorrect gamma calculations in shaders.
  code/def_files/data/effects/main-f.sdr
Labels: fix, graphics

#5256 Expose texture filtering as a built-in option
  code/graphics/opengl/gropengltexture.cpp
Labels: enhancement, graphics, ui

#5280 Scpui API for medals access
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/medals.cpp
  code/scripting/api/objs/medals.h
  code/scripting/api/objs/player.cpp
  code/scripting/api/objs/rank.cpp
  code/scripting/api/objs/rank.h
  code/source_groups.cmake
Labels: enhancement, ui, scripting

#5101 fredTunes, Fredify, Fred Music, or whatever. It's a music player.
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  fred2/CMakeLists.txt
  fred2/fred.cpp
  fred2/fred.h
  fred2/fred.rc
  fred2/fredrender.cpp
  fred2/fredview.cpp
  fred2/fredview.h
  fred2/mainfrm.cpp
  fred2/musicplayerdlg.cpp
  fred2/musicplayerdlg.h
  fred2/res/next.bmp
  fred2/res/play.bmp
  fred2/res/prev.bmp
  fred2/res/stop.bmp
  fred2/resource.h
  fred2/textviewdlg.cpp
  fred2/textviewdlg.h
Labels: fred, feature

#5289 restored the keyboard hotkey for envmap export.
  code/lab/manager/lab_manager.cpp
Labels: Lab

#5287 Revert "synchronize simulation timestamps across the entire frame"
  code/io/timer.cpp
  code/io/timer.h
  freespace2/freespace.cpp
Labels: regression, fix

#4835 Generic Lua Multiplayer RPC
  code/globalincs/pstypes.h
  code/network/multi.cpp
  code/network/multi.h
  code/network/multi_lua.cpp
  code/network/multi_lua.h
  code/network/multimsgs.h
  code/object/object.h
  code/parse/sexp.h
  code/scripting/ade.cpp
  code/scripting/ade.h
  code/scripting/ade_api.h
  code/scripting/api/libs/multi.cpp
  code/scripting/api/objs/ai_helper.cpp
  code/scripting/api/objs/audio_stream.cpp
  code/scripting/api/objs/briefing.cpp
  code/scripting/api/objs/bytearray.cpp
  code/scripting/api/objs/bytearray.h
  code/scripting/api/objs/cmd_brief.cpp
  code/scripting/api/objs/debriefing.cpp
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/enums.h
  code/scripting/api/objs/gameevent.cpp
  code/scripting/api/objs/gameevent.h
  code/scripting/api/objs/gamestate.cpp
  code/scripting/api/objs/gamestate.h
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/oswpt.cpp
  code/scripting/api/objs/parse_object.cpp
  code/scripting/api/objs/parse_object.h
  code/scripting/api/objs/rpc.cpp
  code/scripting/api/objs/rpc.h
  code/scripting/api/objs/ship_bank.cpp
  code/scripting/api/objs/shipwepselect.cpp
  code/scripting/api/objs/subsystem.cpp
  code/scripting/api/objs/subsystem.h
  code/scripting/api/objs/vecmath.cpp
  code/scripting/api/objs/vecmath.h
  code/scripting/lua.cpp
  code/source_groups.cmake
Labels: multi, scripting, feature

#5134 Parse and save asteroids by name
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: cleanup

#5286 Force expand wings instead of toggle for scpui
  code/mission/missionhotkey.cpp
  code/mission/missionhotkey.h
  code/scripting/api/libs/ui.cpp
Labels: enhancement, ui, scripting

#5290 Dehardcode Command arrival message chance
  code/mission/missionmessage.cpp
  code/mission/missionmessage.h
  code/mission/missionparse.cpp
Labels: enhancement, Requested by Active Mod

#5295 No overlapping turret sounds
  code/ai/aiturret.cpp
  code/scripting/api/objs/subsystem.cpp
Labels: fix

#5294 fix IFF logic for teams that attack themselves
  code/ai/aicode.cpp
  code/weapon/weapons.cpp
Labels: fix

#5288 Add "no-first-wave-message" wing flag
  code/mission/missionparse.cpp
  code/ship/ship.cpp
  code/ship/ship_flags.h
  fred2/fred.rc
  fred2/missionsave.cpp
  fred2/resource.h
  fred2/wing_editor.cpp
  fred2/wing_editor.h
  qtfred/src/mission/missionsave.cpp
Labels: enhancement

#5293 additional constraint on Command arrival messages
  code/mission/missionparse.cpp
Labels: fix
