Repository scp-fs2open/fs2open.github.com, pull requests merged in 2023-06, with the labels that each got.

#5438 Default profile name needs to be added after reset()
  code/lighting/lighting_profiles.cpp
Labels: cleanup, fix

#5435 Flags to see if a ship or weapon class is player allowed
  code/scripting/api/objs/shipclass.cpp
  code/scripting/api/objs/weaponclass.cpp
Labels: enhancement, scripting

#5401 Enhance jump node handling
  code/hud/hudbrackets.cpp
  code/hud/hudtargetbox.cpp
  code/jumpnode/jumpnode.cpp
  code/jumpnode/jumpnode.h
  code/mission/missionparse.cpp
  code/missionui/missionbrief.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/CMakeLists.txt
  fred2/fred.cpp
  fred2/fred.h
  fred2/fred.rc
  fred2/fredrender.cpp
  fred2/fredview.cpp
  fred2/fredview.h
  fred2/jumpnodedlg.cpp
  fred2/jumpnodedlg.h
  fred2/mainfrm.cpp
  fred2/management.cpp
  fred2/missionsave.cpp
  fred2/resource.h
  fred2/waypointpathdlg.cpp
  qtfred/src/mission/missionsave.cpp
Labels: enhancement

#5433 Sexp tree searching and filtering
  code/ai/aigoals.cpp
  code/globalincs/systemvars.h
  code/globalincs/utility.h
  code/hud/hudtarget.cpp
  code/mission/missionmessage.cpp
  code/mission/missiontraining.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp/sexp_lookup.cpp
  code/parse/sexp/sexp_lookup.h
  code/source_groups.cmake
  fred2/CMakeLists.txt
  fred2/OperatorComboBox.cpp
  fred2/OperatorComboBox.h
  fred2/eventeditor.cpp
  fred2/resource.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: sexps, fred, feature

#5439 Fixes for lab backgrounds and curve initialization
  code/lab/renderer/lab_renderer.cpp
  qtfred/src/mission/management.cpp
Labels: cleanup, fix, qtfred, Lab

#5441 Lua access to default countermeasure class
  code/scripting/api/objs/shipclass.cpp
Labels: enhancement, scripting

#5440 add game_settings.tbl option to enable HUD drop shadows by default
  code/mod_table/mod_table.cpp
Labels: enhancement, Requested by Active Mod

#5442 some refinements for retiming of object collision pairs
  code/autopilot/autopilot.cpp
  code/object/objcollide.cpp
  code/object/objcollide.h
  code/parse/sexp.cpp
  code/scripting/api/objs/object.cpp
Labels: enhancement, fix

#5443 some updates to the lighting profile code
  code/globalincs/adjustment.cpp
  code/globalincs/adjustment.h
  code/graphics/opengl/gropenglpostprocessing.cpp
  code/lab/dialogs/lab_ui.cpp
  code/lighting/lighting_profiles.cpp
  code/lighting/lighting_profiles.h
  fred2/missionsave.cpp
  fred2/weaponeditordlg.cpp
  qtfred/src/main.cpp
  qtfred/src/mission/management.cpp
  qtfred/src/mission/management.h
  qtfred/src/mission/missionsave.cpp
Labels: cleanup, fix

#5407 Fix 5405
  code/io/joy-sdl.cpp
  code/io/joy.h
Labels: fix, controls

#5449 Fix typo and copy/paste error
  code/asteroid/asteroid.cpp
Labels: fix

#5445 OpenGL Capability Handling
  code/cmdline/cmdline.cpp
  code/def_files/data/effects/main-g.sdr
  code/graphics/2d.h
  code/graphics/material.cpp
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropenglshader.cpp
  code/mod_table/mod_table.cpp
  code/model/modelread.cpp
Labels: fix, graphics, opengl

#5446 Make lasers less kinky
  code/def_files/data/effects/batched-f.sdr
  code/def_files/data/effects/batched-v.sdr
  code/graphics/2d.h
  code/graphics/opengl/gropengltnl.cpp
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/render/batching.cpp
  code/render/batching.h
  code/weapon/trails.cpp
Labels: fix, graphics

#5450 Validate chunk size to avoid align crash and add align skip flag
  code/cmdline/cmdline.cpp
  code/model/modelread.cpp
Labels: fix, models

#5454 Fix AI subsys reposition oversight
  code/ai/aibig.cpp
Labels: fix, ai

#5455 Fix check for shadows
  code/cmdline/cmdline.cpp
  code/graphics/2d.cpp
  code/mod_table/mod_table.cpp
Labels: fix

#5452 Update Some Newish CM Options to Floats
  code/ai/aicode.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, fix

#5456 handle special characters in additional places in FRED
  code/localization/localize.cpp
  fred2/campaigneditordlg.cpp
  fred2/management.cpp
  fred2/management.h
  fred2/missionnotesdlg.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/Editor.h
  qtfred/src/mission/dialogs/CampaignEditorDialogModel.cpp
  qtfred/src/mission/dialogs/MissionSpecDialogModel.cpp
Labels: fix, qtfred, fred

#5457 fix angle conversions in FRED
  code/mission/missionparse.cpp
  fred2/bgbitmapdlg.cpp
Labels: fix, fred

#5318 add per-species warp effects
  code/gamesnd/gamesnd.cpp
  code/gamesnd/gamesnd.h
  code/ship/ship.cpp
  code/species_defs/species_defs.cpp
  code/species_defs/species_defs.h
  fred2/management.cpp
  freespace2/freespace.cpp
  qtfred/src/main.cpp
  qtfred/src/mission/management.cpp
  qtfred/src/mission/management.h
Labels: enhancement, general modding, Requested by Active Mod

#5444 refinements of jump node features
  code/hud/hudbrackets.cpp
  code/hud/hudtargetbox.cpp
  code/jumpnode/jumpnode.cpp
  code/jumpnode/jumpnode.h
  code/mission/missionparse.cpp
  code/parse/sexp.cpp
  fred2/jumpnodedlg.cpp
  fred2/jumpnodedlg.h
  fred2/missionsave.cpp
  fred2/sexp_tree.cpp
  qtfred/src/mission/missionsave.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: cleanup, fix, qtfred, fred

#5465 Fix crash that can occur due to invalid glow point bank
  code/model/modelrender.cpp
Labels: fix

#5467 Decouple MSAA from deferred_end
  code/graphics/2d.h
  code/graphics/grstub.cpp
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropengldeferred.cpp
  code/graphics/opengl/gropengldeferred.h
  code/graphics/vulkan/vulkan_stubs.cpp
  code/object/objectsort.cpp
  code/ship/ship.cpp
Labels: fix, graphics

#5462 allow getting of mission info even for files with long names
  code/mission/missionparse.cpp
  fred2/freddoc.cpp
  fred2/freddoc.h
  fred2/missionsave.cpp
  fred2/missionsave.h
Labels: fix, fred

#5463 Fix issues with campaign-persistent containers
  code/mission/missioncampaign.cpp
  code/pilotfile/csg.cpp
Labels: fix, sexps, pilot file

#5471 fix Assertion in turret_swarm_set_up_info
  code/weapon/swarm.cpp
Labels: fix

#5469 tweak filename length check for PNGs
  code/bmpman/bmpman.cpp
Labels: fix, graphics

#5473 Remove `max_pixel_w > 0` assertion from `split_str_once()`.
  code/parse/parselo.cpp
Labels: cleanup, fix
