Repository scp-fs2open/fs2open.github.com, pull requests merged in 2024-03, with the labels that each got.

#5974 use C++ casts for floating.h and floating.cpp
  code/math/floating.cpp
  code/math/floating.h
Labels: cleanup

#5925 Animation Drivers for Cockpits
  code/menuui/techmenu.cpp
  code/missionui/missionbrief.cpp
  code/model/animation/modelanimation.cpp
  code/model/animation/modelanimation.h
  code/model/animation/modelanimation_driver.cpp
  code/model/model.h
  code/model/modelread.cpp
  code/model/modelrender.cpp
  code/ship/ship.cpp
  code/starfield/starfield.cpp
  code/weapon/weapons.cpp
Labels: enhancement, models

#5956 several coverity fixes
  code/ai/aiturret.cpp
  code/graphics/opengl/gropenglopenxr.cpp
  code/iff_defs/iff_defs.cpp
  code/parse/sexp.cpp
  code/scripting/api/libs/ui.cpp
  code/ship/awacs.cpp
Labels: coverity, fix

#5997 allow targeting subsystems on already targeted ship under reticule
  code/hud/hudtarget.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: enhancement, gameplay

#6005 add extra ways to modify background elements in missions
  code/gamesnd/gamesnd.h
  code/globalincs/vmallocator.h
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/background_element.cpp
  code/starfield/starfield.cpp
  code/starfield/starfield.h
Labels: enhancement, scripting, Requested by Active Mod

#5971 Fix "missing" command brief data
  qtfred/src/mission/dialogs/CommandBriefingDialogModel.cpp
Labels: fix, qtfred

#5992 Change special IFF color `#define`s into `extern int`s.
  code/iff_defs/iff_defs.cpp
  code/iff_defs/iff_defs.h
Labels: enhancement, fix, general modding

#6022 Fix CTD with HUD Preset Switching
  code/hud/hudconfig.cpp
Labels: fix, HUD, Point Release Candidate

#5928 Allow lua to lock/unlock cutscenes
  code/scripting/api/objs/techroom.cpp
Labels: scripting, Requested by Active Mod

#6012 scripting refactor to compose handle types
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/model.h
  code/scripting/api/objs/ship_bank.cpp
  code/scripting/api/objs/ship_bank.h
  code/scripting/api/objs/sound.cpp
  code/scripting/api/objs/sound.h
Labels: scripting, refactor

#5849 Make Active_games_head an SCP_list
  code/network/multi.cpp
  code/network/multi.h
  code/network/multiui.cpp
  code/network/multiutil.cpp
  code/network/multiutil.h
Labels: cleanup

#5934 Code to check if a medal is rank or badge
  code/scripting/api/objs/medals.cpp
  code/scripting/api/objs/medals.h
Labels: enhancement, cleanup, scripting

#5987 make several miscellaneous timestamps type-safe
  code/mission/missionhotkey.cpp
  code/mission/missionmessage.cpp
  code/object/objectsnd.cpp
  code/ship/awacs.cpp
  code/ship/ship.cpp
  code/weapon/trails.cpp
  code/weapon/trails.h
  code/weapon/weapons.cpp
Labels: refactor, timer/timestamp

#5936 Expose parse skip_to_string
  code/scripting/api/libs/parse.cpp
Labels: enhancement, scripting

#6028 clean up and update macOS bundle info
  freespace2/resources.cmake
  freespace2/resources/mac/Info.plist.in
  freespace2/resources/mac/InfoPlist.strings.in
Labels: mac

#6006 allow invalid arguments to be nil
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/scripting/ade.h
  code/scripting/ade_args.h
  code/scripting/api/libs/base.cpp
Labels: enhancement, scripting, refactor

#5958 Lua method to get the number of object sounds
  code/scripting/api/objs/object.cpp
Labels: sound, scripting

#5964 Add opf custom string as a lua sexp return type
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp/LuaSEXP.cpp
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: feature

#6013 Fix message api out of bounds check
  code/scripting/api/objs/message.cpp
Labels: fix

#6030 Fix crash when right-clicking on a container modifier
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, qtfred, fred

#6031 Handle container data nodes correctly with eval_num()
  code/parse/sexp.cpp
Labels: fix, sexps

#6019 Add `$player orders afterburn hard` flag
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aigoals.cpp
Labels: enhancement, ai

#6036 remove Docker setup for standalone servers
  .github/workflows/build-standalone.yaml
  docker/build.sh
  docker/standalone/Dockerfile
  docker/standalone/fs2_open.ini
  docker/standalone/multi.cfg
Labels: ci

#6035 enhancements for submodel collisions
  code/model/modelcollide.cpp
  code/object/collidedebrisship.cpp
  code/object/collideshipship.cpp
  code/object/collideshipweapon.cpp
  code/object/objcollide.cpp
  code/object/objcollide.h
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/object.cpp
  code/scripting/global_hooks.cpp
  code/weapon/beam.cpp
Labels: enhancement, scripting, Requested by Active Mod

#5937 some parse upgrades
  code/ai/aicode.cpp
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/network/multi_ingame.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/parse_object.cpp
  code/scripting/api/objs/ship.cpp
  code/scripting/api/objs/wing.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipfx.cpp
Labels: refactor

#5845 Scpui multi pxo api
  code/network/chat_api.cpp
  code/network/chat_api.h
  code/network/multi_pxo.cpp
  code/network/multi_pxo.h
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/multi_objects.cpp
  code/scripting/api/objs/multi_objects.h
  code/source_groups.cmake
Labels: enhancement, multi, ui, scripting

#6040 Default post processing to on because so many things require it
  code/graphics/2d.cpp
Labels: fix, graphics, Point Release Candidate

#6034 Add scripted model 'lightning' arcs
  code/model/model.h
  code/model/modelread.cpp
  code/model/modelrender.cpp
  code/object/object.cpp
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipfx.cpp
Labels: enhancement, scripting

#6041 improve set-support-ship description
  code/parse/sexp.cpp
Labels: sexps, documentation

#6016 fix help descriptions for string-greater-than and string-less-than
  code/parse/sexp.cpp
Labels: fix, sexps, documentation

#6020 Fix retail options not saving
  code/menuui/optionsmenu.cpp
  code/menuui/optionsmenu.h
  code/menuui/optionsmenumulti.cpp
  code/options/OptionsManager.cpp
  code/options/OptionsManager.h
Labels: fix

#5850 Convert multi team chat to use a struct/list setup
  code/missionui/chatbox.cpp
  code/missionui/chatbox.h
Labels: cleanup, ui

#6043 Add lua function to validate a string as a valid IP
  code/scripting/api/libs/options.cpp
Labels: enhancement, scripting

#6046 Default framebuffer effects to off
  code/graphics/2d.cpp
Labels: cleanup

#6047 Add AI Flag to `align to target when guarding stationary ship`
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aicode.cpp
Labels: enhancement, ai

#6050 add a HUD virtvar for contrast
  code/hud/hud.cpp
  code/hud/hud.h
  code/scripting/api/libs/hud.cpp
  code/starfield/starfield.cpp
Labels: enhancement, HUD, scripting, Requested by Active Mod

#6049 add getStringHeight and getStringSize
  code/scripting/api/libs/graphics.cpp
Labels: enhancement, scripting, Requested by Active Mod

#6042 Allow skipping using retail mainhall defaults
  code/menuui/mainhallmenu.cpp
Labels: enhancement, ui

#6055 add ShipBSubmodel to ship collisions
  code/object/collideshipship.cpp
  code/scripting/global_hooks.cpp
Labels: enhancement, scripting, Requested by Active Mod

#6056 update Fix_ai_path_order_bug for new waypoint options
  code/ai/aicode.cpp
Labels: fix, Requested by Active Mod

#6023 add weapon preloader
  code/parse/sexp.cpp
Labels: enhancement, Requested by Active Mod

#5894 Coverity: Change many auto calls to const auto& to avoid unnecessary copies.
  code/controlconfig/controlsconfig.cpp
  code/graphics/light.cpp
  code/graphics/matrix.cpp
  code/graphics/opengl/gropenglpostprocessing.cpp
  code/lab/dialogs/lab_ui_helpers.cpp
  code/parse/sexp/sexp_lookup.cpp
  code/scripting/ade.cpp
  code/scripting/api/libs/base.cpp
  code/scripting/api/libs/ui.cpp
  test/src/actions/expression/test_ExpressionParser.cpp
  test/src/scripting/doc_parser.cpp
Labels: coverity, fix

#5893 Fix coverity time t issues
  code/network/multi.cpp
  code/network/multi.h
  code/network/multi_log.cpp
  code/network/multiutil.cpp
  freespace2/freespace.cpp
Labels: coverity, fix

#6014 fix a few lighting bugs
  code/graphics/opengl/gropengldeferred.cpp
  code/graphics/opengl/gropenglpostprocessing.cpp
  code/lighting/lighting.cpp
  code/lighting/lighting.h
  code/missionui/missionscreencommon.cpp
  code/ship/shipfx.cpp
  code/ship/shipfx.h
  code/starfield/starfield.cpp
  freespace2/freespace.cpp
Labels: fix, graphics

#6060 fix crash caused by using a moved variable
  code/parse/sexp/sexp_lookup.cpp
Labels: fix

#6061 Don't init the debrief ui in API mode
  code/missionui/missiondebrief.cpp
Labels: fix

#5927 Basic implementation of some audio options in-game
  code/localization/localize.cpp
  code/sound/ds.cpp
  code/sound/openal.cpp
  code/sound/openal.h
Labels: sound, ui

#5924 Cockpit fov option
  code/camera/camera.cpp
  code/camera/camera.h
  code/cmdline/cmdline.cpp
  code/localization/localize.cpp
Labels: graphics, ui

#6065 additional lighting fixes
  code/lighting/lighting.cpp
  freespace2/freespace.cpp
Labels: fix, graphics, Lab

#6070 Fix an issue with animation directions
  code/model/animation/modelanimation.cpp
Labels: fix, models, Point Release Candidate

#6066 add "override submodel impact" subsystem flag
  code/model/model_flags.h
  code/ship/ship.cpp
  code/ship/shiphit.cpp
Labels: enhancement, Requested by Active Mod

#6067 fix fixed-missile-detonation
  code/weapon/weapons.cpp
Labels: fix, Requested by Active Mod

#6063 allow boolean and numeric scripted SEXPs to return special values
  code/parse/sexp/LuaSEXP.cpp
  code/parse/sexp/LuaSEXP.h
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/enums.h
Labels: enhancement, scripting

#5978 Add runtime flag to split up the main render shader
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
  code/decals/decals.cpp
  code/def_files/data/effects/main-f.sdr
  code/def_files/data/effects/main-g.sdr
  code/def_files/data/effects/main-v.sdr
  code/def_files/data/effects/main_large.sdr
  code/def_files/data/effects/main_small.sdr
  code/def_files/data/effects/model_shader_flags.h
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/graphics/material.cpp
  code/graphics/material.h
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropenglshader.cpp
  code/graphics/opengl/gropengltnl.cpp
  code/graphics/uniforms.cpp
  code/graphics/util/UniformBufferManager.cpp
  code/mod_table/mod_table.cpp
  code/model/modelread.cpp
  code/model/modelrender.cpp
  code/render/batching.cpp
  code/source_groups.cmake
  code/tracing/tracing.cpp
Labels: fix, graphics, refactor

#5870 add a new check to the Voice Acting Manager
  fred2/fred.rc
  fred2/resource.h
  fred2/voiceactingmanager.cpp
  fred2/voiceactingmanager.h
Labels: enhancement, fred

#6074 speed up FRED reloading with this one weird trick
  code/mission/missionparse.h
  fred2/campaigntreewnd.cpp
  fred2/freddoc.cpp
  fred2/management.cpp
  fred2/management.h
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/Editor.h
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
Labels: enhancement, qtfred, fred

#4210 QTFred Loadout Editor
  code/ship/ship.cpp
  qtfred/source_groups.cmake
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/Editor.h
  qtfred/src/mission/dialogs/LoadoutEditorDialogModel.cpp
  qtfred/src/mission/dialogs/LoadoutEditorDialogModel.h
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
  qtfred/src/ui/dialogs/LoadoutDialog.cpp
  qtfred/src/ui/dialogs/LoadoutDialog.h
  qtfred/src/ui/dialogs/TeamLoadoutDialog.cpp
  qtfred/src/ui/dialogs/TeamLoadoutDialog.h
  qtfred/ui/FredView.ui
  qtfred/ui/LoadoutDialog.ui
  qtfred/ui/TeamLoadoutDialog.ui
Labels: qtfred, required feature

#5887 check for potential issues in FRED missions
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/campaigntreewnd.cpp
  fred2/fred.cpp
  fred2/fred.rc
  fred2/fredrender.cpp
  fred2/fredrender.h
  fred2/fredview.cpp
  fred2/fredview.h
  fred2/resource.h
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/Editor.h
  qtfred/src/mission/EditorViewport.h
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
  qtfred/ui/FredView.ui
Labels: enhancement, qtfred, fred

#6002 allow game_settings options to be read in any order
  code/ai/ai_profiles.cpp
  code/mod_table/mod_table.cpp
Labels: enhancement

#6069 Add bad-rearm-time sexp
  code/ai/ai.h
  code/ai/aicode.cpp
  code/iff_defs/iff_defs.cpp
  code/iff_defs/iff_defs.h
  code/parse/sexp.cpp
Labels: enhancement, sexps
