Repository scp-fs2open/fs2open.github.com, pull requests merged in 2024-12, with the labels that each got.

#6221 create a `process_ship_subsystems` routine for subsystem operations
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: sexps, refactor

#6439 add scripting support for weapon class "turret names"
  code/hud/hudtargetbox.cpp
  code/scripting/api/objs/subsystem.cpp
  code/scripting/api/objs/weaponclass.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: enhancement, Requested by Active Mod

#6449 add nebula-set-range
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, sexps

#6438 allow the mod title and version to be displayed independently
  code/menuui/mainhallmenu.cpp
Labels: enhancement, ui

#6319 Modular curves for weapon attributes during lifetime
  code/globalincs/type_traits.h
  code/io/keycontrol.cpp
  code/object/collideshipweapon.cpp
  code/object/collideweaponweapon.cpp
  code/object/object.cpp
  code/parse/encrypt.cpp
  code/parse/encrypt.h
  code/ship/shiphit.cpp
  code/ship/shiphit.h
  code/source_groups.cmake
  code/utils/RandomRange.h
  code/utils/modular_curves.h
  code/weapon/beam.cpp
  code/weapon/beam.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement

#6322 QtFRED: Custom Warp Dialog
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/ShipEditor/ShipCustomWarpDialogModel.cpp
  qtfred/src/mission/dialogs/ShipEditor/ShipCustomWarpDialogModel.h
  qtfred/src/ui/dialogs/ShipEditor/ShipCustomWarpDialog.cpp
  qtfred/src/ui/dialogs/ShipEditor/ShipCustomWarpDialog.h
  qtfred/src/ui/dialogs/ShipEditor/ShipEditorDialog.cpp
  qtfred/src/ui/dialogs/ShipEditor/ShipEditorDialog.h
  qtfred/ui/ShipCustomWarpDialog.ui
Labels: qtfred

#6459 Fix maneuvering thruster initialization
  code/ship/ship.h
Labels: fix, graphics

#6452 default the connection speed to Fast even if it has been set to None
  code/network/multiutil.cpp
Labels: multi

#6463 fix sexp_ship_deal_with_subsystem_flag()
  code/parse/sexp.cpp
Labels: fix, sexps

#6455 STL fixes and cleanup
  code/ai/aigoals.h
  code/globalincs/pstypes.h
  code/globalincs/vmallocator.h
  code/iff_defs/iff_defs.cpp
  code/mission/missionparse.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/ship/ship.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
  tools/embedfile/embedfile.cpp
Labels: cleanup, refactor

#6446 fix ship:warpIn() behavior for docked ships
  code/object/objectdock.cpp
  code/object/objectdock.h
  code/scripting/api/objs/ship.cpp
  code/ship/shipfx.cpp
Labels: fix, gameplay, Requested by Active Mod

#6424 add $Substitute Music: for credits.tbl
  code/menuui/credits.cpp
  code/menuui/credits.h
  code/scripting/api/libs/ui.cpp
Labels: enhancement, sound, Requested by Active Mod

#6468 Fix ImGUI input flag handling
  code/osapi/osapi.cpp
Labels: fix, ui

#6399 Add underlining as a custom decorator
  code/scpui/RocketDecorators.cpp
  code/scpui/RocketDecorators.h
  code/scpui/RocketDecoratorsInstancer.cpp
  code/scpui/RocketDecoratorsInstancer.h
  code/scpui/rocket_ui.cpp
  code/source_groups.cmake
Labels: enhancement, Requested by Active Mod

#6338 Upgrade head ani handling
  code/hud/hudmessage.cpp
  code/mission/missionmessage.cpp
  code/mission/missionmessage.h
Labels: feature, Requested by Active Mod

#6474 Weapon light bugfix
  code/graphics/color.cpp
  code/graphics/color.h
  code/object/object.cpp
Labels: fix, graphics

#6426 fix a few bugs in the Vasudan heads cheat
  code/menuui/mainhallmenu.cpp
  code/menuui/mainhallmenu.h
Labels: fix, ui

#6443 improve campaign file extension handling
  code/exceptionhandler/exceptionhandler.cpp
  code/globalincs/windebug.cpp
  code/menuui/readyroom.cpp
  code/mission/missioncampaign.cpp
  code/model/modelread.cpp
  code/osapi/dialogs.cpp
  code/pilotfile/csg.cpp
  code/scripting/api/objs/player.cpp
  code/utils/string_utils.h
  code/windows_stub/stubs.cpp
Labels: fix, Requested by Active Mod

#6453 enhance the add-goal and remove-goal sexps
  code/ai/aigoals.cpp
  code/ai/aigoals.h
  code/parse/sexp.cpp
  freespace2/freespace.cpp
Labels: enhancement, sexps, Requested by Active Mod

#6482 Add FSO_BUILD_WITH_DISCORD cmake option
  CMakeLists.txt
  code/CMakeLists.txt
  code/libs/discord/discord.cpp
  code/mod_table/mod_table.cpp
  lib/CMakeLists.txt
Labels: build

#6484 Weapon light followup
  code/graphics/color.cpp
  code/graphics/color.h
  code/object/object.cpp
Labels: cleanup, graphics

#6486 Fixes Joystick Hat Labeling
  code/controlconfig/controlsconfigcommon.cpp
Labels: regression, fix, controls, localization / translation

#6479 Update JOY_NUM_BUTTONS to 128
  code/io/joy.h
Labels: enhancement, controls

#6480 Ensure custom preferences path ends with path separator
  code/osapi/osapi.cpp
Labels: cleanup, fix

#6488 adjust-audio-volume adjustments
  code/sound/sound.cpp
Labels: cleanup, fix, sound

#6494 Fix warp flash option
  code/fireball/warpineffect.cpp
Labels: fix, graphics

#6492 add safeguards to the "immobile" flag migration
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/parse/sexp.cpp
  fred2/freddoc.cpp
  fred2/fredrender.cpp
  fred2/fredrender.h
  fred2/fredview.cpp
  fred2/management.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/EditorViewport.h
Labels: enhancement, sexps, fred

#6483 Add '-campaign' cmdline option to set current campaign
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
  code/mission/missioncampaign.cpp
Labels: discussion

#6451 add set-squadron-wings sexp
  code/hud/hudwingmanstatus.cpp
  code/hud/hudwingmanstatus.h
  code/math/floating.h
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, HUD, sexps
