Repository scp-fs2open/fs2open.github.com, pull requests merged in 2024-08, with the labels that each got.

#6284 fix a minor bug with directive marking
  code/mission/missiontraining.cpp
Labels: fix, timer/timestamp

#6260 some coverity fixes
  code/missionui/missionscreencommon.cpp
  code/missionui/missionscreencommon.h
  code/options/OptionsManager.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/scripting/api/objs/sexpvar.h
Labels: coverity

#6283 add is-species SEXP operator
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, fix, sexps

#6280 add scripting support for wing wave min/max delay
  code/scripting/api/objs/wing.cpp
Labels: enhancement, scripting, Requested by Active Mod

#6269 Beam slash curves
  code/weapon/beam.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement

#6288 Fix renderLeadCurrentTarget
  code/hud/hudtarget.cpp
Labels: fix, HUD

#6265 Friendly fire control flags and SEXP
  code/ai/ai_profiles.cpp
  code/ai/ai_profiles.h
  code/object/collideshipweapon.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/weapon/beam.cpp
  code/weapon/shockwave.cpp
  code/weapon/weapons.cpp
Labels: enhancement

#6264 Add offset for tabled particle effects
  code/ai/aibig.cpp
  code/ai/aiturret.cpp
  code/particle/ParticleSource.cpp
  code/particle/ParticleSource.h
  code/particle/ParticleSourceWrapper.cpp
  code/particle/ParticleSourceWrapper.h
  code/particle/effects/GenericShapeEffect.h
  code/particle/effects/SingleParticleEffect.cpp
  code/particle/effects/VolumeEffect.cpp
  code/particle/util/ParticleProperties.cpp
  code/particle/util/ParticleProperties.h
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/weapon/beam.cpp
  code/weapon/weapons.cpp
Labels: enhancement, particles

#6282 parameter deconfliction
  code/scripting/ade_external_serializer.h
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/oswpt.cpp
  code/scripting/api/objs/vecmath.cpp
Labels: cleanup

#6292 safety check for lua_tostring()
  code/globalincs/utility.h
  code/osapi/dialogs.cpp
  code/scripting/ade.cpp
  code/scripting/ade.h
  code/scripting/ade_args.cpp
  code/scripting/ade_args.h
  code/scripting/api/libs/base.cpp
  code/scripting/api/objs/file.cpp
Labels: fix, scripting

#6293 Remove some int3s from offscreen indicator drawing
  code/hud/hudtarget.cpp
Labels: cleanup, HUD

#6297 Stop constantly rechecking the options value for deferred lighting
  code/lighting/lighting.cpp
Labels: regression, fix, optimization

#6296 Switch options manager from signaling empty keys with exceptions to use optional<>
  code/options/Option.cpp
  code/options/Option.h
  code/options/OptionsManager.cpp
  code/options/OptionsManager.h
Labels: cleanup, regression, fix, optimization

#6299 Fix sorting of older but active directives
  code/mission/missiontraining.cpp
Labels: fix, HUD

#6302 Fixes CTD with new Friendly Fire Feature
  code/weapon/weapons.cpp
Labels: fix

#6305 fix template warnings when compiling 2d.cpp
  code/graphics/2d.cpp
Labels: cleanup

#6268 Remove some overzealous prints
  code/math/vecmat.cpp
  code/particle/effects/GenericShapeEffect.h
Labels: cleanup

#6303 Cleanup variable name in `weapon_do_area_effect` function
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: cleanup

#6308 Grant access to shipclass shield hitpoints value
  code/scripting/api/objs/shipclass.cpp
Labels: scripting, Requested by Active Mod

#6307 Fix WeaponClass.SwarmInfo
  code/scripting/api/objs/weaponclass.cpp
Labels: fix

#6306 Adds warning if cond-impact armor type not found.
  code/object/collideweaponweapon.cpp
  code/weapon/weapons.cpp
Labels: cleanup

#6311 fix waypoint marking
  fred2/fredview.cpp
Labels: fix, fred

#6286 improve sounds.tbl index ordering
  code/gamesnd/gamesnd.cpp
Labels: fix, sound

#6317 fix the mysterious crash in BWO
  code/menuui/readyroom.cpp
Labels: fix

#6312 add option in FRED to lock objects from being edited
  code/object/object_flags.h
  fred2/fred.rc
  fred2/fredrender.cpp
  fred2/fredview.cpp
  fred2/fredview.h
  fred2/resource.h
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/Editor.h
  qtfred/src/mission/EditorViewport.cpp
  qtfred/src/ui/FredView.cpp
  qtfred/src/ui/FredView.h
  qtfred/ui/FredView.ui
Labels: enhancement, qtfred, fred

#6304 implement don't-change-position and don't-change-orientation
  code/ai/aicode.cpp
  code/mission/mission_flags.h
  code/mission/missionparse.cpp
  code/object/collideshipship.cpp
  code/object/objcollide.cpp
  code/object/object.cpp
  code/object/object_flags.h
  code/parse/sexp.cpp
  code/physics/physics.cpp
  code/ship/ship.cpp
  fred2/fred.rc
  fred2/missionsave.cpp
  fred2/resource.h
  fred2/shipflagsdlg.cpp
  fred2/shipflagsdlg.h
  qtfred/src/mission/dialogs/ShipEditor/ShipFlagsDialogModel.cpp
  qtfred/src/mission/dialogs/ShipEditor/ShipFlagsDialogModel.h
  qtfred/src/mission/missionsave.cpp
  qtfred/src/ui/dialogs/ShipEditor/ShipFlagsDialog.cpp
  qtfred/src/ui/dialogs/ShipEditor/ShipFlagsDialog.h
  qtfred/ui/ShipFlagsDialog.ui
Labels: gameplay, feature

#6278 some timestamp refinements
  code/io/timer.cpp
  code/io/timer.h
  code/network/multi_obj.cpp
Labels: fix, timer/timestamp

#6314 Generic random distributions, including curve-based
  code/decals/decals.cpp
  code/decals/decals.h
  code/gamesnd/gamesnd.cpp
  code/math/curve.cpp
  code/math/curve.h
  code/nebula/neb.cpp
  code/nebula/neb.h
  code/particle/effects/ConeShape.h
  code/particle/effects/GenericShapeEffect.h
  code/particle/effects/SingleParticleEffect.cpp
  code/particle/effects/SingleParticleEffect.h
  code/particle/effects/VolumeEffect.cpp
  code/particle/effects/VolumeEffect.h
  code/particle/util/EffectTiming.cpp
  code/particle/util/EffectTiming.h
  code/particle/util/ParticleProperties.cpp
  code/particle/util/ParticleProperties.h
  code/sound/sound.h
  code/utils/RandomRange.h
Labels: enhancement

#6300 Accessibility IFF colors
  code/iff_defs/iff_defs.cpp
  code/iff_defs/iff_defs.h
  code/localization/localize.cpp
Labels: enhancement, Requested by Active Mod

#6321 Small optimization
  code/iff_defs/iff_defs.cpp
Labels: cleanup

#6262 Fix: Always check for nullptrs and make red-alert respect cur_waves from last mission
  code/missionui/redalert.cpp
  code/ship/ship.cpp
Labels: fix, general modding

#6323 follow-up to BWO crash fix
  code/controlconfig/controlsconfig.cpp
  code/menuui/readyroom.cpp
  code/mission/missionhotkey.cpp
Labels: fix, gameplay

#6318 Reset hotkey lines before populating
  code/mission/missionhotkey.cpp
  code/mission/missionhotkey.h
  code/scripting/api/libs/ui.cpp
Labels: fix

#6295 Upgraded Asteroid Field SEXPs
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: enhancement, sexps

#6324 fix deletion of looping sounds
  code/ship/ship.cpp
Labels: fix, sound, Requested by Active Mod

#6325 follow-up to probability curves
  code/gamesnd/gamesnd.cpp
  code/math/curve.cpp
  code/math/curve.h
  code/nebula/neb.h
  code/particle/effects/GenericShapeEffect.h
  code/particle/effects/VolumeEffect.cpp
  code/particle/effects/VolumeEffect.h
Labels: regression, fix

#6331 update detection of save version
  code/mission/missionparse.cpp
Labels: qtfred, fred

#6333 fix sound initialization
  code/gamesnd/gamesnd.cpp
Labels: fix, sound
