Repository scp-fs2open/fs2open.github.com, pull requests merged in 2024-06, with the labels that each got.

#6149 Make headon transition behavior consistent between laser and glow bitmaps
  code/weapon/weapons.cpp
Labels: enhancement, graphics

#6120 Fred autorecover
  code/cfile/cfile.h
  code/cfile/cfilesystem.cpp
  fred2/freddoc.cpp
  fred2/freddoc.h
  fred2/management.cpp
  fred2/management.h
  fred2/missionsave.cpp
  fred2/missionsave.h
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/Editor.h
  qtfred/src/mission/missionsave.cpp
  qtfred/src/mission/missionsave.h
  qtfred/src/mission/util.cpp
  qtfred/src/mission/util.h
  qtfred/src/ui/FredView.cpp
Labels: enhancement, qtfred, fred

#6173 Exposes the New Flight Cursor Mode to Scripting and Fixed Aiming Setting
  code/playerman/player.h
  code/playerman/playercontrol.cpp
  code/scripting/api/libs/controls.cpp
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/enums.h
  code/ship/ship.cpp
Labels: enhancement, scripting

#6100 convert model_h and submodel_h to use indexes
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/model.h
Labels: scripting, refactor, models

#6178 Expose Impact Damage Type to Scripting
  code/scripting/api/objs/ship.cpp
Labels: enhancement, scripting

#6177 fix compilation warnings
  code/graphics/opengl/gropenglopenxr.cpp
  code/math/floating.h
  code/network/multi_log.cpp
  code/weapon/weapons.cpp
Labels: cleanup

#6157 Fix beam particle velocity
  code/particle/ParticleSource.cpp
  code/particle/ParticleSourceWrapper.h
Labels: fix, graphics

#6182 Assorted beam fixes
  code/ai/ai_profiles.cpp
  code/ship/ship.cpp
  code/weapon/beam.cpp
  code/weapon/weapons.cpp
Labels: fix, gameplay

#6180 utility functions for counting and searching
  code/globalincs/utility.h
  code/parse/sexp.cpp
  code/scripting/api/objs/ship.cpp
Labels: enhancement

#6011 Split up debris and asteroid types
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
  code/mission/missionparse.cpp
  fred2/asteroideditordlg.cpp
  fred2/dumpstats.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/dialogs/AsteroidEditorDialogModel.cpp
  qtfred/src/mission/missionsave.cpp
Labels: cleanup

#6000 Scanning is chaos, let's make it sane
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/hud/hudtargetbox.h
  code/localization/localize.cpp
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/playerman/player.h
  code/playerman/playercontrol.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/ship_flags.h
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, cleanup

#5917 Ingame options respect mods
  code/localization/localize.cpp
  code/menuui/playermenu.cpp
  code/options/OptionsManager.cpp
  code/osapi/osregistry.cpp
  code/osapi/osregistry.h
Labels: enhancement, discussion, Requested by Active Mod

#6105 replace pointers with indexes in object_h
  code/actions/types/MoveToSubmodel.cpp
  code/actions/types/ParticleEffectAction.cpp
  code/actions/types/PlaySoundAction.cpp
  code/ai/ai.h
  code/ai/aicode.cpp
  code/camera/camera.cpp
  code/decals/decals.cpp
  code/object/object.cpp
  code/object/object.h
  code/particle/ParticleSource.cpp
  code/particle/ParticleSource.h
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/libs/hud.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/libs/testing.cpp
  code/scripting/api/objs/ai_helper.cpp
  code/scripting/api/objs/asteroid.cpp
  code/scripting/api/objs/beam.cpp
  code/scripting/api/objs/camera.cpp
  code/scripting/api/objs/debris.cpp
  code/scripting/api/objs/decaldefinition.cpp
  code/scripting/api/objs/fireball.cpp
  code/scripting/api/objs/model_path.cpp
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/order.cpp
  code/scripting/api/objs/particle.cpp
  code/scripting/api/objs/physics_info.cpp
  code/scripting/api/objs/shields.cpp
  code/scripting/api/objs/ship.cpp
  code/scripting/api/objs/ship_bank.cpp
  code/scripting/api/objs/subsystem.cpp
  code/scripting/api/objs/waypoint.cpp
  code/scripting/api/objs/weapon.cpp
  code/scripting/api/objs/wing.cpp
Labels: refactor

#6045 Allow player-specific options even when using In-Game Options
  code/menuui/optionsmenu.cpp
  code/menuui/optionsmenu.h
  code/menuui/optionsmenumulti.cpp
  code/options/OptionsManager.cpp
  code/options/OptionsManager.h
  code/pilotfile/csg.cpp
  code/pilotfile/plr.cpp
Labels: cleanup, refactor

#6179 Increase Lua safety
  code/scripting/lua.cpp
Labels: scripting

#6183 Follow-up to Unified Scanning
  code/playerman/player.h
  code/playerman/playercontrol.cpp
Labels: cleanup, fix

#6181 Make the $Shots parameter work for beams.
  code/ai/aiturret.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/weapon/beam.cpp
Labels: fix, gameplay

#6170 Arrival/Departure Paths Dialog
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/ShipEditor/ShipPathsDialogModel.cpp
  qtfred/src/mission/dialogs/ShipEditor/ShipPathsDialogModel.h
  qtfred/src/ui/dialogs/ShipEditor/ShipEditorDialog.cpp
  qtfred/src/ui/dialogs/ShipEditor/ShipEditorDialog.h
  qtfred/src/ui/dialogs/ShipEditor/ShipPathsDialog.cpp
  qtfred/src/ui/dialogs/ShipEditor/ShipPathsDialog.h
  qtfred/ui/ShipPathsDialog.ui
Labels: enhancement, fred

#6021 Unlimited Asteroid/Debris Field Types & Subtypes
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
  code/graphics/shadows.cpp
  code/hud/hudbrackets.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/mission/missionparse.cpp
  code/model/modelread.cpp
  code/object/collideshipship.cpp
  code/object/object.cpp
  code/object/objectsort.cpp
  code/parse/sexp.cpp
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/objs/object.cpp
  code/ship/shipfx.cpp
  code/weapon/beam.cpp
  fred2/asteroideditordlg.cpp
  fred2/asteroideditordlg.h
  fred2/dumpstats.cpp
  fred2/fred.rc
  fred2/missionsave.cpp
  fred2/resource.h
  fred2/sexp_tree.cpp
  qtfred/src/mission/dialogs/AsteroidEditorDialogModel.cpp
  qtfred/src/mission/dialogs/AsteroidEditorDialogModel.h
  qtfred/src/mission/missionsave.cpp
  qtfred/src/ui/dialogs/AsteroidEditorDialog.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: enhancement, cleanup, fred

#6186 Fix edge case in MSAA shader
  code/def_files/data/effects/msaa-f.sdr
Labels: fix, graphics

#6111 make mission log dynamic
  code/hud/hudmessage.cpp
  code/mission/missionlog.cpp
  code/mission/missionlog.h
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/missionlog.cpp
  code/scripting/api/objs/missionlog.h
Labels: general modding, refactor

#6190 make sure 'tactical' variants of disable and disarm are allowed
  code/def_files/data/tables/objecttypes.tbl
Labels: fix, ai, Requested by Active Mod

#6027 limit debug log spam from file shadows
  code/cfile/cfilesystem.cpp
Labels: cleanup

#6107 add API for glow point banks
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/model.h
Labels: scripting, refactor, models

#6192 add support for PXO's UDP hole punch feature
  code/network/gtrack.cpp
  code/network/gtrack.h
Labels: multi

#5003 Generalize linear interpolation
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/model/model.h
  code/network/multi_ingame.cpp
  code/network/multi_interpolate.cpp
  code/network/multi_interpolate.h
  code/network/multi_obj.cpp
  code/network/multi_obj.h
  code/object/collideshipship.cpp
  code/object/object.cpp
  code/object/object.h
  code/object/waypoint.cpp
  code/physics/physics_state.cpp
  code/physics/physics_state.h
  code/ship/ship.cpp
  code/source_groups.cmake
  freespace2/freespace.cpp
Labels: multi, physics, feature

#6195 fix data length bug in PXO hole punch packet
  code/network/gtrack.cpp
Labels: bug, multi

#4489 Simplify logic here
  code/mission/missionparse.cpp
Labels: cleanup, fred

#6159 Improve Volumetrics Performance
  code/def_files/data/effects/volumetric-f.sdr
  code/globalincs/pstypes.h
  code/graphics/opengl/gropengldeferred.cpp
  code/graphics/util/uniform_structs.h
  code/nebula/volumetrics.cpp
  code/nebula/volumetrics.h
  code/tracing/categories.cpp
  code/tracing/categories.h
Labels: enhancement, graphics, optimization

#6187 Fix Transparent Cockpits
  code/ship/ship.cpp
Labels: fix, graphics

#6198 Fix ingame options init bugs
  code/menuui/playermenu.cpp
  code/osapi/osregistry.cpp
Labels: fix

#6201 Follow-up to asteroids update #6021
  code/asteroid/asteroid.cpp
Labels: fix

#6202 One more follow-up to #6021
  code/asteroid/asteroid.cpp
  code/mission/missionparse.cpp
Labels: cleanup

#6209 clear Parse_names on mission init
  code/mission/missionparse.cpp
Labels: fix, fred

#6199 Prevent SCPUI flicker on Win11
  code/graphics/2d.cpp
Labels: fix, graphics, windows

#6204 Fix screenshudder option issue
  freespace2/freespace.cpp
Labels: fix

#6211 Followup to #6187
  code/ship/ship.cpp
Labels: fix, graphics

#6206 Don't kill paused messages
  code/mission/missionmessage.cpp
Labels: fix

#6184 Custom Strings for ships and weapons
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  code/scripting/api/objs/shipclass.cpp
  code/scripting/api/objs/weaponclass.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
  fred2/customstringsdlg.cpp
  fred2/customstringsdlg.h
Labels: enhancement

#6212 properly handle game sounds with numeric IDs
  code/gamesnd/gamesnd.cpp
  code/scripting/api/objs/sound.cpp
Labels: cleanup, fix, sound

#6215 Adds Voluemtrics Toggle SEXP
  code/graphics/opengl/gropengldeferred.cpp
  code/nebula/volumetrics.cpp
  code/nebula/volumetrics.h
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, sexps, Requested by Active Mod

#6142 Allow defining custom message types
  code/mission/missionmessage.cpp
  code/mission/missionmessage.h
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/parse/sexp/sexp_lookup.cpp
  fred2/sexp_tree.cpp
  fred2/sexp_tree.h
  qtfred/src/ui/widgets/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.h
Labels: enhancement, Requested by Active Mod

#6213 Cleanup message_kill_all
  code/io/keycontrol.cpp
  code/mission/missionmessage.cpp
  code/mission/missionmessage.h
Labels: cleanup

#6217 another follow-up to #6021
  code/mission/missionparse.cpp
Labels: fix
