Repository scp-fs2open/fs2open.github.com, pull requests merged in 2024-11, with the labels that each got.

#6329 Optional icon scaling
  code/localization/localize.cpp
  code/mission/missionbriefcommon.cpp
  code/mission/missionbriefcommon.h
  code/missionui/missionbrief.cpp
Labels: enhancement, ui, Requested by Active Mod

#6376 make malformed XSTR a release warning
  code/localization/localize.cpp
  code/parse/parselo.cpp
Labels: enhancement, localization / translation

#6410 hide variable -index SEXP operators in FRED
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: cleanup, qtfred, sexps, fred

#6261 refine timestamp_valid
  code/io/timer.h
Labels: coverity

#6412 handle connection speed in a user-friendly way
  code/network/multi_options.cpp
  code/network/multiutil.cpp
  code/network/psnet2.cpp
  code/network/psnet2.h
Labels: fix, multi

#6359 replace waypoint pointers with waypoint indexes
  code/ai/ai.h
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aigoals.h
  code/autopilot/autopilot.cpp
  code/autopilot/autopilot.h
  code/mission/missiontraining.cpp
  code/mission/missiontraining.h
  code/network/multi_obj.cpp
  code/object/waypoint.cpp
  code/object/waypoint.h
  code/parse/sexp.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/order.cpp
  code/scripting/api/objs/waypoint.cpp
  code/scripting/api/objs/waypoint.h
  code/ship/ship.cpp
  freespace2/freespace.cpp
Labels: fix, gameplay, refactor

#6413 sync upload and download artifacts
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/build-test.yaml
Labels: build, dependencies, github_actions

#6345 Grant lua access to countermeasure parameters
  code/scripting/api/objs/weaponclass.cpp
  code/weapon/weapons.cpp
Labels: enhancement, Requested by Active Mod

#6337 Remove model_pointer in favor of using model_number
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
  code/object/collideshipship.cpp
Labels: cleanup, Requested by Active Mod

#6342 Auto size font for screen resolutions
  code/graphics/software/font.cpp
Labels: feature, Requested by Active Mod

#6241 optimize collision code a bit
  code/object/collideshipweapon.cpp
  code/weapon/beam.cpp
Labels: coverity, gameplay, optimization

#6414 make mission skipping more robust
  code/mission/missioncampaign.cpp
  code/parse/sexp.cpp
Labels: fix

#6415 add is-true-for-duration sexp
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: sexps, feature

#6409 enhance sexp handling of generic subsystems
  code/model/model.h
  code/parse/sexp.cpp
  code/parse/sexp.h
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: enhancement, sexps

#6418 add hud drawing and pre-player-entry checks
  code/scripting/api/libs/hud.cpp
  code/scripting/api/libs/mission.cpp
  fred2/fredstubs.cpp
  freespace2/freespace.cpp
  freespace2/freespace.h
  qtfred/src/fredstubs.cpp
  test/src/test_stubs.cpp
Labels: gameplay, HUD, scripting, Requested by Active Mod

#6420 Define whether or not to render the game strings on the mainhall
  code/menuui/mainhallmenu.cpp
  code/menuui/mainhallmenu.h
Labels: enhancement

#6378 fix ai behavior when avoiding ship and weapon shockwaves
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aicode.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, fix, ai, Requested by Active Mod

#6423 allow ambient sound to be specified on a per-main-hall basis
  code/gamesnd/gamesnd.cpp
  code/gamesnd/gamesnd.h
  code/menuui/mainhallmenu.cpp
  code/menuui/mainhallmenu.h
Labels: enhancement, sound, Requested by Active Mod

#6403 revise Run FreeSpace menu option
  code/cmdline/cmdline.cpp
  fred2/fredview.cpp
Labels: enhancement, fix, fred

#6371 More Axes!
  code/controlconfig/controlsconfig.cpp
  code/controlconfig/controlsconfig.h
  code/controlconfig/controlsconfigcommon.cpp
  code/io/joy.h
  code/localization/localize.cpp
Labels: controls, localization / translation

#6425 Fix CTD from recent cycle expansion
  code/model/model.h
  code/ship/ship.cpp
Labels: fix

#6422 protect against weapon bank overflow
  code/mission/missionparse.cpp
Labels: cleanup, fix

#6433 Cycle expansion followup
  code/ship/ship.cpp
Labels: fix, general modding

#6428 fix DDV_ validation in FRED, especially DDV_MaxChars
  fred2/addvariabledlg.cpp
  fred2/bgbitmapdlg.cpp
  fred2/briefingeditordlg.cpp
  fred2/campaigneditordlg.cpp
  fred2/cmdbrief.cpp
  fred2/createwingdlg.cpp
  fred2/debriefingeditordlg.cpp
  fred2/eventeditor.cpp
  fred2/messageeditordlg.cpp
  fred2/missioncutscenesdlg.cpp
  fred2/missiongoalsdlg.cpp
  fred2/missionnotesdlg.cpp
  fred2/modifyvariabledlg.cpp
  fred2/shipeditordlg.cpp
Labels: fix, fred

#6434 enable or disable weapon icons according to bank compatibility
  code/globalincs/pstypes.h
  code/missionui/missionweaponchoice.cpp
Labels: fix, ui, Requested by Active Mod

#6437 improve bank-compatibility check
  code/missionui/missionweaponchoice.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: cleanup, fix, ui

#6435 re-add Update_window tracking
  fred2/fred.cpp
Labels: fix, fred

#6315 fix memory management in FontManager
  .clang-tidy
  code/graphics/software/FSFont.cpp
  code/graphics/software/FSFont.h
  code/graphics/software/FontManager.cpp
  code/graphics/software/FontManager.h
  code/graphics/software/NVGFont.cpp
  code/graphics/software/NVGFont.h
  code/graphics/software/VFNTFont.cpp
  code/graphics/software/font.cpp
  code/graphics/software/font.h
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/objs/font.cpp
  code/scripting/api/objs/font.h
  code/scripting/api/objs/hudgauge.cpp
  code/ui/window.cpp
  fred2/sexp_tree.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: fix, refactor

#6336 Actually compile with proper optimizations in a release build.
  CMakeLists.txt
  cmake/toolchain-apple-clang.cmake
  cmake/toolchain-clang.cmake
  cmake/toolchain-gcc.cmake
  code/menuui/playermenu.cpp
  code/model/modelread.cpp
  code/model/modelreplace.cpp
  code/network/gtrack.cpp
  code/network/psnet2.cpp
  code/network/psnet2.h
  code/network/ptrack.cpp
  code/network/valid.cpp
  code/osapi/osregistry.cpp
  code/ship/ship.cpp
  code/weapon/weapons.cpp
Labels: build

#6406 Add hud-set-xstr sexp
  code/mission/missiontraining.cpp
  code/mission/missiontraining.h
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: Requested by Active Mod

#6377 Allow beams to do energy leeching
  code/ship/shiphit.cpp
Labels: enhancement, gameplay

#6440 several small fixes
  code/hud/hudparse.cpp
  code/missionui/missionbrief.cpp
  code/nebula/neblightning.cpp
  code/scripting/api/objs/weaponclass.cpp
  code/ship/ship.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: fix, gameplay

#6330 Ttf font scaling option
  code/graphics/render.cpp
  code/graphics/software/FSFont.cpp
  code/graphics/software/FSFont.h
  code/graphics/software/FontManager.cpp
  code/graphics/software/FontManager.h
  code/graphics/software/NVGFont.cpp
  code/graphics/software/NVGFont.h
  code/graphics/software/VFNTFont.h
  code/graphics/software/font.cpp
  code/graphics/software/font.h
  code/localization/localize.cpp
  freespace2/freespace.cpp
Labels: enhancement, ui, Requested by Active Mod

#6341 Allow defining custom overhead line colors
  code/missionui/missionweaponchoice.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: feature

#6385 allow voice acting manager to handle non-wingman personas
  code/mission/missionmessage.cpp
  code/mission/missionmessage.h
  fred2/fred.rc
  fred2/resource.h
  fred2/voiceactingmanager.cpp
  fred2/voiceactingmanager.h
Labels: enhancement, fred

#6387 Support custom preferences path
  code/cmdline/cmdline.cpp
  code/osapi/osapi.cpp
Labels: enhancement

#6447 Beam cycle fix
  code/ship/ship.cpp
Labels: fix, Requested by Active Mod
