Repository scp-fs2open/fs2open.github.com, pull requests merged in 2024-07, with the labels that each got.

#6216 Clarify some SEXP operator documentation
  code/parse/sexp.cpp
Labels: cleanup, sexps

#6218 Adds conditional impact functionality.
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement

#6220 enhance stuff_int_list to allow turning off the warning
  code/parse/parselo.cpp
  code/parse/parselo.h
Labels: enhancement

#6219 enhance lock-perspective to also lock slew mode
  code/io/keycontrol.cpp
  code/io/keycontrol.h
  code/parse/sexp.cpp
  code/playerman/player.h
  code/playerman/playercontrol.cpp
  freespace2/freespace.cpp
Labels: sexps, Requested by Active Mod

#6214 Deprecate some commandlines and make some options not require restart
  code/cmdline/cmdline.cpp
  code/cmdline/cmdline.h
  code/fireball/warpineffect.cpp
  code/graphics/post_processing.cpp
  code/starfield/starfield.cpp
  code/weapon/shockwave.cpp
  code/weapon/shockwave.h
  freespace2/freespace.cpp
Labels: cleanup

#6185 Assign hud in ships.tbl
  code/hud/hud.cpp
  code/hud/hud.h
  code/hud/hudparse.cpp
  code/parse/sexp.cpp
  code/ship/ship.cpp
Labels: enhancement, cleanup, fix, Requested by Active Mod

#6224 fix coverity task
  .github/workflows/weekly-coverity-scan.yaml
Labels: fix, ci

#6225 fix poof alignment
  code/nebula/neb.cpp
Labels: fix

#6226 Save current preset name and use as default when saving new preset name
  code/controlconfig/controlsconfig.cpp
Labels: enhancement, controls, ui

#6229 Fix `short read` error with red alert csg file reading
  code/pilotfile/csg.cpp
Labels: cleanup, fix, pilot file

#6232 Several coverity fixes
  code/asteroid/asteroid.cpp
  code/cfile/cfilesystem.cpp
  code/controlconfig/controlsconfigcommon.cpp
  code/cutscene/ffmpeg/SubtitleDecoder.cpp
  code/decals/decals.cpp
  code/gamesnd/gamesnd.cpp
  code/globalincs/undosys.cpp
  code/hud/hudparse.cpp
  code/lab/dialogs/lab_ui.cpp
  code/lab/dialogs/lab_ui.h
  code/math/curve.cpp
  code/mission/missionparse.cpp
  code/mission/missiontraining.cpp
  code/parse/parselo.cpp
  code/parse/sexp.cpp
  code/parse/sexp/sexp_lookup.cpp
  code/particle/ParticleManager.cpp
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/model.cpp
  code/scripting/scripting.cpp
  code/scripting/util/LuaValueSerializer.cpp
  code/ship/awacs.cpp
  code/ship/ship.cpp
  code/stats/scoring.cpp
  code/weapon/beam.cpp
  code/weapon/weapons.cpp
Labels: coverity

#6234 Fix clang-tidy
  ci/linux/clang_tidy.sh
Labels: ci

#6236 Fix clang tidy again
  .clang-tidy
  ci/linux/clang_tidy.sh
Labels: ci

#6231 Fix unreliable Sounds index retrieval
  code/sound/ds.cpp
  code/sound/ds.h
  code/sound/sound.cpp
Labels: fix, sound

#6244 Make clang const correctness a little less aggressive
  .clang-tidy
Labels: ci

#6239 Respect tabled delay for arrival and backup messages
  code/mission/missionmessage.h
  code/mission/missionparse.cpp
Labels: fix

#6242 Fix Settings Localization IDs
  code/globalincs/systemvars.cpp
  code/graphics/2d.cpp
  code/nebula/neb.cpp
Labels: cleanup, fix, localization / translation

#6223 address 6010
  code/globalincs/utility.h
  code/math/curve.cpp
  code/particle/ParticleEffect.h
  code/particle/ParticleManager.cpp
  code/particle/ParticleManager.h
  code/particle/effects/GenericShapeEffect.h
  code/particle/effects/VolumeEffect.cpp
  code/particle/effects/VolumeEffect.h
  code/particle/particle.cpp
  code/particle/util/ParticleProperties.cpp
  lib/antlr4-cpp-runtime/runtime/src/tree/xpath/XPathLexer.cpp
  parsers/action_expression/generated/ActionExpressionLexer.cpp
  parsers/action_expression/generated/ActionExpressionParser.cpp
  parsers/arg_parser/generated/ArgumentListLexer.cpp
  parsers/arg_parser/generated/ArgumentListParser.cpp
Labels: cleanup, particles, optimization

#6233 Fix Insignia Checkbox in the Lab
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/jumpnode/jumpnode.cpp
  code/lab/renderer/lab_renderer.cpp
  code/menuui/techmenu.cpp
  code/missionui/missionscreencommon.cpp
  code/missionui/missionscreencommon.h
  code/model/model.h
  code/model/modelinterp.cpp
  code/model/modelrender.cpp
  code/model/modelrender.h
  code/ship/ship.cpp
  code/ship/ship_flags.h
  code/ship/shipfx.cpp
  code/starfield/starfield.cpp
  code/starfield/starfield.h
  code/weapon/weapons.cpp
  fred2/fredrender.cpp
  qtfred/src/mission/FredRenderer.cpp
Labels: fix, graphics, Lab

#6248 Bug fix for aspect invulnerability timing... again
  code/object/collideweaponweapon.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: fix, gameplay

#6250 only run the Coverity workflow on the SCP repository
  .github/workflows/weekly-coverity-scan.yaml
Labels: ci

#6245 Expose shockwave damage
  code/scripting/api/objs/weaponclass.cpp
Labels: scripting, feature, Requested by Active Mod

#1451 better stats handling when switching or resetting campaigns
  code/menuui/readyroom.cpp
  code/mission/missioncampaign.cpp
  code/mission/missioncampaign.h
  code/pilotfile/csg.cpp
  code/pilotfile/pilotfile.h
Labels: cleanup, discussion

#6251 fix incorrect processing of keys during ESC popup
  code/popup/popup.cpp
  code/popup/popup.h
Labels: fix, gameplay

#6252 Expose Minimum LoS Detection Radius
  code/ai/ai_profiles.cpp
  code/ai/ai_profiles.h
  code/ai/aicode.cpp
Labels: enhancement, ai, Requested by Active Mod

#6253 Ensure guards ignore protected attackers
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aicode.cpp
Labels: fix, ai

#6258 fix `NextFireTimestamp`
  code/io/timer.cpp
  code/scripting/api/objs/subsystem.cpp
Labels: fix, scripting

#6255 change atan2_safe to atan2
  code/hud/hudtarget.cpp
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/render/3ddraw.cpp
  code/render/3dmath.cpp
Labels: fix, fred

#6259 fix copy-paste error in timestamp_since
  code/io/timer.cpp
Labels: fix, timer/timestamp

#6235 Allow accepting a pilot without changing gamestate
  code/menuui/barracks.cpp
  code/menuui/barracks.h
  code/scripting/api/libs/ui.cpp
Labels: cleanup, fix, ui

#6243 Per weapon auto convergence
  code/object/object_flags.h
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/ship_flags.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: feature, Requested by Active Mod

#6257 Print in game options data to scripting output files
  code/scripting/doc_html.cpp
  code/scripting/doc_json.cpp
  code/scripting/lua.cpp
  code/scripting/scripting_doc.h
Labels: enhancement, cleanup, scripting

#6266 Disable clang misc-no-recursion
  .clang-tidy
Labels: ci

#6267 Fix SDL2 pkg-config name
  lib/SDL2.cmake
Labels: fix, build

#6270 Adds consts to parameters for a couple laser rendering functions.
  code/render/batching.cpp
  code/render/batching.h
Labels: cleanup

#6275 Fix a sound crash
  code/sound/sound.cpp
Labels: fix, sound, Requested by Active Mod

#6276 Slightly clean up RPC API
  code/globalincs/pstypes.h
  code/object/object.h
  code/parse/sexp.h
  code/scripting/ade_api.h
  code/scripting/ade_external_serializer.h
  code/scripting/api/objs/bytearray.h
  code/scripting/api/objs/enums.h
  code/scripting/api/objs/gameevent.h
  code/scripting/api/objs/gamestate.h
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/oswpt.cpp
  code/scripting/api/objs/parse_object.h
  code/scripting/api/objs/subsystem.h
  code/scripting/api/objs/vecmath.cpp
  code/scripting/api/objs/vecmath.h
  code/source_groups.cmake
Labels: cleanup

#6277 improve model texture parsing
  code/model/model.h
  code/model/modelread.cpp
Labels: cleanup

#6249 Interpolate particle spawning positions for moving spawner objects
  code/particle/ParticleSource.cpp
  code/particle/ParticleSource.h
  code/particle/effects/GenericShapeEffect.h
  code/particle/effects/SingleParticleEffect.cpp
  code/particle/effects/VolumeEffect.cpp
  code/particle/util/EffectTiming.cpp
  code/particle/util/EffectTiming.h
Labels: enhancement, particles

#6254 Conditional Impacts followup
  code/object/collideweaponweapon.cpp
  code/weapon/weapons.cpp
Labels: cleanup, particles
