Repository scp-fs2open/fs2open.github.com, pull requests merged in 2024-02, with the labels that each got.

#5963 Fix assert when adding custom strings
  fred2/customstringsdlg.cpp
  fred2/customstringsdlg.h
Labels: fix, general modding

#5932 Clarify which SEXPS work on ships not arrived
  code/parse/sexp.cpp
Labels: documentation

#5970 be mindful of death rolls when checking for ship stats
  code/parse/sexp.cpp
Labels: fix

#5973 ensure medal information is correctly assigned
  code/stats/medals.cpp
Labels: fix

#5972 update sexp help for send-message
  code/parse/sexp.cpp
Labels: documentation

#5962 fix warp time durations
  code/fireball/fireballs.cpp
  code/ship/shipfx.cpp
  code/ship/shipfx.h
Labels: fix, gameplay

#5977 Fix faulty / missing optimization for AMD shader compilation
  code/def_files/data/effects/main-f.sdr
Labels: fix, graphics

#5975 fix error handling in cfile_push_chdir()
  code/cfile/cfile.cpp
Labels: fix

#5976 refactor unix modlist handling to fix serveral issues
  code/cmdline/cmdline.cpp
Labels: fix

#5979 Unhardcode renderSelectModel zoom value
  code/scripting/api/objs/shipclass.cpp
  code/scripting/api/objs/weaponclass.cpp
Labels: ui, scripting, Requested by Active Mod

#5982 address issue 5980
  code/starfield/starfield.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: fix, qtfred, fred

#5983 fix FRED's "new object type" popup
  code/network/multiutil.cpp
  fred2/fredview.cpp
  fred2/fredview.h
  fred2/mainfrm.cpp
  fred2/management.cpp
  fred2/management.h
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/Editor.h
Labels: cleanup, fix, fred

#5984 Virtual POF fixes
  code/model/modelinterp.cpp
  code/model/modelreplace.cpp
Labels: fix, Requested by Active Mod

#5985 make model file checks consistent
  code/globalincs/pstypes.h
  code/missionui/missionweaponchoice.cpp
  code/model/modelread.cpp
  code/ship/ship.cpp
  code/weapon/shockwave.cpp
  code/weapon/weapons.cpp
Labels: fix, models

#5986 edit the release template
  ci/post/release.mako
Labels: build

#5988 Add some security to avoid invalid `Random::next()` calls.
  code/asteroid/asteroid.cpp
  code/debris/debris.cpp
  code/hud/hudartillery.cpp
Labels: cleanup, fix

#6003 bump version to 24.1
  cmake/version.cmake
Labels: build

#5884 str_wrap_to_width followup
  code/camera/camera.cpp
  code/gamehelp/contexthelp.cpp
  code/graphics/2d.h
  code/graphics/render.cpp
  code/graphics/render.h
  code/graphics/software/font.cpp
  code/hud/hudmessage.cpp
  code/menuui/credits.cpp
  code/missionui/missionweaponchoice.cpp
  code/osapi/DebugWindow.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/scripting/api/libs/graphics.cpp
Labels: cleanup, refactor, Waiting for Stable

#5996 fix "this ship name is already in use" bug
  fred2/shipeditordlg.cpp
  qtfred/src/mission/dialogs/ShipEditorDialogModel.cpp
Labels: fix, qtfred, fred, Waiting for Stable

#6007 Fix broken collision pair caching
  code/globalincs/globals.h
  code/object/objcollide.cpp
  code/object/objcollide.h
Labels: regression, fix, physics, Point Release Candidate

#5895 Retail ingame options
  code/camera/camera.cpp
  code/controlconfig/controlsconfigcommon.cpp
  code/fireball/fireballs.cpp
  code/fireball/warpineffect.cpp
  code/gamesequence/gamesequence.cpp
  code/gamesequence/gamesequence.h
  code/gamesnd/eventmusic.cpp
  code/globalincs/systemvars.cpp
  code/graphics/2d.cpp
  code/graphics/opengl/gropengltexture.cpp
  code/graphics/post_processing.cpp
  code/graphics/shadows.cpp
  code/io/joy-sdl.cpp
  code/io/joy_ff-sdl.cpp
  code/io/mouse.cpp
  code/lighting/lighting.cpp
  code/localization/localize.cpp
  code/menuui/optionsmenu.cpp
  code/mission/missionbriefcommon.cpp
  code/mod_table/mod_table.cpp
  code/nebula/neb.cpp
  code/network/multi_options.cpp
  code/options/Ingame_Options.cpp
  code/options/Ingame_Options.h
  code/options/Ingame_Options_internal.h
  code/options/Option.cpp
  code/options/Option.h
  code/options/OptionsManager.cpp
  code/options/dialogs/ingame_options_ui.cpp
  code/options/dialogs/ingame_options_ui.h
  code/options/manager/ingame_options_manager.cpp
  code/options/manager/ingame_options_manager.h
  code/osapi/osapi.cpp
  code/scripting/api/objs/option.cpp
  code/sound/sound.cpp
  code/source_groups.cmake
  code/starfield/starfield.cpp
  code/weapon/shockwave.cpp
  freespace2/freespace.cpp
Labels: ui, general modding, feature

#6001 add Team virtvar to parse objects
  code/scripting/api/objs/parse_object.cpp
Labels: enhancement, scripting, Requested by Active Mod

#5933 add for-subsystems
  code/mission/missionparse.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, sexps

#5886 make is-in-mission work for wings
  code/parse/sexp.cpp
Labels: enhancement, sexps

#5995 cover all stages of ship warping in the Lua API
  code/scripting/api/objs/ship.cpp
Labels: enhancement, scripting, Requested by Active Mod

#5993 Fix SSM strikes with a variable count.
  code/hud/hudartillery.cpp
Labels: regression, fix, Point Release Candidate

#6015 reconcile isValid between PRs
  code/scripting/api/objs/ship.cpp
Labels: fix, scripting

#5935 connect ship and parsed ship in Lua API
  code/scripting/api/objs/parse_object.cpp
  code/scripting/api/objs/ship.cpp
Labels: enhancement, scripting, Requested by Active Mod

#5998 allow a ship class's type to be set more than once
  code/ship/ship.cpp
Labels: fix

#6018 another isValid fix
  code/scripting/api/objs/ship.cpp
Labels: fix, scripting

#5950 add a has-time-elapsed-msecs SEXP
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, sexps

#5967 bitstring poofs
  code/lab/renderer/lab_renderer.cpp
  code/math/bitarray.h
  code/mission/missionparse.cpp
  code/nebula/neb.cpp
  code/nebula/neb.h
  code/parse/sexp.cpp
  fred2/bgbitmapdlg.cpp
  fred2/dumpstats.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: enhancement
