Repository scp-fs2open/fs2open.github.com, pull requests merged in 2024-09, with the labels that each got.

#6339 further refinement of sound fixes
  code/gamesnd/gamesnd.cpp
Labels: fix, sound

#6346 Fix deferred lighting Option
  code/lighting/lighting.cpp
  code/options/Option.cpp
  code/options/Option.h
  code/options/OptionsManager.cpp
  code/options/OptionsManager.h
Labels: fix

#6348 two HUD fixes
  code/hud/hud.cpp
  code/parse/sexp/LuaSEXP.cpp
  code/scripting/api/objs/hudgauge.cpp
Labels: fix, HUD

#6356 retail-style warning fix
  code/gamesnd/gamesnd.cpp
Labels: fix, sound

#6352 allow explicitly empty sounds
  code/gamesnd/gamesnd.cpp
  code/sound/sound.h
Labels: sound

#6355 Clarify options popup message text
  code/menuui/playermenu.cpp
Labels: cleanup

#6357 use functions for getting swarm info and corkscrew info
  code/scripting/api/objs/weaponclass.cpp
Labels: fix, scripting, Requested by Active Mod

#6361 derp
  code/scripting/api/objs/weaponclass.cpp
Labels: cleanup, scripting

#6367 remove bogus ship types from objecttypes.tbl
  code/def_files/data/tables/objecttypes.tbl
  code/ship/ship.cpp
Labels: fix, general modding

#6373 Fixes Lab Rendering when Zooming
  code/model/model.h
  code/ship/ship_flags.h
Labels: fix

#6370 Make Shockwaves in-game option force multi-value selection.
  code/weapon/shockwave.cpp
Labels: enhancement, fix

#6363 set the modified flag in the Voice Acting Manager
  fred2/voiceactingmanager.cpp
Labels: enhancement, fix, fred

#6368 Have TMAP chunks report >25 verts polygon error as well
  code/model/modelcollide.cpp
Labels: cleanup, Waiting for Stable
