Repository scp-fs2open/fs2open.github.com, pull requests merged in 2024-01, with the labels that each got.

#5908 Add some better error and validation checking to lua enums scripting API
  code/scripting/api/objs/LuaEnum.cpp
  code/scripting/api/objs/LuaEnum.h
Labels: cleanup, documentation

#5902 refine numeric error checking in FRED
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: fix, fred

#5913 5911 followup
  code/model/modelread.cpp
Labels: fix

#5909 remove mainhalltemp
  code/menuui/mainhalltemp.cpp
  code/menuui/mainhalltemp.h
  code/source_groups.cmake
Labels: cleanup, Waiting for Stable

#5915 restore number hack sign checking in all builds
  code/parse/sexp.cpp
Labels: fix

#5910 campaign error message improvement
  code/localization/localize.cpp
  code/menuui/barracks.cpp
  code/menuui/mainhallmenu.cpp
  code/menuui/readyroom.cpp
  code/mission/missioncampaign.cpp
  code/mission/missioncampaign.h
  code/parse/parselo.cpp
  code/parse/parselo.h
  fred2/campaigneditordlg.cpp
  freespace2/freespace.cpp
Labels: enhancement, fix

#5919 codesign Mac builds to prevent broken app message
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/build-test.yaml
Labels: build, mac

#5838 constify some turret code
  code/ai/ai.h
  code/ai/aibig.cpp
  code/ai/aibig.h
  code/ai/aicode.cpp
  code/ai/aiinternal.h
  code/ai/aiturret.cpp
  code/hud/hudbrackets.cpp
  code/hud/hudlock.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/model/model.h
  code/model/modelread.cpp
  code/scripting/api/objs/subsystem.cpp
  code/ship/awacs.cpp
  code/ship/awacs.h
  code/ship/ship.cpp
  code/ship/ship.h
  code/sound/ds.cpp
  code/sound/ds.h
  code/sound/ds3d.cpp
  code/sound/ds3d.h
  code/sound/sound.cpp
  code/sound/sound.h
  code/weapon/beam.cpp
  code/weapon/flak.cpp
  code/weapon/flak.h
  code/weapon/muzzleflash.cpp
  code/weapon/muzzleflash.h
  code/weapon/swarm.cpp
  code/weapon/swarm.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: refactor

#5916 upgrade the OPF_POSITIVE number hack
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, fix

#5938 Fix SCPUI overwriting campaign data
  code/scripting/api/libs/ui.cpp
Labels: scripting, Requested by Active Mod

#5948 Fix MSAA for some graphics drivers
  code/def_files/data/effects/msaa-f.sdr
Labels: fix

#5947 Fix: Keep Chase view from crashing in multi
  code/controlconfig/controlsconfig.h
  freespace2/freespace.cpp
Labels: fix, multi

#5914 Print option settings to the log
  code/io/mouse.cpp
  code/options/OptionsManager.cpp
  code/options/OptionsManager.h
  freespace2/freespace.cpp
Labels: cleanup, fix

#5953 fix crash in fire-beam-at-coordinates
  code/weapon/beam.cpp
Labels: fix

#5952 Fix custom string saving
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: fix, qtfred, fred

#5946 fix splash crash and add supplemental script hook
  code/scripting/global_hooks.cpp
  code/scripting/global_hooks.h
  code/scripting/hook_api.h
  code/scripting/scripting.cpp
  code/scripting/scripting.h
  fred2/management.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/management.cpp
Labels: fix, scripting

#5954 Fix discord option needing restart
  code/mod_table/mod_table.cpp
Labels: fix, general modding

#5929 Cleanup ui cutscene api
  code/cutscene/cutscenes.cpp
  code/cutscene/cutscenes.h
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/techroom.cpp
  code/scripting/api/objs/techroom.h
Labels: cleanup, fix, scripting

#5921 Save these to the ini file
  code/scripting/api/libs/options.cpp
Labels: fix, scripting

#5920 Properly check if we're running in a windowed mode
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/osapi/dialogs.cpp
Labels: fix, sound, general modding

#5955 Pause the UI properly based on user settings
  code/osapi/osapi.cpp
  freespace2/freespace.cpp
Labels: fix, gameplay, general modding

#5965 switch to new linux build image
  .github/workflows/build-nightly.yaml
  .github/workflows/build-release.yaml
  .github/workflows/build-test.yaml
  .github/workflows/cache-master.yaml
  .github/workflows/test-pull_request.yaml
  .github/workflows/weekly-coverity-scan.yaml
  ci/linux/configure_cmake.sh
Labels: fix, ci, linux

#5961 Third gravity fix
  code/ai/aibig.cpp
Labels: fix, gameplay

#5957 fix ship subsystem parse warning
  code/ship/ship.cpp
Labels: fix
