Repository scp-fs2open/fs2open.github.com, pull requests merged in 2025-02, with the labels that each got.

#6506 a few pstypes changes and refinements
  code/ai/ai.h
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/fireball/fireballs.cpp
  code/globalincs/pstypes.h
  code/graphics/2d.cpp
  code/graphics/opengl/gropenglbmpman.cpp
  code/graphics/render.cpp
  code/jumpnode/jumpnode.cpp
  code/menuui/techmenu.cpp
  code/missionui/missionweaponchoice.cpp
  code/model/animation/modelanimation.cpp
  code/model/model.h
  code/model/modelread.cpp
  code/model/modelrender.cpp
  code/model/modelreplace.cpp
  code/model/modelreplace.h
  code/nebula/volumetrics.cpp
  code/object/collideshipship.cpp
  code/playerman/playercontrol.cpp
  code/scripting/api/objs/weaponclass.cpp
  code/ship/ship.cpp
  code/ship/shiphit.cpp
  code/starfield/starfield.cpp
  code/starfield/supernova.cpp
  code/tracing/FrameProfiler.cpp
  qtfred/src/mission/dialogs/MissionSpecDialogModel.cpp
Labels: cleanup, refactor

#6561 add subsystemname scripted sexp type
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/parse/sexp/LuaSEXP.cpp
Labels: enhancement, scripting, Requested by Active Mod

#6562 Allow scripted gauges to be off by default
  code/hud/hudparse.cpp
Labels: Requested by Active Mod

#6548 Allow preloading briefing icons
  code/mission/missionparse.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: enhancement, ui

#6557 update .gitmodules references
  .gitmodules
Labels: build

#6567 reduce magic numbers in missionweaponchoice
  code/missionui/fictionviewer.cpp
  code/missionui/missioncmdbrief.cpp
  code/missionui/missionweaponchoice.cpp
  code/missionui/missionweaponchoice.h
Labels: cleanup

#6571 Unify Particle Attachment
  code/debris/debris.cpp
  code/model/modelread.cpp
  code/model/modelrender.cpp
  code/object/collideshipweapon.cpp
  code/particle/EffectHost.h
  code/particle/ParticleEffect.h
  code/particle/ParticleSource.cpp
  code/particle/ParticleSource.h
  code/particle/hosts/EffectHostObject.cpp
  code/particle/hosts/EffectHostObject.h
  code/particle/hosts/EffectHostSubmodel.cpp
  code/particle/hosts/EffectHostSubmodel.h
  code/particle/hosts/EffectHostVector.cpp
  code/particle/hosts/EffectHostVector.h
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/utils/modular_curves.h
  code/weapon/beam.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, fix

#6469 some upgrades to vmallocator.h
  code/ai/ai.h
  code/ai/aicode.cpp
  code/globalincs/systemvars.cpp
  code/globalincs/vmallocator.cpp
  code/globalincs/vmallocator.h
  code/hud/hudsquadmsg.cpp
  code/model/animation/modelanimation.h
  code/model/animation/modelanimation_moveables.cpp
  code/model/animation/modelanimation_moveables.h
  code/model/modelinterp.cpp
  code/parse/sexp.cpp
  code/scripting/api/libs/mission.cpp
  code/scripting/lua.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/source_groups.cmake
  fred2/eventeditor.cpp
  fred2/ignoreordersdlg.cpp
  fred2/missiongoalsdlg.cpp
  fred2/sexp_tree.cpp
  qtfred/src/mission/dialogs/MissionGoalsDialogModel.cpp
  qtfred/src/mission/dialogs/ShipEditor/PlayerOrdersDialogModel.cpp
  qtfred/src/ui/dialogs/EventEditorDialog.cpp
  qtfred/src/ui/widgets/sexp_tree.cpp
Labels: refactor

#6565 add some utility functions
  code/globalincs/utility.h
  code/graphics/2d.cpp
  code/math/curve.cpp
  code/parse/sexp.cpp
  code/scripting/api/objs/ship.cpp
  code/utils/string_utils.cpp
  code/utils/string_utils.h
Labels: enhancement, refactor

#6580 fix wing creation dialog
  fred2/createwingdlg.cpp
  fred2/management.cpp
  fred2/management.h
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/Editor.h
  qtfred/src/mission/dialogs/FormWingDialogModel.cpp
Labels: fix, qtfred, fred

#6583 allow stringcost to be case-insensitive
  code/globalincs/utility.h
  code/parse/sexp.cpp
  fred2/OperatorComboBox.cpp
Labels: sexps, fred

#6584 Allow mods to Always Show Directive Value Count
  code/mission/missiongoals.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: enhancement, cleanup

#6586 addendum to fixed missile detonation
  code/object/collideshipweapon.cpp
Labels: fix, gameplay

#6585 Allow modders to always show first game tip at start
  code/menuui/playermenu.cpp
  code/menuui/playermenu.h
Labels: enhancement, documentation

#6569 misceallaneous small fixes and tweaks
  code/hud/hudsquadmsg.cpp
  code/missionui/missionshipchoice.cpp
  code/parse/sexp/LuaSEXP.cpp
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/waypoint.cpp
  code/ship/ship.cpp
  code/ship/ship.h
Labels: cleanup, fix, scripting, Requested by Active Mod

#6570 update script API for AI orders
  code/ai/ai.h
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aigoals.h
  code/scripting/api/objs/order.cpp
  code/scripting/api/objs/ship.cpp
  code/scripting/api/objs/waypoint.cpp
Labels: enhancement, fix, scripting, Requested by Active Mod

#6590 fix two uses of optional_string_either
  code/weapon/weapons.cpp
Labels: fix

#6589 Unify AI Usage of Shield Manage Delay
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aicode.cpp
Labels: enhancement, cleanup, ai

#6591 Create scripting hook: 'On Options Menu Tab Changed'
  code/menuui/optionsmenu.cpp
  code/scripting/global_hooks.cpp
  code/scripting/global_hooks.h
Labels: enhancement, scripting

#6517 Add many options to default settings table
  code/camera/camera.cpp
  code/gamesnd/eventmusic.cpp
  code/globalincs/systemvars.cpp
  code/graphics/opengl/gropengltexture.cpp
  code/graphics/post_processing.cpp
  code/graphics/shadows.cpp
  code/lighting/lighting.cpp
  code/nebula/neb.cpp
  code/playerman/playercontrol.cpp
  code/sound/sound.cpp
  code/starfield/starfield.cpp
  code/weapon/shockwave.cpp
  freespace2/freespace.cpp
Labels: enhancement, ui

#6592 Update in-game joystick settings to work without restarting FSO
  code/io/joy-sdl.cpp
Labels: enhancement, controls, ui

#6594 Make Cockpit Deferred an In-game Option
  code/lighting/lighting.cpp
  code/lighting/lighting.h
  code/localization/localize.cpp
  code/ship/ship.cpp
Labels: enhancement, graphics, ui

#6593 add linked loop firing sounds
  code/ship/ship.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, sound

#6600 Fix particle name assignment when using legacy-type composite effects that address child effects by name
  code/particle/ParticleParse.cpp
Labels: fix

#6601 change the selection style on the nebula poof list box
  fred2/fred.rc
Labels: fred, Requested by Active Mod

#6597 Fix changes to Options not properly discarding when escape key pressed
  code/menuui/optionsmenu.cpp
  code/menuui/optionsmenumulti.cpp
  code/menuui/optionsmenumulti.h
  code/network/multi_options.cpp
  code/network/multi_pxo.cpp
  code/pilotfile/plr.cpp
Labels: fix, ui

#6602 several fixes to ship sparks
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipfx.cpp
  code/ship/shiphit.cpp
Labels: cleanup, fix

#6598 refactor ship_get_eye
  code/camera/camera.cpp
  code/hud/hudtargetbox.cpp
  code/observer/observer.cpp
  code/observer/observer.h
  code/physics/physics.cpp
  code/playerman/playercontrol.cpp
  code/radar/radarsetup.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shipfx.cpp
  freespace2/freespace.cpp
Labels: refactor

#6604 Create scripting hook: 'On Options Menu Closed'
  code/menuui/optionsmenu.cpp
  code/scripting/global_hooks.cpp
  code/scripting/global_hooks.h
Labels: enhancement, scripting

#6605 Localize a missing Controls Popup text string
  code/controlconfig/controlsconfig.cpp
  code/localization/localize.cpp
Labels: cleanup, ui, localization / translation

#6608 Create scripting hooks HUD and Control Config Close
  code/controlconfig/controlsconfig.cpp
  code/hud/hudconfig.cpp
  code/scripting/global_hooks.cpp
  code/scripting/global_hooks.h
Labels: enhancement, scripting

#6603 audio QoL update
  code/gamesnd/eventmusic.cpp
  code/gamesnd/gamesnd.cpp
Labels: cleanup

#6573 HUD Config Rendering Methods PR 1/7
  code/hud/hud.cpp
  code/hud/hud.h
Labels: enhancement, HUD, ui
