Repository scp-fs2open/fs2open.github.com, pull requests merged in 2025-10, with the labels that each got.

#7069 color/colour updates
  code/globalincs/alphacolors.cpp
  code/hud/hudparse.cpp
  code/mod_table/mod_table.cpp
  code/ship/ship.cpp
Labels: cleanup

#7067 Updates to fireball parsing
  code/asteroid/asteroid.cpp
  code/fireball/fireballs.cpp
  code/globalincs/alphacolors.cpp
  code/globalincs/systemvars.cpp
  code/graphics/2d.cpp
  code/hud/hudparse.cpp
  code/iff_defs/iff_defs.cpp
  code/lab/renderer/lab_renderer.cpp
  code/math/floating.h
  code/mission/missioncampaign.cpp
  code/mission/missionparse.cpp
  code/mod_table/mod_table.cpp
  code/nebula/neb.cpp
  code/parse/parsehi.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/ship/ship.cpp
  code/species_defs/species_defs.cpp
  code/weapon/weapons.cpp
Labels: enhancement, cleanup, general modding, Requested by Active Mod

#7076 Fix anim executables when animations wrap around
  code/model/animation/modelanimation.cpp
Labels: fix
