Repository scp-fs2open/fs2open.github.com, pull requests merged in 2025-09, with the labels that each got.

#6998 QtFRED Background Editor Dialog
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/BackgroundEditorDialogModel.cpp
  qtfred/src/mission/dialogs/BackgroundEditorDialogModel.h
  qtfred/src/ui/dialogs/BackgroundEditorDialog.cpp
  qtfred/src/ui/dialogs/BackgroundEditorDialog.h
  qtfred/ui/BackgroundEditor.ui
Labels: qtfred

#7012 Fix crashing if mod uses custom hud gauge and no -mod cmdline is passed
  code/hud/hudconfig.cpp
Labels: fix, general modding

#7011 Expose value of idle circling with 'attack-any'
  code/ai/ai_profiles.cpp
  code/ai/ai_profiles.h
  code/ai/aicode.cpp
Labels: enhancement, ai, Requested by Active Mod

#7013 Fix build issues with Vulkan SDK 1.3.301+
  code/graphics/vulkan/VulkanRenderer.cpp
Labels: fix, build, graphics, vulkan

#7010 Add 'direct fire lead target' beam flag
  code/weapon/beam.cpp
  code/weapon/weapon_flags.h
  code/weapon/weapons.cpp
Labels: enhancement, gameplay

#7021 Fix for modern Thruster Particles
  code/ship/ship.cpp
Labels: fix, particles

#7023 make legacy particle spews more robust
  code/weapon/weapons.cpp
Labels: fix, particles

#7024 restore double quote conversion in event editor
  qtfred/src/mission/dialogs/MissionEventsDialogModel.cpp
Labels: fix, qtfred

#7014 modular table fix for cinematic warp
  code/fireball/fireballs.cpp
Labels: fix, graphics

#7038 fix null vector assertion in slash beam collisions
  code/weapon/beam.cpp
Labels: fix, particles

#7034 Give Particles Access to Their Spawner Effect
  .clang-tidy
  code/particle/ParticleEffect.cpp
  code/particle/ParticleEffect.h
  code/particle/ParticleManager.cpp
  code/particle/ParticleParse.cpp
  code/particle/ParticleSource.h
  code/particle/hosts/EffectHostParticle.cpp
  code/particle/particle.cpp
  code/particle/particle.h
  code/utils/modular_curves.h
Labels: enhancement, particles

#7033 Do not set IS_X86 when target cpu is armv7
  cmake/globals.cmake
Labels: build

#7039 Supply normals for edge hits
  code/model/modelcollide.cpp
  code/weapon/beam.cpp
Labels: fix

#7042 Update to #7023
  code/particle/particle.cpp
Labels: fix, particles

#7040 Particles can now emit light
  code/particle/ParticleEffect.cpp
  code/particle/ParticleEffect.h
  code/particle/ParticleParse.cpp
  code/particle/particle.cpp
Labels: enhancement, particles

#7044 Small particle copy-paste fixes
  code/particle/ParticleEffect.cpp
  code/particle/particle.cpp
Labels: fix, particles

#7043 add ai_profiles flag to disable form-on-wing at mission start
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aigoals.cpp
Labels: enhancement, gameplay, Requested by Active Mod

#7047 Particle Curves with access to host object & ship properties
  code/asteroid/asteroid.cpp
  code/hud/hudets.h
  code/model/model.h
  code/object/object_instance.h
  code/particle/ParticleEffect.h
  code/particle/ParticleManager.h
  code/particle/ParticleSource.cpp
  code/particle/particle.cpp
  code/source_groups.cmake
  code/utils/modular_curves.h
  code/weapon/muzzleflash.cpp
Labels: enhancement, particles

#7030 QtFRED Campaign Editor
  qtfred/source_groups.cmake
  qtfred/src/mission/dialogs/CampaignEditorDialogModel.cpp
  qtfred/src/mission/dialogs/CampaignEditorDialogModel.h
  qtfred/src/ui/dialogs/CampaignEditorDialog.cpp
  qtfred/src/ui/dialogs/CampaignEditorDialog.h
  qtfred/src/ui/widgets/CampaignMissionGraph.cpp
  qtfred/src/ui/widgets/CampaignMissionGraph.h
  qtfred/src/ui/widgets/SimpleListSelectDialog.cpp
  qtfred/src/ui/widgets/SimpleListSelectDialog.h
  qtfred/ui/CampaignEditorDialog.ui
Labels: qtfred

#7064 QtFRED Modernize Menus
  qtfred/ui/FredView.ui
Labels: qtfred

#7061 Particle Scripting API
  code/particle/ParticleManager.cpp
  code/particle/ParticleManager.h
  code/scripting/api/libs/tables.cpp
  code/scripting/api/objs/particle.cpp
  code/scripting/api/objs/particle.h
Labels: scripting, particles

#7068 Fix Asteroid Table Parsing
  code/asteroid/asteroid.cpp
Labels: fix
