Repository scp-fs2open/fs2open.github.com, pull requests merged in 2025-05, with the labels that each got.

#6703 Lab firing upgrades
  code/ai/ai.h
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/lab/dialogs/lab_ui.cpp
  code/lab/dialogs/lab_ui.h
  code/lab/manager/lab_manager.cpp
  code/lab/manager/lab_manager.h
  code/ship/ship.cpp
  code/weapon/swarm.cpp
  code/weapon/swarm.h
  code/weapon/weapons.cpp
Labels: enhancement, Lab

#6691 Allow defining separate player and target shield icons for config
  code/hud/hudconfig.cpp
  code/hud/hudconfig.h
  code/hud/hudescort.cpp
  code/hud/hudparse.cpp
  code/hud/hudshield.cpp
  code/hud/hudshield.h
Labels: enhancement, HUD, Requested by Active Mod

#6705 Update Changelog script to sort by labels
  ci/post/changelog.py
Labels: build

#6698 fix hull/shield checks in missionsave
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: fix, qtfred, fred

#6708 check dockpoints when changing ship class
  code/globalincs/utility.h
  code/ship/ship.cpp
Labels: fix, models

#6706 Allow Trigger Radius curve input to work with muzzle effects
  code/ai/aiturret.cpp
  code/ship/shipfx.cpp
Labels: enhancement, particles

#6692 Add a few hud lua methods
  code/hud/hud.cpp
  code/hud/hud.h
  code/hud/hudsquadmsg.cpp
  code/scripting/api/objs/hudconfig.cpp
  code/scripting/api/objs/hudgauge.cpp
Labels: Requested by Active Mod

#6712 A few fixes
  code/parse/parselo.cpp
  code/scripting/api/objs/comm_order.cpp
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
Labels: fix

#6686 enhance look_at
  code/model/modelread.cpp
Labels: cleanup, fix, models

#6714 goto considered useful
  code/sound/ds.cpp
Labels: coverity, fix, sound

#6717 improve scripting support for waypoint lists
  code/ai/aicode.cpp
  code/object/waypoint.cpp
  code/object/waypoint.h
  code/parse/sexp.cpp
  code/scripting/api/libs/mission.cpp
Labels: enhancement, scripting

#6711 Small fix for turret swarm stuff
  code/weapon/swarm.cpp
Labels: cleanup

#6713 Various Coverity issues
  code/actions/expression/ExpressionParser.cpp
  code/actions/types/MoveToSubmodel.cpp
  code/controlconfig/controlsconfig.cpp
  code/hud/hudbrackets.cpp
  code/hud/hudsquadmsg.cpp
  code/hud/hudtarget.cpp
  code/jumpnode/jumpnode.cpp
  code/jumpnode/jumpnode.h
  code/menuui/credits.cpp
  code/mission/missionparse.cpp
  code/model/animation/modelanimation.cpp
  code/model/animation/modelanimation_moveables.cpp
  code/network/psnet2.cpp
  code/options/dialogs/ingame_options_ui.cpp
  code/parse/parselo.cpp
  code/parse/sexp/LuaSEXP.cpp
  code/parse/sexp/sexp_lookup.cpp
  code/pilotfile/csg.cpp
  code/pilotfile/plr.cpp
  code/popup/popup.cpp
  code/popup/popupdead.cpp
  code/radar/radarsetup.cpp
  code/scpui/elements/AnimationElement.cpp
  code/scripting/api/libs/async.cpp
  code/scripting/api/libs/engine.cpp
  code/scripting/api/libs/graphics.cpp
  code/scripting/api/libs/multi.cpp
  code/scripting/api/objs/hudconfig.cpp
  code/scripting/api/objs/rpc.cpp
  code/scripting/doc_parser.cpp
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/weapon/weapons.cpp
  fred2/fredview.cpp
  fred2/jumpnodedlg.cpp
  fred2/management.cpp
  freespace2/freespace.cpp
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/dialogs/WaypointEditorDialogModel.cpp
  test/src/actions/expression/test_ExpressionParser.cpp
  test/src/scripting/doc_parser.cpp
Labels: coverity

#6670 Support Custom Gauges in HUD Config UI
  code/hud/hud.cpp
  code/hud/hudconfig.cpp
  code/hud/hudconfig.h
  code/hud/hudobserver.cpp
  code/pilotfile/csg.cpp
  code/pilotfile/plr.cpp
  code/pilotfile/plr_hudprefs.cpp
  code/pilotfile/plr_hudprefs.h
  code/scripting/api/objs/hudconfig.cpp
  code/source_groups.cmake
Labels: enhancement, HUD, ui, Requested by Active Mod

#6716 Fix highlighting color discrepancy for player ship in loadout screen
  code/missionui/missionshipchoice.cpp
  code/missionui/missionshipchoice.h
  code/missionui/missionweaponchoice.cpp
Labels: enhancement, fix

#6720 Extra Visual Indication for `Scramble` Missions
  code/localization/localize.cpp
  code/missionui/missionscreencommon.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: enhancement

#6723 Various more Coverity issues
  code/controlconfig/controlsconfig.cpp
  code/controlconfig/controlsconfig.h
  code/fireball/fireballs.cpp
  code/globalincs/utility.h
  code/hud/hudconfig.h
  code/hud/hudtargetbox.cpp
  code/lab/renderer/lab_renderer.h
  code/missionui/missiondebrief.cpp
  code/model/modelread.cpp
  code/parse/parselo.cpp
  code/parse/sexp/sexp_lookup.cpp
  code/pilotfile/csg_convert.cpp
  code/scripting/scripting.cpp
  code/tracing/FrameProfiler.cpp
  code/tracing/FrameProfiler.h
Labels: coverity

#6671 ETS updates
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aicode.cpp
  code/hud/hudets.cpp
  code/hud/hudets.h
  code/model/animation/modelanimation_driver.cpp
  code/parse/sexp.cpp
  code/ship/afterburner.cpp
Labels: enhancement, gameplay, Requested by Active Mod

#6726 add an ETS comment
  code/hud/hudets.cpp
Labels: cleanup

#6722 Weapon curves followup
  code/model/modelrender.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, fix, graphics, Requested by Active Mod

#6733 Tiny optimization to laser culling.
  code/weapon/weapons.cpp
Labels: cleanup

#6675 Allow using seeded noise for particle velocity and spawn position offset
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/particle/ParticleEffect.cpp
  code/particle/ParticleEffect.h
  code/particle/ParticleParse.cpp
  code/particle/ParticleSource.cpp
  code/particle/ParticleSource.h
Labels: enhancement, particles

#6737 One fix and one enhancement to AI shield behavior
  code/ai/ai.h
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/aicode.cpp
  code/object/collideshipweapon.cpp
  code/object/objectshield.cpp
Labels: enhancement, fix, ai
