Repository scp-fs2open/fs2open.github.com, pull requests merged in 2025-07, with the labels that each got.

#6805 change this WarningEx to a Warning
  code/graphics/software/font.cpp
Labels: cleanup, documentation

#6813 Instanced Decals
  code/decals/decals.cpp
  code/def_files/data/effects/decal-f.sdr
  code/def_files/data/effects/decal-v.sdr
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/graphics/decal_draw_list.cpp
  code/graphics/decal_draw_list.h
  code/graphics/grstub.cpp
  code/graphics/opengl/gropengl.cpp
  code/graphics/opengl/gropengldraw.cpp
  code/graphics/opengl/gropengldraw.h
  code/graphics/opengl/gropenglshader.cpp
  code/graphics/opengl/gropenglshader.h
  code/graphics/opengl/gropengltnl.cpp
  code/graphics/opengl/gropengltnl.h
  code/graphics/util/uniform_structs.h
  code/graphics/vulkan/vulkan_stubs.cpp
Labels: optimization

#6818 qtfred cleanup
  qtfred/src/mission/dialogs/CustomWingNamesDialogModel.cpp
  qtfred/src/mission/dialogs/ShipEditor/ShipTextureReplacementDialogModel.cpp
  qtfred/src/ui/dialogs/LoadoutDialog.cpp
  qtfred/src/ui/dialogs/ReinforcementsEditorDialog.cpp
Labels: cleanup, qtfred

#6817 fix qtfred memory corruption
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/Editor.h
  qtfred/src/ui/FredView.cpp
Labels: fix, qtfred

#6806 make script-eval-num and script-eval-bool multiline
  code/parse/sexp.cpp
Labels: enhancement, sexps, scripting

#6816 memory safety for model parsing
  code/globalincs/pstypes.h
  code/model/model.h
  code/model/modelcollide.cpp
  code/model/modelinterp.cpp
  code/model/modelread.cpp
  code/model/modelsinc.h
  code/render/3d.h
  code/render/3ddraw.cpp
Labels: cleanup, models

#6821 Fix some things in the particle code coverity flagged
  code/particle/volumes/SpheroidVolume.cpp
  code/weapon/muzzleflash.cpp
  code/weapon/weapons.cpp
Labels: fix

#6820 fix broken newline behavior when FRED saves missions
  fred2/missionsave.cpp
  fred2/missionsave.h
  qtfred/src/mission/missionsave.cpp
  qtfred/src/mission/missionsave.h
Labels: fix, qtfred, fred

#6804 sort map keys before saving a container
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: qtfred, fred

#6785 Enhanced functionality for conditional impacts
  code/debris/debris.cpp
  code/debris/debris.h
  code/network/multimsgs.cpp
  code/object/collidedebrisweapon.cpp
  code/object/collideshipweapon.cpp
  code/object/collideweaponweapon.cpp
  code/ship/shiphit.cpp
  code/ship/shiphit.h
  code/weapon/beam.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement

#6825 Fix orb radar in config mode
  code/radar/radarorb.cpp
Labels: fix, HUD

#6826 ensure SEXP help has appropriate newlines or spaces
  code/parse/sexp.cpp
Labels: sexps, documentation

#6829 fix decal shader compile error
  code/def_files/data/effects/decal-f.sdr
  code/def_files/data/effects/decal-v.sdr
Labels: fix, opengl

#6834 Fix Thread Count Detection on Windows
  code/utils/threading.cpp
Labels: fix

#6835 get proper number of physical cpu cores on macOS
  code/utils/threading.cpp
Labels: cleanup

#6827 Slots for custom post processing effects
  code/def_files/data/effects/post-f.sdr
  code/def_files/data/tables/post_processing.tbl
  code/graphics/opengl/gropenglpostprocessing.cpp
  code/graphics/post_processing.cpp
  code/graphics/post_processing.h
  code/graphics/util/uniform_structs.h
Labels: enhancement, graphics, Requested by Active Mod

#6831 fix play-sound-from-file with multiple variable-controlled streams
  code/parse/sexp.cpp
Labels: fix, Requested by Active Mod

#6837 Fix default PSPEW scale
  code/weapon/weapons.cpp
Labels: fix

#6844 allow modular nebula tables to not define bitmaps
  code/nebula/neb.cpp
Labels: enhancement

#6847 Allow mods to set threshold at which shield stops taking damage
  code/hud/hudshield.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/object/objectshield.cpp
  code/object/objectshield.h
  code/ship/shield.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/ship/shiphit.cpp
  code/weapon/weapons.cpp
Labels: enhancement, general modding

#6850 Fix Edge-case with `$Preload briefing icon models:`
  code/mission/missionparse.cpp
Labels: fix

#6855 Fix odd-looking hull impacts spawning when the shield is hit
  code/ship/shiphit.cpp
  code/ship/shiphit.h
Labels: fix

#6860 Fix 'show-ship` not working
  code/ship/ship.cpp
Labels: fix

#6862 Lua func to check if in game options are enabled
  code/scripting/api/libs/options.cpp
Labels: enhancement, scripting

#6866 Prevent lua from Garbage Collecting possibly-stale Subframes
  code/scripting/api/objs/texture.cpp
  code/scripting/api/objs/texture.h
Labels: bug, graphics, scripting

#6872 Fix calculation of apparent size
  code/model/modelrender.cpp
  code/model/modelrender.h
  code/particle/ParticleEffect.cpp
  code/utils/RandomRange.h
  code/weapon/weapons.cpp
Labels: fix

#6869 fix particle related standalone error
  code/asteroid/asteroid.cpp
Labels: fix, multi

#6871 fix multi crash loading campaigns
  code/mission/missioncampaign.cpp
  code/mission/missioncampaign.h
  code/mission/missionparse.cpp
  code/network/multi_options.cpp
  code/network/multiui.cpp
  code/playerman/managepilot.cpp
  code/scripting/api/libs/mission.cpp
Labels: fix, multi

#6865 add smoothing field to volumetrics dialog
  fred2/fred.rc
  fred2/resource.h
  fred2/volumetricsdlg.cpp
  fred2/volumetricsdlg.h
Labels: fred

#6875 Fix p-spew with homing weapons
  code/weapon/weapons.cpp
Labels: fix, particles

#6861 Custom data for personas
  code/mission/missionmessage.cpp
  code/mission/missionmessage.h
  code/scripting/api/objs/message.cpp
Labels: enhancement, cleanup, Requested by Active Mod

#6883 Fix rare collisions being dropped in threaded FSO
  code/object/objcollide.cpp
Labels: fix

#6884 Minor Particle Fixes
  code/particle/ParticleParse.cpp
  code/scripting/api/libs/graphics.cpp
Labels: fix, particles

#6874 Preload asteroids and debris when config-field SEXPs are used
  code/asteroid/asteroid.cpp
  code/asteroid/asteroid.h
  code/parse/sexp.cpp
Labels: cleanup, optimization

#6886 fix more particle issues with standalone
  code/asteroid/asteroid.cpp
  code/scripting/api/libs/graphics.cpp
  code/ship/ship.cpp
  code/ship/shipfx.cpp
Labels: fix, multi

#6888 fix double dumbfire missiles for multi clients
  code/network/multimsgs.cpp
Labels: fix, multi
