Repository scp-fs2open/fs2open.github.com, pull requests merged in 2025-01, with the labels that each got.

#6499 Prefer ship tech model if it exists in renderTechModel
  code/model/modelrender.cpp
Labels: enhancement, ui

#6501 Fix `Mouse` XSTR Index in In-game options
  code/io/mouse.cpp
Labels: cleanup, fix, ui, localization / translation

#6478 Make explicit shield hit radius for ships and weapons
  code/object/collideshipweapon.cpp
  code/ship/shield.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/beam.cpp
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: enhancement, graphics

#6497 Func to get a ship's persona directly
  code/scripting/api/objs/message.cpp
  code/scripting/api/objs/ship.cpp
Labels: enhancement

#6448 Allow per-stage briefing grid colors
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/mission/missionbriefcommon.cpp
  code/mission/missionbriefcommon.h
  code/mission/missionparse.cpp
  code/mission/missionparse.h
  fred2/briefingeditordlg.cpp
  fred2/missionsave.cpp
  qtfred/src/mission/missionsave.cpp
Labels: enhancement, ui

#6502 Fix offset dialog option image with controls preset confirmation
  code/controlconfig/controlsconfig.cpp
Labels: cleanup, controls, ui

#6472 Add Lua global variables library
  code/scripting/api/libs/globals.cpp
  code/scripting/api/libs/globals.h
  code/scripting/api/libs/ui.cpp
  code/scripting/lua.cpp
  code/source_groups.cmake
Labels: enhancement, scripting

#6505 gracefully fail if volumetrics model is not found
  code/nebula/volumetrics.cpp
Labels: cleanup, models

#6467 Ai-goal refactor
  code/ai/ai.h
  code/ai/ai_flags.h
  code/ai/aibig.cpp
  code/ai/aicode.cpp
  code/ai/aigoals.cpp
  code/ai/aigoals.h
  code/autopilot/autopilot.cpp
  code/hud/hudsquadmsg.cpp
  code/mission/missionparse.cpp
  code/network/multimsgs.cpp
  code/parse/sexp.cpp
  code/parse/sexp.h
  code/scripting/api/objs/enums.cpp
  code/scripting/api/objs/enums.h
  code/scripting/api/objs/order.cpp
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/weapons.cpp
  fred2/management.cpp
  fred2/management.h
  fred2/shipgoalsdlg.cpp
  fred2/shipgoalsdlg.h
  qtfred/src/mission/Editor.cpp
  qtfred/src/mission/Editor.h
  qtfred/src/mission/dialogs/ShipEditor/ShipGoalsDialogModel.cpp
  qtfred/src/mission/dialogs/ShipEditor/ShipGoalsDialogModel.h
  qtfred/src/ui/dialogs/ShipEditor/ShipGoalsDialog.cpp
Labels: qtfred, ai, fred, refactor

#6511 Allow Modders to Tune Strafing
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/ai_profiles.h
  code/ai/aibig.cpp
Labels: enhancement, ai, Requested by Active Mod

#6491 Default settings tbl
  code/ai/ai_profiles.cpp
  code/ai/ai_profiles.h
  code/asteroid/asteroid.cpp
  code/globalincs/systemvars.cpp
  code/globalincs/systemvars.h
  code/graphics/2d.cpp
  code/menuui/optionsmenu.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/model/modelinterp.cpp
  code/model/modelrender.cpp
  code/nebula/neb.cpp
  code/nebula/volumetrics.cpp
  code/network/multi_pinfo.cpp
  code/options/Option.h
  code/options/OptionsManager.cpp
  code/options/OptionsManager.h
  code/options/default_settings_table.cpp
  code/options/default_settings_table.h
  code/particle/particle.cpp
  code/pilotfile/plr.cpp
  code/playerman/managepilot.cpp
  code/source_groups.cmake
  code/starfield/starfield.cpp
  code/utils/string_utils.cpp
  code/utils/string_utils.h
  freespace2/freespace.cpp
Labels: feature, Requested by Active Mod

#6512 fix volume updates for looping sounds
  code/sound/sound.cpp
  code/utils/id.h
Labels: fix, sound

#6510 Lua access to MAX_SHIPS_PER_WING
  code/scripting/api/libs/globals.cpp
Labels: enhancement, scripting

#6513 Add Mod Option to Limit 'Show Ship' when Toggling Cockpits
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
  code/object/objectsort.cpp
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/weapon/beam.cpp
Labels: enhancement, graphics, Requested by Active Mod

#6519 Fixes Debris not inheriting parent ship texture replacements
  code/debris/debris.cpp
  code/scripting/api/objs/modelinstance.cpp
  code/scripting/api/objs/ship.cpp
Labels: fix, graphics

#6481 Add scaling for vfnts and scale multipler to gr_string()
  code/camera/camera.cpp
  code/gamehelp/contexthelp.cpp
  code/graphics/2d.h
  code/graphics/render.cpp
  code/graphics/render.h
  code/graphics/software/FSFont.cpp
  code/graphics/software/FSFont.h
  code/graphics/software/FontManager.cpp
  code/graphics/software/NVGFont.cpp
  code/graphics/software/NVGFont.h
  code/graphics/software/VFNTFont.cpp
  code/graphics/software/VFNTFont.h
  code/graphics/software/font.cpp
  code/graphics/software/font.h
  code/hud/hudmessage.cpp
  code/menuui/credits.cpp
  code/menuui/techmenu.cpp
  code/missionui/fictionviewer.cpp
  code/missionui/missionbrief.cpp
  code/missionui/missioncmdbrief.cpp
  code/missionui/missionweaponchoice.cpp
  code/osapi/DebugWindow.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/scripting/api/libs/graphics.cpp
Labels: enhancement, graphics, refactor

#6525 Fix font multiplier in release builds
  code/graphics/render.cpp
  code/graphics/software/FSFont.cpp
  code/graphics/software/FSFont.h
  code/graphics/software/NVGFont.cpp
  code/graphics/software/VFNTFont.cpp
  code/graphics/software/VFNTFont.h
Labels: fix, ui

#6487 Add scaling features to additional bitmap drawing methods
  code/graphics/2d.cpp
  code/graphics/2d.h
  code/graphics/render.cpp
  code/graphics/render.h
Labels: enhancement, cleanup, graphics

#6522 Add missed popup for on dialog frame and add text hook var
  code/popup/popup.cpp
  code/popup/popupdead.cpp
  code/scripting/global_hooks.cpp
Labels: enhancement, multi, ui, scripting

#6523 fix player weapon precedence to include per-bank restriction
  code/missionui/missionweaponchoice.cpp
Labels: fix, gameplay

#6526 Add failsafe check for new texture replace fix
  code/debris/debris.cpp
Labels: fix

#6508 Some minor Control Config UI changes for SCPUI
  code/controlconfig/controlsconfig.cpp
  code/controlconfig/controlsconfig.h
  code/controlconfig/presets.cpp
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/control_config.cpp
Labels: enhancement, ui, scripting

#6498 Lua set mainhall
  code/menuui/mainhallmenu.cpp
  code/menuui/mainhallmenu.h
  code/scripting/api/libs/ui.cpp
Labels: enhancement, ui, scripting, Requested by Active Mod

#6524 tweak object model/instance convenience functions
  code/actions/types/MoveToSubmodel.cpp
  code/actions/types/ParticleEffectAction.cpp
  code/actions/types/PlaySoundAction.cpp
  code/camera/camera.cpp
  code/debris/debris.cpp
  code/decals/decals.cpp
  code/hud/hudtargetbox.cpp
  code/model/modelread.cpp
  code/model/modelrender.cpp
  code/network/multimsgs.cpp
  code/object/object.cpp
  code/object/object.h
  code/object/objectdock.cpp
  code/scripting/api/objs/object.cpp
  code/ship/ship.cpp
  code/weapon/weapons.cpp
Labels: refactor, models

#6530 re-remove Update_window check
  fred2/fred.cpp
Labels: fix, fred

#6527 fix kamikaze attack of subsystems
  code/ai/aicode.cpp
Labels: fix, ai, Requested by Active Mod

#6534 Mission goals hook
  code/mission/missiongoals.cpp
  code/scripting/global_hooks.cpp
  code/scripting/global_hooks.h
Labels: enhancement, scripting

#6533 Fix input text string rendering
  code/graphics/render.cpp
Labels: fix, ui

#6535 make line-of-sight objects aware of its subclasses
  code/scripting/api/libs/mission.cpp
Labels: fix, scripting

#6529 fix event editor modification check
  fred2/eventeditor.cpp
  qtfred/src/ui/dialogs/EventEditorDialog.cpp
Labels: fix, qtfred, fred

#6538 Ensure that Ext Game Popup sends Affirmative and Negative Flags
  code/menuui/mainhallmenu.cpp
Labels: fix, ui, scripting

#6539 Fix more Popup Button Alignments
  code/controlconfig/controlsconfig.cpp
  code/controlconfig/presets.cpp
Labels: fix, ui

#6541 update sexp documentation
  code/parse/sexp.cpp
Labels: sexps, documentation

#6514 make hitpoint sexps safer to use in debriefing
  code/hud/hudets.cpp
  code/object/object.cpp
  code/object/object.h
  code/object/objectshield.cpp
  code/object/objectshield.h
  code/parse/sexp.cpp
  code/scripting/api/objs/ship.cpp
  code/ship/ship.cpp
  code/ship/shiphit.cpp
Labels: fix, sexps

#6542 Cleanup few In-game Defaults
  code/controlconfig/controlsconfig.cpp
  code/graphics/2d.cpp
  code/graphics/opengl/gropengltexture.cpp
Labels: cleanup, graphics, ui

#6537 fix NaN for functional-if-then-else
  code/parse/sexp.cpp
Labels: fix, sexps

#6543 Fix child enums in lua sexps
  code/parse/sexp.cpp
Labels: cleanup, fix, sexps, scripting

#6500 Table based warp parameters and new custom warp animations.
  code/fireball/fireballs.cpp
  code/fireball/fireballs.h
  code/fireball/warpineffect.cpp
Labels: enhancement, graphics, feature

#6544 Allow Modders to Tune Guarding
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/ai/ai_profiles.h
  code/ai/aicode.cpp
Labels: enhancement, ai

#6550 Fix map container mutation issues
  code/parse/sexp_container.cpp
Labels: fix, sexps

#6553 Fix countermeasure virtvars
  code/scripting/api/objs/weaponclass.cpp
Labels: fix, scripting

#6554 Check for invalid player progress
  code/pilotfile/csg.cpp
  code/pilotfile/pilotfile.h
Labels: cleanup

#6556 fix random sidethrust call
  code/ai/aibig.cpp
Labels: fix, ai, Requested by Active Mod

#6546 Allow VFNTs to auto scale and disallow auto scaling in FRED
  code/graphics/render.cpp
  code/graphics/software/FSFont.cpp
  code/graphics/software/FSFont.h
  code/graphics/software/font.cpp
Labels: cleanup, ui
