Repository scp-fs2open/fs2open.github.com, pull requests merged in 2025-03, with the labels that each got.

#6574 HUD Config Rendering Methods PR 2/7
  code/hud/hudconfig.cpp
  code/hud/hudconfig.h
  code/hud/hudescort.cpp
  code/hud/hudescort.h
  code/hud/hudets.cpp
  code/hud/hudets.h
  code/hud/hudlock.cpp
Labels: enhancement, HUD, ui

#6611 Fixes missing XSTRs for Joysticks
  code/controlconfig/controlsconfigcommon.cpp
  code/localization/localize.cpp
Labels: cleanup, fix, controls, ui, localization / translation

#6612 Hide Disabled Controls in the F1 Screen
  code/gamehelp/gameplayhelp.cpp
Labels: cleanup, fix, controls, ui

#6599 Model eyepoint for set camera host flag
  code/camera/camera.cpp
  code/mod_table/mod_table.cpp
  code/mod_table/mod_table.h
Labels: enhancement, cleanup

#6610 enhance detection of model property errors
  code/model/modelread.cpp
  code/parse/parselo.cpp
  code/parse/parselo.h
Labels: cleanup

#6575 HUD Config Rendering Methods PR 3/7
  code/hud/hudconfig.cpp
  code/hud/hudconfig.h
  code/hud/hudmessage.cpp
  code/hud/hudparse.cpp
  code/hud/hudshield.cpp
  code/hud/hudshield.h
  code/hud/hudsquadmsg.cpp
  code/localization/localize.cpp
Labels: enhancement, HUD, ui

#6576 HUD Config Rendering Methods PR 4/7
  code/hud/hudreticle.cpp
  code/hud/hudreticle.h
  code/hud/hudtargetbox.cpp
  code/hud/hudtargetbox.h
Labels: enhancement, HUD, ui

#6613 Fixes cursor not restoring when exiting IMU GUI
  freespace2/freespace.cpp
Labels: fix, ui

#6577 HUD Config Rendering Methods PR 5/7
  code/hud/hudconfig.cpp
  code/hud/hudconfig.h
  code/hud/hudtarget.cpp
  code/hud/hudtarget.h
Labels: enhancement, HUD, ui

#6596 use vm_vector_2_matrix_norm on normalized vectors
  code/actions/types/ParticleEffectAction.cpp
  code/ai/aibig.cpp
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/autopilot/autopilot.cpp
  code/camera/camera.cpp
  code/debris/debris.cpp
  code/graphics/opengl/gropengldeferred.cpp
  code/graphics/shadows.cpp
  code/hud/hudartillery.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/math/staticrand.cpp
  code/math/vecmat.cpp
  code/math/vecmat.h
  code/mission/missionparse.cpp
  code/model/modelread.cpp
  code/nebula/neb.cpp
  code/nebula/neblightning.cpp
  code/network/multimsgs.cpp
  code/particle/ParticleEffect.cpp
  code/particle/hosts/EffectHostTurret.cpp
  code/playerman/playercontrol.cpp
  code/render/3ddraw.cpp
  code/scripting/api/libs/base.cpp
  code/scripting/api/objs/model.cpp
  code/scripting/api/objs/subsystem.cpp
  code/ship/shield.cpp
  code/ship/ship.cpp
  code/ship/shipfx.cpp
  code/starfield/supernova.cpp
  code/weapon/beam.cpp
  code/weapon/corkscrew.cpp
  code/weapon/flak.cpp
  code/weapon/weapons.cpp
  freespace2/freespace.cpp
Labels: cleanup

#6578 HUD Config Rendering Methods PR 6/7
  code/hud/hudconfig.cpp
  code/hud/hudconfig.h
  code/hud/hudparse.cpp
  code/hud/hudscripting.cpp
  code/hud/hudwingmanstatus.cpp
  code/hud/hudwingmanstatus.h
  code/mission/missiontraining.cpp
Labels: enhancement, HUD, ui

#6579 HUD Config Rendering Methods PR 7/7
  code/radar/radar.cpp
  code/radar/radar.h
  code/radar/radardradis.cpp
  code/radar/radarorb.cpp
  code/radar/radarorb.h
  code/radar/radarsetup.cpp
  code/radar/radarsetup.h
Labels: enhancement, HUD, ui

#6607 std::unique_ptr refactoring
  code/ai/ai.h
  code/globalincs/pstypes.h
  code/globalincs/utility.h
  code/graphics/opengl/gropengltexture.cpp
  code/graphics/shadows.cpp
  code/menuui/techmenu.cpp
  code/mission/missionparse.h
  code/missionui/missionshipchoice.cpp
  code/missionui/missionweaponchoice.cpp
  code/network/multiteamselect.cpp
  code/object/object.h
  code/parse/parselo.cpp
  code/parse/parselo.h
  code/playerman/playercontrol.cpp
  code/scripting/api/objs/shipclass.cpp
  code/scripting/api/objs/weaponclass.cpp
  code/ship/ship.cpp
  code/ship/ship.h
  code/weapon/weapon.h
  code/weapon/weapons.cpp
Labels: cleanup

#6614 upgrade line parsing and end-of-line checks
  code/parse/parselo.cpp
  code/parse/parselo.h
Labels: cleanup

#6617 Update conditional check for wingmen dots
  code/hud/hudwingmanstatus.cpp
Labels: fix, HUD

#6619 Fix ETS copy/paste error
  code/hud/hudets.cpp
Labels: fix, HUD

#6618 a few minor fixes
  code/nebula/neb.cpp
  code/nebula/neb.h
  qtfred/src/mission/missionsave.cpp
Labels: fix, qtfred

#6625 Fix mini-shield custom filename
  code/hud/hudshield.cpp
Labels: fix, HUD

#6623 Allows mods to fully disable energy transfering
  code/ai/ai_flags.h
  code/ai/ai_profiles.cpp
  code/hud/hudets.cpp
Labels: enhancement, ai

#6627 Fix hud errors
  code/hud/hudreticle.cpp
  code/hud/hudsquadmsg.cpp
  code/hud/hudtarget.cpp
Labels: fix, HUD

#6628 Fix script setting of subsystem hitpoints max
  code/scripting/api/objs/subsystem.cpp
Labels: fix, scripting

#6629 attempt to fix Coverity
  .github/workflows/weekly-coverity-scan.yaml
Labels: build

#6624 some refinement of shield quadrants
  code/hud/hudets.cpp
  code/hud/hudshield.cpp
  code/mission/missionparse.cpp
  code/network/multi_ingame.cpp
  code/network/multi_obj.cpp
  code/network/multimsgs.cpp
  code/object/object.cpp
  code/object/object.h
  code/object/objectshield.cpp
  code/parse/sexp.cpp
  code/scripting/api/objs/multi_objects.cpp
  code/scripting/api/objs/object.cpp
  code/scripting/api/objs/shields.cpp
  code/ship/shield.cpp
  code/ship/ship.cpp
  code/ship/shiphit.cpp
Labels: cleanup

#6633 ensure matrices are well-behaved
  code/parse/parselo.cpp
Labels: fix

#6639 Fix Ship Class Scripting API
  code/scripting/api/objs/shipclass.cpp
Labels: fix

#6631 Change ship display name
  code/parse/sexp.cpp
  code/parse/sexp.h
Labels: enhancement, sexps

#6581 Hud config upgrades
  code/hud/hud.cpp
  code/hud/hud.h
  code/hud/hudconfig.cpp
  code/hud/hudconfig.h
  code/hud/hudescort.cpp
  code/hud/hudets.cpp
  code/hud/hudlock.cpp
  code/hud/hudmessage.cpp
  code/hud/hudobserver.cpp
  code/hud/hudparse.cpp
  code/hud/hudreticle.cpp
  code/hud/hudshield.cpp
  code/hud/hudsquadmsg.cpp
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/hud/hudwingmanstatus.cpp
  code/localization/localize.cpp
  code/mission/missiontraining.cpp
  code/parse/sexp.cpp
  code/pilotfile/csg.cpp
  code/pilotfile/plr.cpp
  code/radar/radar.cpp
  code/radar/radarorb.cpp
  code/scripting/api/libs/hud.cpp
  code/scripting/api/libs/ui.cpp
  code/scripting/api/objs/hudconfig.cpp
  code/scripting/api/objs/hudconfig.h
Labels: enhancement, HUD, ui

#6642 Fix fire-point and flight cursor positions
  code/hud/hudreticle.cpp
Labels: fix, HUD

#6555 Move warp options to tables
  code/fireball/fireballs.cpp
  code/fireball/fireballs.h
  code/fireball/warpineffect.cpp
  freespace2/freespace.cpp
Labels: enhancement

#6644 Fix fog and skybox with alpha interaction
  code/model/modelrender.cpp
Labels: fix, graphics

#6647 fix compilation on linux arm64
  cmake/toolchain-gcc.cmake
Labels: fix, linux, compiler

#6646 handle starting shipname mismatch
  code/mission/missionparse.cpp
Labels: fix

#6643 skipmemymissionyo fixes
  code/localization/localize.cpp
  code/menuui/mainhallmenu.cpp
  code/mission/missioncampaign.cpp
  code/mission/missioncampaign.h
  code/popup/popup.cpp
  code/popup/popup.h
  code/scripting/api/libs/mission.cpp
Labels: fix, ui

#6650 fix normalized vector handling
  code/actions/types/ParticleEffectAction.cpp
  code/ai/aicode.cpp
  code/ai/aiturret.cpp
  code/camera/camera.cpp
  code/camera/camera.h
  code/hud/hudtarget.cpp
  code/hud/hudtargetbox.cpp
  code/math/staticrand.cpp
  code/math/vecmat.cpp
  code/model/modelread.cpp
  code/playerman/playercontrol.cpp
  code/render/3ddraw.cpp
  code/scripting/api/objs/subsystem.cpp
Labels: fix, gameplay

#6653 Fix VR sun popups
  code/render/3d.h
  code/render/3ddraw.cpp
  code/starfield/starfield.cpp
Labels: fix, graphics, vr

#6622 audit move semantics in the codebase
  code/decals/decals.cpp
  code/decals/decals.h
  code/graphics/opengl/ShaderProgram.cpp
  code/graphics/opengl/ShaderProgram.h
  code/graphics/opengl/gropenglshader.cpp
  code/graphics/opengl/gropenglshader.h
  code/io/cursor.cpp
  code/io/cursor.h
  code/io/joy-sdl.cpp
  code/model/animation/modelanimation.cpp
  code/model/animation/modelanimation.h
  code/object/object.cpp
  code/object/object.h
  code/scripting/api/objs/player.cpp
  code/scripting/api/objs/streaminganim.cpp
  code/scripting/api/objs/texture.cpp
  code/scripting/lua/LuaReference.cpp
  code/utils/event.h
Labels: cleanup
